### ISSUE TITLE
Keepass backend

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#14]
Lets' add a Keepass backend so Keyring can store and retrieve passwords from Keypass' kbd files.

http://www.keepassx.org/

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/14
- Originally reported by: Tarek Ziadé
- Originally created at: 2010-02-01T20:48:04.480

**Comment by jaraco** [comment]
Any updates on this?

---

Original comment by: Jens Timmerman

**Comment by jaraco** [comment]
I'm going to close this ticket, as it's been idle for over 3 years. If you're excited about support for Keepass, please feel free to put together a patch/pull request.

---

Original comment by: Jason R. Coombs

**Comment by piegamesde** [comment]
I'm interested in such a feature. Sadly, KeePass has no convenient interface for retrieving passwords. Here are the possibilities I can see to implement this:

- Use `kpscript` which uses the KeePass API as a standalone CLI. This has the drawback that it only works on KeePass files and not with the application itself. So even if you have KeePass open with your database unlocked this will require you to type in your password
- Use the `KeePassHTTP` plugin. It is widely used by browser extensions and uses http for password exchange. Drawbacks are that the application has to register a client to the plugin and that I think this looks a bit hacky.
- Create own plugin for KeePass that provides a proper interface (like via DBus).
- Extend `KeePassHTTP` to use DBus and such too.

**Comment by muggenhor** [comment]
KeePassXC has an implementation of the SecretService D-BUS API. But unfortunately KeePass stores its username in a camel case field named `UserName` instead of the lower case `username`. As a result I had to override the `SecretService` backend like this to work with both KeePassXC and other password managers: https://github.com/tomtom-international/hopic/blob/1ff427a6a93c8d514c3c9e0a32a6503a7bed09c0/hopic/credentials.py#L22-L52

**Comment by mitya57** [comment]
@muggenhor Interesting!

In Keyring you can override appid using class attributes. Maybe it would be easier if we made field names (like `username`) overridable too? Feel free to create a pull request for that.
