### ISSUE TITLE
Keyring access control in OS X

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#144]
When a new password is created through the OS X backend it's done through the `security` command, and the new keyring item is therefore set to always allow access from the `security` command. It seems reasonable to me that the creating process should have access, but because keyring delegates to the security command there's a particular problem: `security` will happily dump the password you're saving for anyone else! This access can be manually revoked, at the cost of manually confirming access each run, but there's no way to connect access to your particular application. (I'm not sure how it's verified anyways, so maybe this is a moot point without a signed binary or something of that sort.)

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/144
- Originally reported by: Sam Birch
- Originally created at: 2014-04-29T03:18:19.853

**Comment by jaraco** [comment]
Previously (before rev 438) there was native implementation for mac os x backend with ctypes.
I prefer native call to KeychainAPI instead of subprocess because ownership belongs to calling process not to 'security' app.
But I'm not sure it will work in virtual env or other sandboxes.

---

Original comment by: Denis Averin

**Comment by jaraco** [comment]
I also would prefer a ctypes implementation to a subprocess.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
As a temporary workaround, you can pass an option to security add-generic-password to make it so it does not give the 'security' process "trusted" permissions

from the security manpage:

> By default, the application which creates an item is trusted to
>             access its data without warning.  You can remove this default
>             access by explicitly specifying an empty app pathname: -T "". If
>             no keychain is specified, the password is added to the default
>             keychain.

---

Original comment by: Mark Grandi

**Comment by hryamzik** [comment]
@jaraco so is it possible to set up keyring to use the `-T ""` option?

P.S. is there any way to change the app name (security to a custom one)?

**Comment by jaraco** [comment]
I'm not sure. I think I answered that question elsewhere - maybe in a pull request or different ticket. But I believe passing `-T ""` would cause the application to force an interactive prompt on every access, which violates a primary goal of keyring (making interaction unnecessary for credential access).

**Comment by hryamzik** [comment]
@jaraco in fact it will just ask next time and if user click on "always allow" – it would go away forever. The issue here is that any app can call security framework and allowing it to access all the keys without prompt by default doesn't seem to be a good idea.

**Comment by jaraco** [comment]
I'll experiment with this idea, get a feel for the user experience.

**Comment by jaraco** [comment]
I've tried this technique, but when running the unit tests, it issues about 10 interactive prompts including ones that don't offer "always allow". Selecting "always allow" doesn't suppress the prompts for subsequent runs. The proposed technique is not viable.
