### ISSUE TITLE
Password exposure through process listing on OS X

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#145]
Keyring delegates password setting to `security` on OS X. When a password is set the process is Popen'd with the password in the command. I think this exposes the password to `ps`, e.g. you can see the arguments to `sleep` here:

```
>>> import subprocess
>>> subprocess.Popen(['sleep', '100'])
```

```
$ ps
PID   TTY           TIME CMD
50559 ttys002    0:00.01 sleep 100
```

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/145
- Originally reported by: Sam Birch
- Originally created at: 2014-04-29T03:27:46.155

**Comment by jaraco** [comment]
Oh. That seems not so good security at all. Perhaps keyring can pass the password using the IO stream. Otherwise, it may be necessary to use the C API, which I believe had other bugs.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Another way might be to pass it through an environment variable, but I'm not sure that `security` will read from one, and variable expansion in the command doesn't solve the problem (as `ps` shows it after expansion).

---

Original comment by: Sam Birch

**Comment by jaraco** [comment]
It looks like you could do it via stdin through `security`'s interactive mode:

```
$ security -i
security> add-generic-password -a 'TEST' -s 'TEST SERVICE' -w 'PASSWORD'
security> <EOF> 
```

You could even keep a process w/ interactive mode open to reduce the process startup overhead.

---

Original comment by: Sam Birch

**Comment by jaraco** [comment]
FYI, #13 is where subprocess-based invocation was added to workaround an apparent security issue with virtualenvs. It was released with Keyring 0.8.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I'm inclined to back out the changes from #13 and re-open that ticket. Performing passwords in-process (using ctypes) seems like the proper solution. If Mac disallows access to those APIs for virtualenv-hosted Pythons, then Apple should fix that issue or provide a means for the user to do so. That may be asking too much from Apple.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Thanks for the context Jason.

FWIW I'd rather have it working in virtualenv than proper, unfortunate as it is. I don't know all the details of the restrictions w/r/t the keychain in virtualenvs, but it sounds to me like the present policy is the "proper" one from Apple's perspective and they're unlikely to change it if so.

I'm by no means wedded to this solution, but I think the current `security` based system could be adapted relatively easily to use pipes through interactive mode. AFAIK pipes are secure. The caveat in my mind is that it doesn't address #144, but it seems that this is exactly what Apple's security model doesn't want you to be able to do.

---

Original comment by: Sam Birch

**Comment by jaraco** [comment]
I tried the interactive technique proposed above, but it doesn't seem to be working for me:

```
jaraco$ python
Python 2.7.5 (default, Aug 25 2013, 00:04:04)
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.0.68)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> proc = subprocess.Popen(['security', '-i'], stdin=subprocess.PIPE)
>>> proc.stdin
<open file '<fdopen>', mode 'wb' at 0x10254f6f0>
>>> proc.stdin.write('add-generic-password -a "TEST" -s "TEST SERVICE" -w "TEST PASSWORD"\n')
security: SecKeychainItemCreateFromContent (<default>): User interaction is not allowed.
add-generic-password: returned -25308
>>> proc.stdin.close()
>>> proc.wait()
36
>>>
```

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
Previously (before rev 438) there was native implementation for mac os x backend with ctypes.
It was more secure than call 'security' from subprocess, but more complicated for testing. 
Today it need a little bug fix for default keychain, but still it works.
I prefer native call to KeychainAPI instead of subprocess.

---

Original comment by: Denis Averin

**Comment by jaraco** [comment]
Issue #150 was marked as a duplicate of this issue.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
i can possibly look into making this work with ctypes again, or possibly using pyobjc 

---

Original comment by: Mark Grandi

**Comment by jaraco** [comment]
That's still my preference.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
#13 also has the link to some now-old ctypes code which I've used in the past: https://github.com/acdha/pymacadmin/blob/master/lib/PyMacAdmin/Security/Keychain.py. If that's of use, I would be happy to contribute it under the same license as the rest of keyring.

---

Original comment by: Chris Adams

**Comment by jaraco** [comment]
Try something like this

```
#!python

def securityCmd(command, *args):
    p1 = Popen(
        ["/usr/bin/security", "-i"], stdout=PIPE, stderr=STDOUT, stdin=PIPE)
    cmd = command + " " + " ".join(list(args)) + "\n"
    output = p1.communicate(cmd)[0]
    return p1.returncode, output
```

This runs security in interactive mode and sends the command to security's stdin in the communicate() call. Does not expose any command line arguments (other than "-i").

---

Original comment by: Andre LaBranche

**Comment by joneskoo** [comment]
Just a note if someone is working on this issue. I don't think legacy OS X 10.9 supports the interactive mode.

This would be important to fix. Doesn't seem like there would be a lot of code to change to use the interactive mode for OS X 10.10.

**Comment by rbranche** [comment]
I have a pull request (#165) for this issue as a quick workaround until the native ctypes implementation can be added.

**Comment by rbranche** [comment]
@jaraco @joneskoo I have access to 10.8 and 10.9 on one of my older machines, so I'll check these for the -i.

**Comment by rbranche** [comment]
@jaraco @joneskoo

10.8 security has -i:

```
dust:~ local$ sw_vers
ProductName:    Mac OS X
ProductVersion: 10.8.5
BuildVersion:   12F45
dust:~ local$ security -i
security> 
dust:~ local$ 
```

I assume that 10.9 does as well.

**Comment by rbranche** [comment]
#167 fixes the tests
