### ISSUE TITLE
(How) is it possible to list keyrings/keys?

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#151]
Hi there,

I maintain a little script ( https://github.com/mnagel/gnome-keyring-dumper ) that lists all keys in all keyrings for gnome keyring. Unfortunately it does not longer work with python3 and the most promising way to go I found is to use the python-keyring lib.

(How) is it possible to list keyrings/keys using python-keyring so I can change my keyring dumper to use python-keyring?

Best Regards
Michael

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/151
- Originally reported by: Anonymous
- Originally created at: 2014-10-22T20:40:46.215

**Comment by jaraco** [comment]
The current API does not provide a way to enumerate keys. I'd invite a pull request to support such functionality (even for only some keyrings).

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
If the system keyring is GNOME Keyring, you can use [SecretStorage](https://pypi.org/project/SecretStorage/) module (which is usually the default Python-Keyring backend on GNOME).

For example:

```python
import secretstorage
conn = secretstorage.dbus_init()
collection = secretstorage.get_default_collection(conn)
for item in collection.get_all_items():
    print(item.get_label())
    print(item.get_attributes())
```

Instead of using `get_all_items()` you can also specify a filter using `search_items()` method. See [the documentation](https://secretstorage.readthedocs.io/en/latest/) for details.

Also, you can use GNOME’s libgnome-keyring (the legacy library) and libsecret (the new library) in Python via GObject introspection.

---

Original comment by: Dmitry Shachnev

**Comment by BhasherBEL** [comment]
```python
for item in keyring.get_keyring().get_preferred_collection().get_all_items():
    print(item.get_label(), item.get_attributes())
```

**Comment by desk-job** [comment]
> If the system keyring is GNOME Keyring, you can use [SecretStorage](https://pypi.python.org/pypi/SecretStorage) module (which is usually the default Python-Keyring backend on GNOME).
> 
> For example:
> 
> ```
> :::python3
> import secretstorage
> bus = secretstorage.dbus_init()
> collection = secretstorage.get_default_collection()
> for item in collection.get_all_items():
>     print(item.get_label())
>     print(item.get_attributes())
> ```
> 
> Instead of using `get_all_items()` you can also specify a filter using `search_items()` method. See [the documentation](http://pythonhosted.org/SecretStorage/) for details.
> 
> Also, you can use GNOME’s libgnome-keyring (the legacy library) and libsecret (the new library) in Python via GObject introspection.
> 
> Original comment by: Dmitry Shachnev

Thanks for this. I had to edit it a bit though. You have to include `bus` as an argument for `get_default_collection()`. So that line should be as follows:

`collection = secretstorage.get_default_collection(bus)`

**Comment by mitya57** [comment]
Thank you. I updated that 7 years old comment :)
