### ISSUE TITLE
On Linux Servers where there is no Gnome Keyring service it falls back to Base64 encoded files

### ISSUE THREAD

**Issue by ghost** [jaraco/keyring#158]
Most Python code in Linux is going to run on a Server distro.  In this scenario there is no Gnome Keyring service so this code falls back to a base64 encoded values in a file which is readable/writeable only by the process that called set_password.  Creates a false sense of security.  Perhaps it should error and direct to a way to make it secure on Server-based Linux.  I've validated this in Ubuntu Server 14.

**Comment by yarikoptic** [comment]
I have recently filed a related, I think, #179 wishlist

**Comment by jaraco** [comment]
Also related is #117. Actually, I believe this request is a duplicate of #117.
