### ISSUE TITLE
keyring.get_password crash on windows/python 3.4.1

### ISSUE THREAD

**Issue by zdenop** [jaraco/keyring#160]
I have installed keyring (5.3) on windows 7 pro 64bit (but I am using 32 bit python).

Calling keyring.get_password cause crash of my python script (also in IDLE):

```
Python 3.4.2 (v3.4.2:ab2c023a9432, Oct  6 2014, 22:15:05) [MSC v.1600 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import keyring
>>> name = 'test'
>>> user = 'try_it'
>>> keyring.get_password(name, user)

>>> ================================ RESTART ================================
>>> 
```

The window crash message has this information (for IDLE crash/restart):

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name: pythonw.exe
  Application Version:  0.0.0.0
  Application Timestamp:    5432f86b
  Fault Module Name:    StackHash_f141
  Fault Module Version: 6.1.7601.18247
  Fault Module Timestamp:   521ea8e7
  Exception Code:   c0000374
  Exception Offset: 000ce753
  OS Version:   6.1.7601.2.1.0.256.48
  Locale ID:    1051
  Additional Information 1: f141
  Additional Information 2: f141612f2a85bff8528d4c63387f899a
  Additional Information 3: 0a71
  Additional Information 4: 0a71cae6ba929219378f843e9a865dc4

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

How to find reason what is problem?

**Comment by jaraco** [comment]
First step is identify which backend you're using.

```
C:\Users\jaraco> python -c "import keyring; print(keyring.core._keyring_backend)"
<keyring.backends.Windows.WinVaultKeyring object at 0x0000000002CEF710>
```

If you're not getting WinVaultKeyring, double-check that you have pywin32 installed or win32ctypes.

If you're getting the Win Vault keyring but still getting the error, then double-check that you have the correct pywin32 installed (32-bit for Python 32-bit, 64-bit for Python 64-bit).

I hope that helps track the issue.

**Comment by zdenop** [comment]
Thanks. I am getting WinVaultKeyring:
import keyring; print(keyring.core._keyring_backend)
<keyring.backends.Windows.WinVaultKeyring object at 0x03B18710>

I do not have installed win32ctypes, but I have installed 32bit pywin32 (pywin32-219.win32-py3.4.exe).
I tried to reinstall pywin32 and keyring but it does no helped.

I tried to turn of antivirus, but it does not help.
Any other hint?

**Comment by rom3es** [comment]
I had the same problem, installing pywin32-ctypes helped

**Comment by zdenop** [comment]
thanks! Installing pywin32-ctypes helped
