### ISSUE TITLE
keyring prints password to ps output on OSX

### ISSUE THREAD

**Issue by rbranche** [jaraco/keyring#164]
When calling the security command-line tool, keyring prints the password to ps output on OSX. keyring should use the interactive security prompt (security -i) and call.communicate('') instead of using add-<store>-password directly:

security -i
call.communicate('{} -a {} ... -U\n^D'.format(
    SecurityCommand('add', self.store), username, ...))

**Comment by rbranche** [comment]
Pull request: #165

**Comment by jaraco** [comment]
This is a duplicate of #145.
