### ISSUE TITLE
Python2 vs Python3 and PyQt4 vs PyQt5

### ISSUE THREAD

**Issue by jim-easterbrook** [jaraco/keyring#170]
I started porting an application that uses keyring from PyQt4 to PyQt5, but found it wouldn't run under Python2 because the kwallet backend uses PyQt4: `RuntimeError: the PyQt4.QtCore and PyQt5.QtCore modules both wrap the QObject class`.
I was surprised to find it does work under Python3 though. A bit of further investigation found that under Python3 I'm getting a different keying backend:

``` python
jim@brains:~$ python2
Python 2.7.8 (default, Sep 30 2014, 15:34:38) [GCC] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.get_keyring()
<keyring.backends.kwallet.Keyring object at 0x7f61bdc8d850>
>>> 
jim@brains:~$ python3
Python 3.4.1 (default, May 23 2014, 17:48:28) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.get_keyring()
<keyring.backends.Gnome.Keyring object at 0x7fe5246da320>
>>> 
jim@brains:~$ 
```

I'm running OpenSUSE 13.2 (KDE) but I'd like my application to be cross platform. I suspect kwallet's use of Qt4 is beyond our control, so should keyring choose a different backend if PyQt5 has already been imported?

**Comment by jim-easterbrook** [comment]
I've done a bit more reading and found that KDE dialogs use Qt4, and can't be used from a Qt5 application. KDE is moving to Qt5, so in future we'll have the reverse problem.

**Comment by jim-easterbrook** [comment]
If I install the KDE framework integration plugins I get the same behaviour in Python3 as in Python2, eliminating one of my variables. Now I just need to stop python keyring using the kwallet backend when using Qt5.
http://api.kde.org/frameworks-api/frameworks5-apidocs/frameworkintegration/html/index.html

**Comment by mitya57** [comment]
The Kwallet backend should be definitely ported to PyQt5/PyKDE5. Can you do a pull request for this? :)

**Comment by jim-easterbrook** [comment]
I've not found a Python KDE5 interface in the OpenSUSE repos, so using the KDE5 version of kwallet may not yet be possible. I'll have a go at making the kwallet backend fail more gracefully under Qt5 though.

**Comment by mitya57** [comment]
You are right indeed, pykde5 [does not yet have](http://quickgit.kde.org/?p=pykde5.git&a=tree&f=sip) support for kwallet.

**Comment by jim-easterbrook** [comment]
I've written a separate KWallet backend that uses D-Bus to communicate with the kwalletd daemon, and has no PyQt or pykde dependency. See pull request #174.

**Comment by tuxlife** [comment]
I add a check for DISPLAY variable to check X11

@jaraco please check #182

**Comment by jim-easterbrook** [comment]
As it's the `dbus.SessionBus()` call that raises an exception in your problem instance wouldn't it be easier just to move it into the `try: catch:` block? (Just in case there are systems where D-bus exists but $DISPLAY doesn't.)

**Comment by tuxlife** [comment]
@jim-easterbrook let move this discussion to #182 without duplication :smirk:
