### ISSUE TITLE
command line interface for initializing passwords

### ISSUE THREAD

**Issue by glyph** [jaraco/keyring#173]
Non-interactive tools that use keyring (including those that I've written) often recommend running the tool once interactively to initialize the password before setting up the non-interactive invocation.  It would be nice if I could just run a little command-line `keyring set some-password` and set the password explicitly, rather than having every tool need to implement a dance between `keyring` and `getpass`.

**Comment by jaraco** [comment]
@glyph: Can you use the provided command-line tool?

```
$ env/bin/keyring set
Usage: keyring [get|set|del] SERVICE USERNAME

keyring: error: Wrong number of arguments
$ env/bin/keyring set dummy dummy
Password for 'dummy' in 'dummy': 
```

Presumably, if the keyring you had configured required some interactive login, you would have been prompted for that before being prompted to set the password.

Does that do what you need?

**Comment by glyph** [comment]
@jaraco uh... hrm.  How long has that command-line tool existed?  I could have sworn I checked for one before filing this bug :).  This seems to address my needs just fine; thanks!

**Comment by jaraco** [comment]
It's been there a long time. Probably years. No problem, though. I don't think it's well advertised.

**Comment by jaraco** [comment]
I've added some documentation to the README, which should appear in the next release. ae83fd4d6a4

**Comment by glyph** [comment]
Thanks.

In my case, it wasn't really an issue of lack of visibility, I seriously thought I tried tab-completing "keyring" before filing this, in a virtualenv with keyring installed.  It must have been the wrong window or something.  Nevertheless, it's good to feature this in the README.
