### ISSUE TITLE
ImportWarning and PendingDeprecationWarning

### ISSUE THREAD

**Issue by dougthor42** [jaraco/keyring#180]
### Summary

Keyring has `ImportWarning` for mpl_toolkits and zope and `PendingDeprecationWarning` for the `imp` module.

I have no idea why python is trying to import those - I don't see either in the keyring source code.
### Steps to Reproduce

Run this command:
`python -W default -c "import keyring"`

Results in:
(Keyring v5.3)
![image](https://cloud.githubusercontent.com/assets/5386897/12124478/9c79cb66-b39a-11e5-8df6-5923ae0d3c4c.png)

(Keyring v5.7.1)
![image](https://cloud.githubusercontent.com/assets/5386897/12124590/0cf86fb4-b39b-11e5-9d9c-08792fd12b3f.png)
### System Info:
- **WinPython:** 3.4.3.2
- **Python:** 3.4.3, 64-bit
- **Keyring:** v5.3 and v5.7.1
- **Windows 7 Pro SP1, 64-bit**

**Comment by jaraco** [comment]
I'm pretty sure the ImportWarnings are not related to keyring... though perhaps the use of imp is drawing out those imports.

**Comment by jaraco** [comment]
I note that keyring 5.7.1 doesn't use the `imp` module anywhere, so whatever is triggering the warning is being imported as a side effect of something else present on the system.

Can you confirm the warnings only occur when you import keyring?

I'll need more information to track down what imports might be implicated. What do you get if you run: `py -3 -c "import keyring.backend; print(keyring.backend.get_all_keyring())"`

**Comment by jaraco** [comment]
Or perhaps this: `python -c "import logging, keyring.backend; logging.basicConfig(); print(keyring.backend.get_all_keyring())"`

**Comment by jaraco** [comment]
Ooh. Even better.

`python -W default -c "import logging, keyring.backend; logging.basicConfig(level=logging.INFO); print(keyring.backend.get_all_keyring())"`

**Comment by dougthor42** [comment]
Haha couldn't decide on one eh?

I only have python 3 installed so the `py -3` option won't work for me.

All of them displayed the same ImportError and PendingDeprecationWarning.

#### 1st request (with `-W default`):

```
C:\>python -W default -c "import keyring.backend; print(keyring.backend.get_all_keyring())"

C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory c:\winpyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\zope: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour o
f importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
[<keyring.backends.Windows.WinVaultKeyring object at 0x0000000001FE00B8>, <keyring.backends.Windows.RegistryKeyring obje
ct at 0x0000000001FE0128>, <keyring.backends.Windows.EncryptedKeyring object at 0x000000000352C320>, <keyring.backends.f
ile.PlaintextKeyring object at 0x0000000003564CC0>]
```

#### 2nd request:

```
C:\>python -c "import logging, keyring.backend; logging.basicConfig(); print(keyring.backend.get_all_keyring())"

[<keyring.backends.Windows.WinVaultKeyring object at 0x0000000002B3D400>, <keyring.backends.Windows.RegistryKeyring obje
ct at 0x00000000034BDB70>, <keyring.backends.Windows.EncryptedKeyring object at 0x000000000342DBE0>, <keyring.backends.f
ile.PlaintextKeyring object at 0x0000000002B3D080>]
```

#### 2nd request (with `-W default`):

```
C:\>python -W default -c "import logging, keyring.backend; logging.basicConfig(); print(keyring.backend.get_all_keyring(
))"

C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory c:\winpyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\zope: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour o
f importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
[<keyring.backends.Windows.WinVaultKeyring object at 0x000000000349F668>, <keyring.backends.Windows.RegistryKeyring obje
ct at 0x00000000034DC320>, <keyring.backends.Windows.EncryptedKeyring object at 0x0000000002B5E128>, <keyring.backends.f
ile.PlaintextKeyring object at 0x0000000002B5E0B8>]
```

#### 3rd request:

```
C:\>python -W default -c "import logging, keyring.backend; logging.basicConfig(level=logging.INFO); print(keyring.backen
d.get_all_keyring())"

C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory c:\winpyth
on34_x64\python-3.4.3.amd64\lib\site-packages\mpl_toolkits: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\importlib\_bootstrap.py:579: ImportWarning: Not importing directory C:\WinPyth
on34_x64\python-3.4.3.amd64\lib\site-packages\zope: missing __init__
  _warnings.warn(msg.format(portions[0]), ImportWarning)
C:\WinPython34_x64\python-3.4.3.amd64\lib\imp.py:32: PendingDeprecationWarning: the imp module is deprecated in favour o
f importlib; see the module's documentation for alternative uses
  PendingDeprecationWarning)
[<keyring.backends.Windows.WinVaultKeyring object at 0x000000000248E438>, <keyring.backends.Windows.RegistryKeyring obje
ct at 0x000000000352C320>, <keyring.backends.Windows.EncryptedKeyring object at 0x000000000248E0B8>, <keyring.backends.f
ile.PlaintextKeyring object at 0x0000000003564DD8>]
```

**Comment by dougthor42** [comment]
Also I fixed typos in the title and OP for other people searching for this error.

**Comment by dougthor42** [comment]
It looks like:
- `ImportWarning` occurs when importing `pkg_resources` in backend.py and core.py
  - I'm still investigating this further.
- `PendingDeprecationWarning` comes from the `pywintypes` package being imported on line 21 of `.../backends/Windows.py`. So obviously that's not something you can fix. I'll submit a PR to ignore warnings for that line.

More info to come later, I hope.

**Comment by dougthor42** [comment]
More info:

I did some more investigation at home with a different computer. Still using the same versions as above, but the packages on this machine are different.

I created a virtual environment folder `venv` with `python -m venv venv` and then tried installing keyring. pip reported 6x PEP440 warnings for the setuptools' `pkg_resources` package.

After installing, I ran `venv/Scripts/python.exe -W default -c "import keyring"` and only received the `PendingDeprecationWarning` which I narrowed down to the `pkg_resources` imports in `backend.py` and `core.py`, as I mentioned previously.

The ImportWarning was not shown on this 2nd system.

---

So it definitely seems like it's not 100% dependent on keyring. However, I think it might be prudent to remove the `pkg_resources` dependency if possible. I commented out all instances of it and it worked fine for me so I have no idea what it does :laughing:.

**Comment by mitya57** [comment]
Small advice: you can use python's `-Werror` flag to track the warnings easily (that will convert them to exceptions and thus a traceback will be printed).

**Comment by jaraco** [comment]
The `pkg_resources` dependency is the hook that enables third-party packages to supply keyring backend implementations through simple dependency injection. The supplied keyring implementations don't rely on it, which is why removing it doesn't affect your usage. It's possible that setuptools will remove usage of imp at some point, but I'm not aware of what it will take to do that. A ticket with setuptools is probably in order, though.

**Comment by dougthor42** [comment]
> python's `-W error` flag

That would have made things much faster. Oh well! Now I know :smile:

---

So now that we know where it's coming from, would you like me to submit a PR to suppress warnings on those imports? It would be beneficial for my case, but I also think that it's a bad idea to intentionally suppress warnings...

**Comment by jaraco** [comment]
I've filed [Setuptools 479](https://bitbucket.org/pypa/setuptools/issues/479/imp-is-deprecated) to capture the warning with pkg_resources. I don't think it's the place of keyring to suppress these warnings. If they need to be suppressed because the issue won't be solved in setuptools, then they should be suppressed there. Otherwise, the best I can recommend is for users impacted by these warnings to suppress them in the affected environments. I don't want keyring to be responsible for masking important warnings.

Interestingly, I don't get any warnings at all when simply importing pkg_resources. Is it possible the warnings are addressed in later versions of setuptools or Python? I'm using Python 3.5.1 and setuptools 19.3 (not yet released).

**Comment by jaraco** [comment]
Aah. According to [comments in the pull request](https://bitbucket.org/pypa/setuptools/pull-requests/129/try-not-to-use-deprected-imp-module-on-34/activity), the change to using `_imp` corrected the deprecation warnings, so indeed updating Setuptools >= 16.0 will likely address the issue.

**Comment by dougthor42** [comment]
Hmm... well it's definitely something on my end then. I'm running setuptools 19.2, so it's probably not that.

Doing another virtualenv and just getting setuptools 19.2 and keyring 6.1 seems to resolve the issue, but doing the same thing in my standard non-virtualenv area doesn't work...

Anyway, I'll close this issue since it's on my end not yours. Thanks for all your help though!
