### ISSUE TITLE
Passwords can't be retrieved?

### ISSUE THREAD

**Issue by Zizouz212** [jaraco/keyring#181]
I recently found the Keyring package within the PyPy and it's seemed to be pretty useful.

There hasn't been much in terms of usage/documentation, so I've been experimenting a bit. One thing seems to puzzle me:

```
import keyring

print keyring.get_password('system', 'Zizouz')
```

But that seems to return `None`.

Checking to see if there was a keyring even available, I used this simple snippet:

```
>>> keyring.get_keyring()
<keyring.backends.OS_X.Keyring object at 0x1022e77d0>
```

I'm trying to run an application, which runs a "video" about cybercrimes, and uses information from the system itself. :)

**Comment by jaraco** [comment]
You have to set the password before you can get the password. Where do you expect the password to have come from?

**Comment by Zizouz212** [comment]
Ok... But oddly, that doesn't make much sense. In the `repr` of the object, why is it showing a seemingly platform-specfic keyring?

I was sort of expecting it to come from a system related keychain, but I've probably drastically misunderstood something in the scheme of things. I'm assuming it's a sort of 'keychain' for applications?

Anyways, closing since it's not really an issue, and mostly arose from a misunderstanding. Keep up the great work :)

**Comment by jaraco** [comment]
Keyring provides different adapter back ends to the keychain services on the platform, as well as some simple standalone implementations.
