### ISSUE TITLE
XDG.Preference('Gnome') decorator has no effect

### ISSUE THREAD

**Issue by mitya57** [jaraco/keyring#186]
The `XDG.Preference(name)` decorator is supposed to multiply priority by 1.5 if `$XDG_CURRENT_DESKTOP` matches the name.

GNOME and Secret Service backends call it with `name = 'Gnome'`.

However, that is never the case. On the mainline GNOME desktop the value is `GNOME` (uppercase), however on desktops derived from GNOME the following values of `$XDG_CURRENT_DESKTOP` are also possible:
- `GNOME-Classic:GNOME` (the semi-official session provided by gnome-shell-extensions package)
- `GNOME-Flashback:GNOME` (the GNOME Flashback session)
- `GNOME-Flashback:Unity` (the GNOME Flashback session on Ubuntu systems)
- `Unity` (Ubuntu's default desktop)
- `X-CINNAMON` (Mint's default desktop)
- …

Even more, the desktops that are not derived from GNOME and don't have their own keyring implementation (i.e. Xfce, LXDE and almost any non-KDE desktop) are usually also using the GNOME Keyring. For example, it is used in Lubuntu (the LXDE Ubuntu flavor).

So we should either update the check to make sure it catches all these variants, or drop it altogether (as it was doing nothing in its current form anyway). I prefer the latter variant.

**Comment by jaraco** [comment]
Is there another way to give preference to systems that supply Gnome Keyring? Perhaps now that the system uses GnomeKeyring the library, that's sufficient to detect viability or not. Is that true? If so, I agree - let's remove this decorator.

**Comment by mitya57** [comment]
In my opinion, this behavior should work:
- If the desktop is KDE/Plasma, then use KWallet;
- Otherwise, if Secret Service is available, use it;
- Otherwise, if GNOME Keyring is available, use it;
- Then fall back to something else.

**Comment by jaraco** [comment]
Keyring doesn't have a procedural resolution of keyring such that an if/else tree could be constructed to match that behavior. However, the priority order resolution with escape hatches should achieve what you describe:
- Give kwallet highest priority, raise RuntimeError if desktop is not KDE/Plasma.
- Give SecretService next highest priority.
- Give Gnome next highest priority.
- Give other backends lower priority.

And that is essentially what we have - kwallet.DBusBackend is 5.1, SecretService is 5.0, Gnome is 1.0, and other backends are generally lower, though some are not, such as pyfs which is 2.0.

Problem is, what about kwallet.QtKeyring? Should it be 5.0? Maybe it should also be downgraded to 1.0. What if secretstorage is available but not a suitable version?

Keyring attempts to solve this problem (or more accurately avoid explicitly solving the problem) by allowing each of the backends to independently declare their relative viability. If Gnome should generally be preferred over other backends that might be available (pyfs, keyczar), then we should raise its priority accordingly.

**Comment by mitya57** [comment]
Yes, I have nothing against the priorities mechanism.

> And that is essentially what we have - kwallet.DBusBackend is 5.1, SecretService is 5.0, Gnome is 1.0, and other backends are generally lower, though some are not, such as pyfs which is 2.0.

In my opinion GNOME should have higher priority than pyfs. Or at least equal.

> Problem is, what about kwallet.QtKeyring? Should it be 5.0? Maybe it should also be downgraded to 1.0.

I agree about downgrading it, provided that QtKeyring uses Qt 4 which is EOL upstream (since December).

> What if secretstorage is available but not a suitable version?

I think Keyring works with 1.0, which was the first stable version.

> Keyring attempts to solve this problem (or more accurately avoid explicitly solving the problem) by allowing each of the backends to independently declare their relative viability. If Gnome should generally be preferred over other backends that might be available (pyfs, keyczar), then we should raise its priority accordingly.

Right. I want to mention that GNOME and Secret Service backends are compatible and do the same thing (libgnome-keyring uses Secret Service internally, it's just deprecated and mostly undeveloped).

**Comment by mitya57** [comment]
Also,

> Give kwallet highest priority, raise RuntimeError if desktop is not KDE/Plasma.

Maybe better would be making the priority lower if desktop is not KDE/Plasma. This way people can still use it on other desktops when they want to.
