### ISSUE TITLE
OS X backend not working when called from cron

### ISSUE THREAD

**Issue by n8henrie** [jaraco/keyring#188]
It was [recently brought to my attention](https://github.com/n8henrie/pycookiecheat/issues/8) that `python-keyring` doesn't appear to be able to retrieve a password from the OS X Keychain when called from cron. Any ideas why?

I assumed it has to do with the keychain being locked, but I'm able to access the keychain from cron using the `security` program (which keyring uses as its default OS X backend), as long as my cron entry first unlocks the keychain, e.g. `security unlock-keychain -p MYPASS /path/to/login.keychain && security find-generic-password -a ACCOUNT -s SERVICE -g >> outfile.log`

Also -- totally irrelevant, but -- what prompted the change to GitHub from Bitbucket? I didn't seen any discussion of it with the relevant commit, maybe I missed it.

**Comment by jaraco** [comment]
I did respond to this issue with a detailed explanation and questions, but I now find (a) my response was lost and (b) my browser form memoizer doesn't have any record of my response. :(

Short answer - keyring can't guess `MYPASS`, so if unlocking the keychain is required by the `security` command, it will be required for Python keyring as well.

**Comment by n8henrie** [comment]
Thanks a bunch for the quick response.

I'm not sure that I communicated the issue properly:
- If I **do not** unlock the keychain, I _cannot_ access passwords from cron using the `security` command, e.g. `* * * * * security find-generic-password -a foo -s bar -g >> out.log 2>&1`
- If I **do** unlock the keychain, I _can_ access passwords from cron using the `security` command, e.g. `security unlock-keychain -p MYPASS /path/to/login.keychain && security find-generic-password -s "foo" -a "bar" -g /path/to/login.keychain >> /path/to/fake.log 2>&1`
- **Even if** I unlock the keychain, I am unable to access the password with keyring, e.g. 
  - `security unlock-keychain -p MYPASS /path/to/login.keychain && /usr/local/bin/python3 -c 'import keyring; print(keyring.get_password("foo", "bar"))' >> /path/to/fake.log 2>&1`
  - `security unlock-keychain -p MYPASS /path/to/login.keychain && /usr/local/bin/keyring get "foo" "bar" >> /path/to/fake.log 2>&1`

Looking into it a bit further, I think it may actually be an issue with the default keychain, as demonstrated by examining what happens when we look at the `default-keychain` when called by `subprocess` (like keyring does) in a regular terminal vs in cron:

``` bash
$ /usr/local/bin/python3 -c "import subprocess; print(subprocess.check_output(['security', 'default-keychain']))"
b'    "/Users/n8henrie/Library/Keychains/login.keychain"\n'
```

vs in cron: `* * * * * /usr/local/bin/python3 -c "import subprocess; print(subprocess.check_output(['security', 'default-keychain']))" >> /path/to/fake.log 2>&1`

``` bash
$ cat fake.log
"/Library/Keychains/System.keychain"
```

So while your response makes sense that the keychain must be unlocked, I think this is a different issue and as I stated above unlocking the keychain doesn't seem to affect the issue. I'll continue looking through the source code for a way to specify the path to the keychain in question, but I don't see one in the OSX backend at least.

**Comment by n8henrie** [comment]
I think I can confirm that it's not a keychain unlocking issue but rather a default keychain issue.

I created a custom keyring that inherits from the default OS X keyring and simply adds a kwarg `keychain` to the `security` command, if provided. I then had to add the ability to accept kwargs into the `get_password` function in `core.py`. With these modifications, I'm able to get passwords when called from `cron` _without_ doing anything to unlock the keychain.

https://github.com/jaraco/keyring/pull/190

**Comment by jaraco** [comment]
Thanks for the PR in #190. This is fixed in 7.2 (via the new `keychain` attribute on the Keyring).

**Comment by frcojimenez** [comment]
I am writing to you concerning some troubleshooting related to the keyring module.

I have some python code which queries an encrypted user name and password previously set up with the keyring tools.
This is the call I have in the code:

1    keyring.get_keyring().keychain = '/path_to/login.keychain'
2    password = keyring.get_password(“server", “user”)

This call works perfectly fine when I execute my code interactively, say :

```
python mycode.py
```

getting the requested password and continuing the code execution.

However, I aim to run this code via the crontab environment (i.e. in the backend). 
When doing so,I get this output: 

```
File “~/mycode.py", line 102, in <module>
    sendEmail(fromaddr,toaddr,subject,body)
  File "~/mycode.py", line 57, in sendEmail
    password = keyring.get_password(“server", “user")
  File "/Library/Python/2.7/site-packages/keyring/core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/Library/Python/2.7/site-packages/keyring/backends/OS_X.py", line 44, in get_password
    return api.find_generic_password(self.keychain, service, username)
  File "/Library/Python/2.7/site-packages/keyring/backends/_OS_X_API.py", line 92, in find_generic_password
    NotFound.raise_for_status(status, msg)
  File "/Library/Python/2.7/site-packages/keyring/backends/_OS_X_API.py", line 43, in raise_for_status
    Error.raise_for_status(status, msg)
  File "/Library/Python/2.7/site-packages/keyring/backends/_OS_X_API.py", line 35, in raise_for_status
    raise cls(status, msg)
keyring.backends._OS_X_API.Error: (-25308, "Can't fetch password from system")
```

I know that when keyring is called from the backend a different login.keychain file path is assumed,
that is why I set this up via the line tagged with ‘1’ in my example.

I followed this thread (among others as in: https://pythonhosted.org/keyring/history.html ) though not a particular solution in my case.

Just to add some more info, my python version is 2.7.10 and I am using keyring: 10.0.2 and I am using OS-X el Capitan.
Do you have any easy solution to this thread?

Thanks in advance

**Comment by jaraco** [comment]
@frcojimenez Are you calling `security unlock-keychain` as [described here](https://github.com/jaraco/keyring/issues/188#issuecomment-170450391)?

**Comment by frcojimenez** [comment]
Hi Jason,

when I do the suggested call from the terminal it returns my encrypted password MYPASS.

security unlock-keychain -p MYPASS /path/to/login.keychain && security find-generic-password -a ACCOUNT -s SERVICE -g >> outfile.log

Is there any clever way to implement this in the python code by calling any python function related to the keyring?

Thanks
Xisco

**Comment by frcojimenez** [comment]
Additionally, using a ’security’ call which needs the password itself to unlock the keychain does not seem to be optimally safe no?

**Comment by jaraco** [comment]
@frcojimenez Okay, so there are several factors here.
- Yes, you have to unlock the keychain somehow. The context in which the cron job runs does not have the credentials to unlock the keychain. There's no way around this fact. If you want the cron job to have access to your passwords in your keychain, you'll have to give the cron job your password.
- Since you've confirmed that you can unlock with `security unlock-keychain`, just invoke that command before invoking your python script, which by setting `.keychain` on the keyring and having unlocked the keychain should be sufficient.

> Is there any clever way to implement this in the python code by calling any python function related to the keyring?

Not really. Well, maybe someone could work out the API calls necessary to perform the `unlock` operation in Python code, but still that Python code would need the user's password to be supplied in order to perform the unlock.

**Comment by frcojimenez** [comment]
Sorry again,
but the command does not work in crontab script
- \* \* \* \* security unlock-keychain -p MYPASS /pathto/login.keychain && security find-generic-password -a User -s Server -g

This is the output I get:
security: SecKeychainUnlock /Users/xisco/Library/Keychains/login.keychain: The user name or passphrase you entered is not correct.

While it works when prompting the same directly in the terminal .

**Comment by jaraco** [comment]
I'm not able to replicate your findings, but I'm not able to make it work either. I've put this in my crontab:

```
* * * * * security unlock-keychain -p MYPASS /Users/jaraco/Library/Keychains/login.keychain 2>&1 > /Users/jaraco/unlock.out && security find-generic-password -a jaraco -s SYSTEM -g /Users/jaraco/Library/Keychains/login.keychain 2>&1 > /Users/jaraco/pw.out
```

Where of course I've substituted my actual password for MYPASS and a valid system for SYSTEM. When the crontab runs, both ~/pw.out and ~/unlock.out are empty.

**Comment by jaraco** [comment]
I can't figure out why the commands aren't outputting anything at all. I tried swapping `> outfile` and `2>&1`, but that had no effect. I set up a crontab with a simple `echo foo > /Users/jaraco/foo.txt` and that emitted the text to foo.txt just as I would have expected.

**Comment by frcojimenez** [comment]
Yes, I think it is just a question of accessing to the keychain which for some reason it is not allowed from a crontab environment. 

My keychain is accessible with no password. I do not know what else I should do.

**Comment by jaraco** [comment]
When I run that command outside of the crontab, I'm prompted to allow the lookup, and I've only clicked Allow. If I click Deny, the command outputs nothing just as seen in the crontab. So this time, I select Always Allow, and now the crontab command does emit the password. So @frcojimenez, there's something wrong with your invocation or your system is configured differently from mine.

**Comment by jaraco** [comment]
> I do not know what else I should do.

Not that I would necessarily recommend it, but you could switch to Windows, which has a much cleaner API for the credential vault and scheduled tasks - if a scheduled task runs as a particular user, that task is set up with the password of the user and runs in the context of that user and has access to that user's secrets. It's one feature I miss dearly.

**Comment by frcojimenez** [comment]
Well it seems that I identified the problem though I do not like the solution. Crontab seems to interact with the Keychain “System roots”. Unlocking this solves the issue, though it could create a security problem.

**Comment by jaraco** [comment]
crontab will interact with the "System roots" keychain unless you specify a keychain as I've done in my crontab.

**Comment by frcojimenez** [comment]
Hi jaraco,

I just gave up. It worked easily with the mac launchd
with no password prompt.

Xisco

**Comment by n8henrie** [comment]
This works fine for me. Are you guys remembering to set the path to the keychain (the end result of this issue and my PR)?

Using `crontab -e` as my usual user, no `sudo`.

```
* * * * * security unlock-keychain -p 'MYPASS' /Users/me/Library/Keychains/login.keychain && /usr/local/bin/python -c 'import keyring; keyring.get_keyring().keychain = "/Users/me/Library/Keychains/login.keychain"; print(keyring.get_password("foo", "bar"))' >> /Users/me/fake.log 2>&1
```

**Comment by shahbhoomi** [comment]
There is one another way of giving cron job the access to our keychains. When you add the password using security add-generic-password -s SERVICE -a USERID -w PASSWORD, you have to first run the script manually to give "always allow" permission to python to access the keychains and then go to your keychains from app launcher and copy that service and password from login.keychians to syste,.keychains as cronjob by default looks into system keychains and not login keychains. This worked for me. Hope it helps!

**Comment by andrejs-sisojevs** [comment]
I had similar problem, when doing `keyring.get_password('Chrome Safe Storage', 'Chrome')` on Python2.7. (sorry, it's not related to `cron`)
Downgraded keyring to v8.7, and it works fine now.

**Comment by quinncomendant** [comment]
I don't use the Python keyring library, but this issue comes up top when googling for issues loading passwords from `security find-generic-password` in crontab, so I'll add my comment to help others who have this problem in general.

I am running a backup script via cron (the excellent [restic](https://restic.net/)) and loading the backup password from the keychain using the `security find-generic-password` command. Because cron runs as root (?) it uses the `/Library/Keychains/System.keychain` keychain, and the password must be added there for it to be accessible by `security find-generic-password`:

(In the following commands, replace `PASSWORDNAME` with the name of the password item, e.g., `restic-backup-pw`, and replace `PASSWORDACCOUNT` with a string that helps identify what will be using the password, e.g., `restic`. These aren't used anywhere except as keys to look up the password in the keychain.)

1. First, add the password to the login keychain: `security add-generic-password -s PASSWORDNAME -a PASSWORDACCOUNT -w`
2. Open `Keychain Access.app`, then copy the PASSWORDNAME item from the *login* keychain to the *System* keychain (right-click and *Copy* the item in login keychain, then right-click and *Paste* in the system keychain).
3. Now you can access the password in cron by running: `security find-generic-password -s PASSWORDNAME -a PASSWORDACCOUNT -w`
3. If you don't need to load the password from the terminal (only cron) you can delete the entry from the login keychain.

I too experienced the confusing issue of `security` responding with an empty string, no errors, etc. I tried to specify my login keychain as an argument to `security` but that never worked. Cron would only load from the system keychain, so the password has to be there.

The comments from @frcojimenez, @jaraco, and @shahbhoomi were very helpful, thanks guys!
