### ISSUE TITLE
Trouble using the default keyring

### ISSUE THREAD

**Issue by GijsTimmers** [jaraco/keyring#192]
Using Ubuntu 14.04

I've been using `keyring` for quite some time now. For some reason, it doesn't work anymore:

```
In [1]: import keyring

In [2]: keyring.get_keyring()
Out[2]: <keyring.backends.file.EncryptedKeyring at 0x7fbe9410cc50>
```

The problem is that `keyring` should've called GnomeKeyring, not the file keyring. Right now, it's asking me for a password every time, probably because it uses the file keyring instead of the Gnome keyring. This happens on both Python 2 and Python 3. Where can I start troubleshooting?

**Comment by mitya57** [comment]
Can you run this in Python console and check what it prints?

``` python
from gi.repository import GnomeKeyring
GnomeKeyring.get_default_keyring_sync()
```

**Comment by GijsTimmers** [comment]
Sure:

```
In [1]: from gi.repository import GnomeKeyring
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-416f98f22e7d> in <module>()
----> 1 from gi.repository import GnomeKeyring

ImportError: cannot import name GnomeKeyring

In [2]: GnomeKeyring.get_default_keyring_sync()
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-2-4f0d736ec98c> in <module>()
----> 1 GnomeKeyring.get_default_keyring_sync()

NameError: name 'GnomeKeyring' is not defined

In [3]: 
```

**Comment by mitya57** [comment]
Then you need to install these packages to use GNOME backend:
- python-gi / python3-gi
- gir1.2-gnomekeyring-1.0

Or, even better, install python-secretstorage / python3-secretstorage and use the superior Secret Service backend.

**Comment by GijsTimmers** [comment]
Thank you, that fixed it.
