### ISSUE TITLE
Docs linked to from Pypi are incorrect

### ISSUE THREAD

**Issue by jeffwidman** [jaraco/keyring#194]
https://pypi.python.org/pypi/keyring points to docs at http://pythonhosted.org/keyring/ which seems either extremely outdated or flat-out incorrect. 

Suggested fix: Either update the docs, or update the link on Pypi.

**Comment by jim-easterbrook** [comment]
As I understand it, once you create pythonhosted documentation you can't remove it or the link to it from PyPI. On my projects I ended up adding a "these docs are out of date, please see xxx" message on every page on pythonhosted and then not updating them further.

**Comment by mitya57** [comment]
You can upload a zip with any HTML files to PyPI, including one index.html with a redirect to somewhere else…

**Comment by jaraco** [comment]
The docs on pythonhosted should be the ones generated from the docs/ folder in the package. Is that not the case? It's probably just the case that they're boilerplate and need to be fleshed out. It doesn't seem to me that they're incorrect.

**Comment by jeffwidman** [comment]
Well, the ones up there now look pretty ugly if they're the boilerplate. I don't know that they need to be fleshed out, as the Readme here on GitHub is pretty solid. 

It would be nice to have something there other than boilerplate since pythonhosted is linked to from Pypi. Rather than uploading the readme to pythonhosted, why not do as @mitya57 suggested and put up an index.html with a 301 to the project readme here on github? 

AFAIK, this is only something someone with Pypi access rights can do, not something I can do with a PR... otherwise I'd be more than happy to submit a PR.

**Comment by jaraco** [comment]
I suspect the meta http-equiv redirect could be added using a [meta directive](http://docutils.sourceforge.net/docs/ref/rst/directives.html#meta).

**Comment by jeffwidman** [comment]
Agreed, it still requires a flat file though with the redirect...

**Comment by jaraco** [comment]
How does that look?

**Comment by jeffwidman** [comment]
:+1:
