### ISSUE TITLE
Fallback scenario is ugly

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#198]
In #117 and specifically in https://github.com/jaraco/keyring/issues/117#issuecomment-171330756, the assertion was made that

> @rsyring: Getting a None returned is probably never going to be the actual desired behavior.

But as reported in [bitbucket issue migration 60](https://github.com/jeffwidman/bitbucket-issue-migration/issues/60#issuecomment-174611323), that's not the case for libraries that optionally include keyring support but fallback to prompting for a password when none is found in the keyring ([bitbucket_issue_migration](https://github.com/jeffwidman/bitbucket-issue-migration/blob/master/migrate.py#L103-L104), ...) and almost certainly others.

I'm thinking we should change the fail backend to only error on set/delete.

**Comment by jeffwidman** [comment]
Possibly could use some kind of flag when calling keyring (such as `verbose=True`) that explains where in the password retrieval process it failed

**Comment by jaraco** [comment]
The reason I say the fallback scenario is ugly is this - say someone wants to optionally offer keyring support but doesn't want to impose it, one must trap the import error but also trap the RuntimeError:

```
try:
    import keyring
except ImportError:
    # mock keyring
    class keyring:
        @staticmethod
        def get_password(system, username):
            return

try:
    password = keyring.get_password(system, username)
except RuntimeError:
    password = getpass()
```

**Comment by jaraco** [comment]
I see the value in failing fast - for developers who rely on there being a valid password found in the keyring. Perhaps keyring could supply a helper function that switches between the fail.Keyring and a null.Keyring, something like:

```
# fail fast
keyring.fallback_hard_fail()
```

or

```
# fail soft
keyring.fallback_soft_fail()
```

I don't like that either, because it provides a new API that's not recognized by the current applications.

**Comment by jaraco** [comment]
I also recognize that the fail fast behavior has been useful in signaling to users who've upgraded, but depend on other backends, that they have something they need to address, which makes me somewhat reluctant to reverse this behavior, as intrusive as it might be.

**Comment by jaraco** [comment]
I'm considering this instead for the recommended fallback behavior:

```
try:
    import keyring
    if keyring.get_keyring().priority == 0:
        raise ValueError()
except (ImportError, ValueError):
    # add mock
```

Then, the simple invocation of keyring.get_password can remain the same in the code... and this technique works with older versions of keyring as well. Yes, I think that's my preference.

**Comment by rsyring** [comment]
Maybe a better API for testing if keyring is usable:

``` python
import keyring
if keyring.is_usable():
...
```

That way, the logic involving priority is internal to keyring and if you wanted to change it in the future, you can, without breaking external apps.

Not sure `is_usable()` is the right name.
