### ISSUE TITLE
Version checking exception not handled

### ISSUE THREAD

**Issue by rileycrane** [jaraco/keyring#199]
This [line](https://github.com/jaraco/keyring/blob/e3ec4793e92eea66f66b01c0f329f08963a43edc/keyring/__init__.py#L12) throws a `DistributionNotFound` exception which is not handled by the `ImportError` handler

**Comment by jaraco** [comment]
I expect keyring to be installed via setuptools/pip and thus fulfill the call to `require`. Under what conditions does DistributionNotFound occur?
