### ISSUE TITLE
Advice: configure default keyring backend in Travis-CI

### ISSUE THREAD

**Issue by balta2ar** [jaraco/keyring#203]
My recent commit has caused test failure on Travis-CI. Specifically, I see `RuntimeError: No recommended backend was available`: https://travis-ci.org/coursera-dl/coursera-dl/jobs/105369498#L313

Could you please advise the simplest way to configure default keyring backend in Travis-CI infrastructure? Thank you.

**Comment by jaraco** [comment]
I apologize for the inconvenience. See #117 for the rationale. I recommend:
- Easiest way to get compatibility with older versions (and especially if you want the insecure backends) is to additionally require `keyrings.alt`.
- If you want keyring availability to be optional, consider using something like [this technique](https://github.com/jeffwidman/bitbucket-issue-migration/commit/f4a2e18b1a8e54ee8e265bf71d0808c5a99f66f9).
