### ISSUE TITLE
how to use with gnome-keyring

### ISSUE THREAD

**Issue by teto** [jaraco/keyring#205]
sorry to use bugtracker but mailing list asks for some registration.

I can't get my passwords using /usr/local/bin/keyring (i.e. not programmatically) registered in gnome-keyring with the a. Apparently the gnome backend was removed ? It's too bad the utility can't list available backends.
I would prefer not resort to the Headless DBUS tricks in the readme

**Comment by mitya57** [comment]
Do you have python-secretstorage installed?

**Comment by teto** [comment]
I just installed it but it still fails. It's frustrating not to know basic details such as:
which backend/store (path ?!) does the script use, did it fail on service or username ?
Because right now I have no idea which store is in use.
That would be cool to have a -v verbose flag.

**Comment by jaraco** [comment]
If you want compatibility with keyring 7.x, simply install the `keyrings.alt` package (via pip or setuptools) and your Gnome Keyring functionality should return like magic.

**Comment by mitya57** [comment]
If you have GNOME Keyring running and python-secretstorage installed, then keyring should work. I agree it would be nice if the CLI could print some debug information. Can you try passing `-b keyring.backends.SecretService.Keyring` to keyring executable and see if anything changes?

Also, if you only need a simple tool to store secrets _only_ for GNOME Keyring, you may try `secret-tool` from `libsecret-tools` package.

**Comment by teto** [comment]
I launched seahorse and apparently my required secrets were not registered with the matching services used by python-keyring.
I managed to make it working via registering the password with the utility. 
I find the whole keyring idea really sexy but it's really hard to get a clear idea of the whole thing, like you got libgnome-keyring superseeded by libssecret, kwallet, can they interoperate ? service names have apparently no standard etc...  I wish debian/other would write some blogpost to make everything clearer :)
Thanks for the help

**Comment by mitya57** [comment]
Secret Service is the new standard (libsecret and python-secretstorage are using it).

Unfortunately GNOME Keyring is the only living implementation of Secret Service. There used to be KSecrets (a successor to KWallet), but it is kinda abandoned (KF5 port is still not finished) and KDE still uses Kwallet (thankfully we have a backend for it too).

I am the Debian maintainer of keyring-related packages, so maybe this comment can replace the blog post :)

**Comment by teto** [comment]
Nevertheless what a mess :'(
Thanks for the explanation  :)
