### ISSUE TITLE
"No recommended backend available" on Windows 10

### ISSUE THREAD

**Issue by mpibpc-mroose** [jaraco/keyring#207]
With the newest keyring I get the following exception:

```
>> keyring.get_password('System', 'mroose')
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "D:\Local_Development\NEW_imspectorDevelopment\ve-imspector-website\lib\site-packages\keyring\core.py", line 42, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "D:\Local_Development\NEW_imspectorDevelopment\ve-imspector-website\lib\site-packages\keyring\backends\fail.py", line 18, in get_password
    raise RuntimeError("No recommended backend was available")
RuntimeError: No recommended backend was available
```

... when installing an older version (7.2 as for another project) everything is fine.

I'm using Windows 10 r1511 Enterprise x64.

**Comment by jaraco** [comment]
Hi @mpibpc-mroose. If it was working with an earlier version, that means you were probably using the Registry backend. To easily fix the issue, simply install `keyrings.alt` in addition to keyring, and it should continue to behave as before.

Even better would be to start from scratch with or migrate your passwords to the WinVaultKeyring, the one recommended keyring for Windows. For that keyring to be available, you need to install `win32ctypes` or pywin32.

**Comment by mpibpc-mroose** [comment]
Hi Jason,

many thanks for that fast response. As promised it now works like a charm using pywin32. Maybe one could extend the docs a bit for dump users like me?

Best, Marco
