### ISSUE TITLE
use of is not for nuymbers

### ISSUE THREAD

**Issue by barry-scott** [jaraco/keyring#211]

**Comment by barry-scott** [comment]
The code in backends/OS_X.py uses lines like this:
if code is not 0:

While this will usually work, its not reliable.
This is object identify not numberic equality. It relies on C Pythons interning 0 as a fixed object identity.

Use if code != 0: for realiable tests.

**Comment by jaraco** [comment]
Is this a theoretical issue or a practical one? Is there a Python implementation where this implementation would not behave as expected?

**Comment by barry-scott** [comment]
I do not know if there is a implementation that will break you.
Its a coding error in my book because you depend on undefined behavior of C Python.
I give you the feedback as a code inspection comment.

**Comment by jaraco** [comment]
Thanks for the clarification. Can you submit a pull request?

**Comment by barry-scott** [comment]
Yes I'll figure out the work flow and do that for you. May take a few days.

**Comment by jaraco** [comment]
After changing `is not 0` to `!= 0`, the [tests now fail](https://travis-ci.org/jaraco/keyring/jobs/115467936). The prior implementation worked. Thank goodness for tests and CI.

**Comment by jaraco** [comment]
Well, that's weird. Backing out the change [didn't correct the failure](https://travis-ci.org/jaraco/keyring/jobs/115469208). But I see other tests that did pass with the change. So the test failure is intermittent and unrelated to the patch.

**Comment by jaraco** [comment]
So I've stripped the backout changeset 88cb5c5 mentioned above.

**Comment by barry-scott** [comment]
FYI this is why you must not code number is X:

> > > x = 20000
> > > y = 20000
> > > x == y
> > > True
> > > x is y
> > > False
> > > x = 0
> > > y = 0
> > > x == y
> > > True
> > > x is y
> > > True
