### ISSUE TITLE
Restore ctypes implementation for OS X backend

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#217]
There have been several issues relating to the implementation of the OS X Keyring delegating to the security command:
- #215 Tests fail intermittently on OS X
- #145 Password exposure through process listing on OS X
- #144 Keyring access control on OS X

Additionally, there are other unreported issues, such as the workaround for #145 only working for some passwords but not others.

As a result, I've started work on a pure ctypes implementation in the [osx-api branch](https://github.com/jaraco/keyring/commits/osx-api). 

Subsequently, there are several issues that should be revisited before reverting back to a CFFI or ctypes interface:
- This current implementation drops support added in #73, which would have to be restored (or explicitly dropped).
- Confirm reasonable virtualenv behavior, respecting #13 OSX install broken when using virtualenvs.
- Confirm that there's no regression w.r.t. #11 Should not use login.keychain on OSX.

My plan is to address these issues and run the branch version locally for some time to understand the impacts of these changes. I welcome others to do the same or provide feedback.

**Comment by copumpkin** [comment]
I was about to file a bug on exactly this, since it seemed pretty bad that the permission was coming from `security` (i.e., #144). A thousand :+1: from me.

**Comment by jaraco** [comment]
> This current implementation drops support added in #73, which would have to be restored (or explicitly dropped).

Given the non-response to the release of keyring 2.1 in #10 and #73, I'm not even sure that feature was ever used. To complicate matters, the API is not congruent, [requiring many more parameters](https://github.com/jaraco/keyring/blob/dc793d1/keyring/backends/_OS_X_API.py#L47-L65) than the generic password counterpart. I'm going to add a warning to the released versions to see if there are any users relying on this functionality.

**Comment by jaraco** [comment]
> Confirm reasonable virtualenv behavior, respecting #13 OSX install broken when using virtualenvs.

I've confirmed that keyring does work naturally in Python 3 venv environments, and in `virtualenv` environments, the user is prompted to Allow or Deny or Always Allow "python" to access the keyring. In other words, this change fixes #144 and regresses w.r.t. #13. Overall, I think the change is beneficial, especially in light of copumpkin's endorsement. It's clear that a backward-incompatible release will be necessary, however.

**Comment by jaraco** [comment]
> Confirm that there's no regression w.r.t. #11 Should not use login.keychain on OSX.

This is now done, with the default keyring now being honored by default.

**Comment by jaraco** [comment]
As far as I'm concerned, this is ready to go. I'm going to sit on it for another week and see if there are any revelations from the release of 8.6 (with a warning for 'internet' passwords). Please feel free to install the latest osx-api branch and test in your environments.
