### ISSUE TITLE
Add dependency on secretstorage on linux

### ISSUE THREAD

**Issue by reece** [jaraco/keyring#231]
[As suggested](https://github.com/jaraco/keyring/issues/223#issuecomment-221812313) by @mitya57, make keyring dependent on secretstorage on linux. This should enable easy installation with `pip install keyring` that just works (see #223 and #230).

**Comment by reece** [comment]
I took a stab at this, but ran into a problem.

```
diff -r a1ebf1ee9fe3 setup.py
--- a/setup.py  Fri Jun 10 07:45:44 2016 -0400
+++ b/setup.py  Sun Jun 19 08:11:29 2016 -0700
@@ -38,6 +38,8 @@
     extras_require={
         'test': test_requirements,
         ':sys_platform=="win32"': ['pywin32-ctypes'],
+        ':sys_platform=="linux2"': ["secretstorage"],  # python 2
+        ':sys_platform=="linux"': ["secretstorage"],   # python 3
     },
     setup_requires=[
         'setuptools_scm>=1.9',
```

This fails:

```
$ deactivate; rm -fr ve; pyvenv ve; source ve/bin/activate; pip install -U pip
$ python setup.py install; python -c "import keyring; print(keyring.get_keyring())"
...
<keyring.backends.fail.Keyring object at 0x7f41580084e0>
```

But, installing secretstorage first works (for me, anyway):

```
$ deactivate; rm -fr ve; pyvenv ve; source ve/bin/activate; pip install -U pip
$ pip install secretstorage 
$ python setup.py install; python -c "import keyring; print(keyring.get_keyring())"
...
<keyring.backends.SecretService.Keyring object at 0x7fe36d861ba8>
```

@mitya57 & @jaraco, does anything here ring a bell? This is with Python 3.5.1 and pip 8.1.2.

**Comment by mitya57** [comment]
Maybe dependencies from `extras_require` are not installed by setuptools by default? Maybe try making that a hard dependency (i.e. `install_requires`)?

**Comment by jaraco** [comment]
It's possible that `setup.py install` doesn't resolve extras dependencies (with or without markers). I haven't looked into it much though. I would expect `python -m easy_install .` to install with the marker dependencies.

I do find the use of `linux2` and `linux` to disambiguate Python versions a bit awkward. Is that really how the markers work? Yuck.

> Maybe dependencies from extras_require are not installed by setuptools by default? Maybe try making that a hard dependency (i.e. install_requires)?

The technique that @reece is proposing is the correct one - extras with no name should be installed by default if the markers match. I would first try the `easy_install` technique, and failing that, I would double-check that the marker syntax evaluates to True (using pkg_resources or packaging to eval the markers). I'd also double-check that you have the latest setuptools installed (though I think setuptools >0.7 supports these markers).

**Comment by reece** [comment]
Answers to the above questions:
- The environment markers work fine in pip (at least in pip 8.1.2, setuptools 23.0.0). I can see setuptools attempting to install secretstorage and dependencies. I also added a bogus package name to highlight the failure.
- `python -m easy_install .` behavior is identical to pip.
- Yes, it appears the python 3 dropped the "2" in "linux2". Check out this table in [PEP-508](https://www.python.org/dev/peps/pep-0508/#environment-markers). (It was news to me also.)

**Comment by reece** [comment]
Here're results from lots of experimentation:

When dbus-python is installed by pip, either directly or indirectly via secretstorage requirements, you get a valid dbus installation.

When dbus-python is installed by setuptools (sp. `python setup.py install` or `python setup.py develop`), an incomplete and non-functional dbus package is installed.

As a further test, I also built a tarball distribution for keyring with environment marker support included. It installed fine with pip even though the exact same code didn't work with setup.py.

So, here's what I think this means for this feature: we can include environment support and it will work without hassle (via pip) for users. However, developers will need to remember that they must manually install dbus-python (perhaps in a requirements-dev.txt file, or somesuch).

@jaraco: you cool with that?

---

Example (ubuntu 16.04, python 3.5.1):

```
(ve) snafu$ cd keyring

(ve) snafu$ reset-ve () { deactivate; rm -fr ve; pyvenv ve; source ve/bin/activate; pip install -U pip setuptools; }

(ve) snafu$ reset-ve 
...

# 1) install dbus-python and check what's really installed

(ve) snafu$ pip install dbus-python
...
Successfully installed dbus-python-1.2.4

(ve) snafu$ /bin/ls -l $VIRTUAL_ENV/lib/python3.5/site-packages/*dbus*
-rwxr-xr-x 1 reece reece   1014 Jun 22 14:28 /home/reece/projects/keyring/ve/lib/python3.5/site-packages/_dbus_bindings.la
-rwxr-xr-x 1 reece reece 571136 Jun 22 14:28 /home/reece/projects/keyring/ve/lib/python3.5/site-packages/_dbus_bindings.so
-rwxr-xr-x 1 reece reece   1083 Jun 22 14:28 /home/reece/projects/keyring/ve/lib/python3.5/site-packages/_dbus_glib_bindings.la
-rwxr-xr-x 1 reece reece  31104 Jun 22 14:28 /home/reece/projects/keyring/ve/lib/python3.5/site-packages/_dbus_glib_bindings.so

/home/reece/projects/keyring/ve/lib/python3.5/site-packages/dbus:
total 192
-rw-r--r-- 1 reece reece 17927 Jun 22 14:28 bus.py
-rw-r--r-- 1 reece reece   211 Jun 22 14:28 _compat.py
-rw-r--r-- 1 reece reece 27773 Jun 22 14:28 connection.py
-rw-r--r-- 1 reece reece  8804 Jun 22 14:28 _dbus.py
-rw-r--r-- 1 reece reece 15207 Jun 22 14:28 decorators.py
-rw-r--r-- 1 reece reece  4674 Jun 22 14:28 exceptions.py
-rw-r--r-- 1 reece reece  3376 Jun 22 14:28 _expat_introspect_parser.py
-rw-r--r-- 1 reece reece  3482 Jun 22 14:28 gi_service.py
-rw-r--r-- 1 reece reece  2097 Jun 22 14:28 glib.py
-rw-r--r-- 1 reece reece  3828 Jun 22 14:28 __init__.py
-rw-r--r-- 1 reece reece  1831 Jun 22 14:28 lowlevel.py
drwxr-xr-x 3 reece reece  4096 Jun 22 14:28 mainloop
-rw-r--r-- 1 reece reece 24788 Jun 22 14:28 proxies.py
drwxr-xr-x 2 reece reece  4096 Jun 22 14:28 __pycache__
-rw-r--r-- 1 reece reece  4624 Jun 22 14:28 server.py
-rw-r--r-- 1 reece reece 35359 Jun 22 14:28 service.py
-rw-r--r-- 1 reece reece   529 Jun 22 14:28 types.py

/home/reece/projects/keyring/ve/lib/python3.5/site-packages/dbus_python-1.2.4-py3.5.egg-info:
total 20
-rw-r--r-- 1 reece reece    1 Jun 22 14:28 dependency_links.txt
-rw-r--r-- 1 reece reece 1207 Jun 22 14:28 installed-files.txt
-rw-r--r-- 1 reece reece  730 Jun 22 14:28 PKG-INFO
-rw-r--r-- 1 reece reece 3069 Jun 22 14:28 SOURCES.txt
-rw-r--r-- 1 reece reece   40 Jun 22 14:28 top_level.txt

# 2) now python setup.py install from keyring directory
(ve) snafu$ reset-ve 
...

(ve) snafu$ python setup.py install
...
Searching for dbus-python
Reading https://pypi.python.org/simple/dbus-python/
Best match: dbus-python 1.2.4
Downloading https://pypi.python.org/packages/ad/1b/76adc363212c642cabbf9329457a918308c0b9b5d38ce04d541a67255174/dbus-python-1.2.4.tar.gz#md5=7372a588c83a7232b4e08159bfd48fe5
Processing dbus-python-1.2.4.tar.gz
Writing /tmp/easy_install-_846jrmw/dbus-python-1.2.4/setup.cfg
Running dbus-python-1.2.4/setup.py -q bdist_egg --dist-dir /tmp/easy_install-_846jrmw/dbus-python-1.2.4/egg-dist-tmp-1zg9b8d6
warning: install_lib: 'build/lib.linux-x86_64-3.5' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Moving dbus_python-1.2.4-py3.5-linux-x86_64.egg to /home/reece/projects/keyring/ve/lib/python3.5/site-packages
Adding dbus-python 1.2.4 to easy-install.pth file

Installed /home/reece/projects/keyring/ve/lib/python3.5/site-packages/dbus_python-1.2.4-py3.5-linux-x86_64.egg
Finished processing dependencies for keyring==0.1.dev853+n7f15646ddd56

(ve) snafu$ /bin/ls -l $VIRTUAL_ENV/lib/python3.5/site-packages/*dbus*
-rw-r--r-- 1 reece reece 2023 Jun 22 14:20 /home/reece/projects/keyring/ve/lib/python3.5/site-packages/dbus_python-1.2.4-py3.5-linux-x86_64.egg

```

Notice the `warning: install_lib: 'build/lib.linux-x86_64-3.5' does not exist -- no Python modules to install`.  Indeed, we get only a dbus .egg file, and it's empty. There are no .la or .so files, and no .py stubs.

I still don't really understand why this is happening or which package is the problem.

**Comment by reece** [comment]
P.S. I just noticed that platform_system == Linux for python 2 and 3. Let's use that for decreased yuck.

**Comment by jaraco** [comment]
> you cool with that?

Yup. It sounds like the correct solution and that there's just a defect with setuptools/easy_install installing dbus-python, which is a separate issue (that may be addressed or not).

**Comment by mitya57** [comment]
Thanks @reece. Based on your [comment](https://github.com/jaraco/keyring/issues/231#issuecomment-227890717) and on https://github.com/jaraco/keyring/issues/230#issuecomment-228074508, it looks like dbus-python installs from PyPI may be broken.

So I will remove it from `install_requires` in SecretStorage, and we should recommend the users to install `dbus-python` from distro packages instead.

**Comment by reece** [comment]
@mitya57: That's not what I meant to suggest. I think you can and should leave it.

The major observation (that I still can't explain) is that installing dbus-python via pip works, both directly (pip install dbus-python) or indirectly (e.g., pip install secretstorage). That is probably the most common end-user case.

When installing via `python setup.py install`, setuptools dutifully tries to build dbus-python, but the result is a non-functional dbus-python installation.

This isn't an issue with PyPI per se (or at least I don't see that).

My guess is that the cause is an unfortunate interaction between setuptools and dbus-python's use of distutils for extension building, but I don't really have good data to support that.

**Comment by mitya57** [comment]
dbus-python uses a hand-crafted setup.py and its own build system, so I am not much surprised that it's broken. There is even no distinction between build and install targets, and no distinction between `build_py` and `build_ext`.
