### ISSUE TITLE
Break hard dependency on secretstorage

### ISSUE THREAD

**Issue by BenjamenMeyer** [jaraco/keyring#236]
A hard dependency on secret storage as pulled in by #231 makes keyring unrealistic for services, such as RESTful APIs where adding dbus and a formal FreeDesktop oriented Keyring Service is not feasible or desired. In these situations, having a simple in-memory, encrypted store that is short term is best if the keyring is used at all - it may not be, thus forcing installation of additional services is not desirable.

**Comment by mitya57** [comment]
If your problem is SecretStorage dependency on dbus-python, then it was downgraded to `extras_require` in SecretStorage 2.2.1 release.

I don't think Keyring has an in-memory backend, but you can find a quite simple file-based backend in `keyrings.alt` package.

**Comment by BenjamenMeyer** [comment]
FWIW, I'm dealing with dependency of dependencies, and know multiple similar projects are effected - not all of which I control. Tools need to be aware of the kinds of projects that use them and how their changes which may seem minor affect those tools. In this case, the downstream ramifications are quiet substantial. I do hope the 2.2.1 release helps; I'll be testing it tomorrow.

And I've used `keyring` plenty in the past without having any kind of formal keyring service installed, without dbus being installed, etc. So this change has a very big impact.

**Comment by BenjamenMeyer** [comment]
@mitya57 I did test `secretstorage` 2.2.1 and I can get through the install; however, given the harshness of that issue I would still highly recommend `keyring` make `secretstorage` a soft dependency, use it if available otherwise do something else like with previous behavior.

**Comment by mitya57** [comment]
SecretStorage per se is a very lightweight pure-Python package, I don't see what can be wrong with depending on it. The only problem was that it pulled in python-dbus, but as I said that is reverted now.

**Comment by mitya57** [comment]
I am closing this issue. If you really believe there are any problems with secretstorage, please file another bug explaining them. Thanks!
