### ISSUE TITLE
Get all accounts for the specified service

### ISSUE THREAD

**Issue by lokhman** [jaraco/keyring#238]
Hi there! Thank you very much for this brilliant library.

The only thing, which I found missing and really important to have, is the method to return a list of user names for a specified service. Something like:

```
keyring.set_password("system", "username 1", "password 1")
keyring.set_password("system", "username 2", "password 2")

usernames = keyring.get_usernames("system")
print(usernames)  # ['username 1', 'username 2']
```

Do you have any plans of adding this functionality (at least for some backends)?

**Comment by jaraco** [comment]
Yes, I think it's desirable to have such functionality - in general, to have the ability to enumerate all services and all usernames. To my knowledge, there is currently no such functionality and no specific plans to implement it.

I welcome you to put together the functionality, but I'd like for it to be (a) tested and (b) available to the recommended backends before rolling it into a release.

Is that a feature you would be interested in working on?

**Comment by jaraco** [comment]
I'm closing this ticket as languishing, but I welcome others to revive it with an implementation.

**Comment by samsaara** [comment]
+1
