### ISSUE TITLE
Allow encrypted keyring without password or have unencrypted keyring as default

### ISSUE THREAD

**Issue by musiKk** [jaraco/keyring#241]
This probably sounds strange and maybe there is a better solution. I use tools which use keyring. These tools are integrated into various workflows (compile and build steps). Every time I build I have to provide the password. This is not always straight forward as the message that queries my password gets buried in normal build output.

I don't believe that this adds any security whatsoever as I already use a single character password in order to make this not maddeningly unusable. The keyring that's used is `EncryptedKeyring` (for some reason KWallet is not used; I run KDE). Another solution I'd be fine with would be to be able to set the default keyring to `keyrings.alt.FileBackend` but I found no way to do this without changing said tools (which I don't have control over).

**Comment by jaraco** [comment]
https://github.com/jaraco/keyring#customize-your-keyring-by-config-file
