### ISSUE TITLE
platform_.config_root() on Linux should prefer ~/.config over ~/.local

### ISSUE THREAD

**Issue by dmacvicar** [jaraco/keyring#242]
```
python -c "import keyring.util.platform_; print(keyring.util.platform_.config_root())"
```

Returns  `~/.local/share/python_keyring`, but that is a directory intended for data.

**Comment by jaraco** [comment]
Yes, that's what [the spec says](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html). Making the change would be trivial, but would break existing deployments that are looking for it in .local. Do we just make a backward-incompatible release and ask everybody to move their config? Or could something else be done?

**Comment by toyg** [comment]
The Right Thing To Do™ would be to check in .config, if not found then check in .local -> if found, migrate to .config and delete (with a warning); if not found, just write new stuff to .config.

**Comment by jaraco** [comment]
> The Right Thing To Do™...

This is what we did when in 0.8 when we migrated config from ~/.keyringrc (or similar) to the new platform-aware location. Then in 1.0, we removed the compatibility support. I suggest following a similar model so the compatibility code doesn't linger forever.

**Comment by jaraco** [comment]
This effort seems to have languished. I welcome anyone to revive it and provide a pull request. In the meantime, I'll close it.
