### ISSUE TITLE
Errors on Mac OS Sierra (10.12)

### ISSUE THREAD

**Issue by ttarhan** [jaraco/keyring#243]
On the GM of Mac OS Sierra, the OS X backend doesn't work. It simply returns an error:

$ keyring set something else
Password for 'else' in 'something': 
Traceback (most recent call last):
  File "...../bin/keyring", line 11, in <module>
    load_entry_point('keyring', 'console_scripts', 'keyring')()
  File "build/bdist.macosx-10.12-intel/egg/keyring/cli.py", line 101, in main
  File "build/bdist.macosx-10.12-intel/egg/keyring/cli.py", line 64, in run
  File "build/bdist.macosx-10.12-intel/egg/keyring/core.py", line 48, in set_password
  File "build/bdist.macosx-10.12-intel/egg/keyring/backends/OS_X.py", line 37, in set_password
keyring.errors.PasswordSetError: Can't store password on keychain

I haven't looked into the cause yet. It appears to be in native-land.

**Comment by jaraco** [comment]
I just installed the latest macOS Sierra (GM2 from 15 Sep) and the latest keyring in it, and I don't encounter the problem:

```
Jasons-MacBook-Pro:~ jaraco$ curl https://bootstrap.pypa.io/get-pip.py -o - | python - --user
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 1488k  100 1488k    0     0  3038k      0 --:--:-- --:--:-- --:--:-- 3044k
Collecting pip
  Downloading pip-8.1.2-py2.py3-none-any.whl (1.2MB)
    100% |████████████████████████████████| 1.2MB 871kB/s 
Collecting wheel
  Downloading wheel-0.29.0-py2.py3-none-any.whl (66kB)
    100% |████████████████████████████████| 71kB 7.5MB/s 
Installing collected packages: pip, wheel
Successfully installed pip wheel
Jasons-MacBook-Pro:~ jaraco$ python -m pip install --user keyring
Collecting keyring
  Using cached keyring-9.3.1-py2.py3-none-any.whl
Installing collected packages: keyring
Successfully installed keyring-9.3.1
Jasons-MacBook-Pro:~ jaraco$ python -m keyring set foo bar
Password for 'bar' in 'foo': 
Jasons-MacBook-Pro:~ jaraco$ python -m keyring get foo bar
test
Jasons-MacBook-Pro:~ jaraco$ python 
Python 2.7.10 (default, Jul 30 2016, 18:31:42) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.core._keyring_backend
<keyring.backends.OS_X.Keyring object at 0x10bcba650>
```

So this issue is probably just another manifestation of #219.

I suggest reading up there and doing some tests in your environment to see if there are security settings preventing your python executable from accessing the keyring.
