### ISSUE TITLE
PyPI long_description seems to be invalid ReST

### ISSUE THREAD

**Issue by mgedmin** [jaraco/keyring#245]
https://pypi.python.org/pypi/keyring looks like this:
![ekrano nuotrauka is 2016-10-20 11-28-59](https://cloud.githubusercontent.com/assets/159967/19552433/69ea9bd8-96b8-11e6-8f10-511258dd97d0.png)

This usually happens when the long_description in setup,py contains invalid ReStructuredText markup.

I couldn't find any problems with the long_description in current git master, so this'll likely be fixed with the next release.  (I usually `pip install restview` and use `restview --long-description` to check for PyPI markup problems.)

**Comment by mgedmin** [comment]
Whoops this is a duplicate of #240, which is already fixed.

Maybe a new release is due?  Or maybe you could fix the long_description manually using the web form on PyPI?

**Comment by jaraco** [comment]
New release has been cut and the PyPI page renders nicely.
