### ISSUE TITLE
Current PyPI packages don't install the CLI script

### ISSUE THREAD

**Issue by acdha** [jaraco/keyring#247]
In the past, `pip install keyring` would install a script. Using Python 2.7.12 at least on OS X, that is no longer the case using either the wheel or source installs. `python -m keyring` works.

(I noticed because [`pipsi`](https://pypi.python.org/pypi/pipsi) checks for and fails commands which don't install scripts)

**Comment by jaraco** [comment]
That's almost certainly a bug introduced when I merged with the skeleton. I'll get it restored promptly.

**Comment by acdha** [comment]
Awesome, thanks!
