### ISSUE TITLE
Test for an available backend

### ISSUE THREAD

**Issue by djmattyg007** [jaraco/keyring#265]
What is the correct way to test for an available backend? I would like to check before I start operating on the keyring in my application so that I can provide a sensible error message if no backends are available.

**Comment by jaraco** [comment]
I'm not sure that's possible, except to trap the exception when no backend is available.

**Comment by djmattyg007** [comment]
I'd be happy to implement this myself. Would you welcome a PR that added this functionality?

**Comment by jaraco** [comment]
Definitely open to improvements. I worry that it may not be possible to make the library introspectable given the curr

**Comment by jaraco** [comment]
Current design. On second thought. It may be possible to simply inspect `keyring.core.get_keyring()` to see if it's a fail.Keyring (or similar).

**Comment by jaraco** [comment]
Go for it and let us know what you find.

**Comment by frispete** [comment]
@djmattyg007 is it a specific backend, you're after, or the default keyring?

**Comment by djmattyg007** [comment]
Any keyring at all, such that calls to `set_password`, `get_password` and `delete_password` will succeed as expected.

**Comment by frispete** [comment]
Hmm, I'm not sure, I follow. What's wrong with:
```
>>> import keyring
>>> kr = keyring.get_keyring()
>>> kr.name
'kwallet DBusKeyringKWallet4'
```
or 
```
>>> for kr in keyring.backend.get_all_keyring(): print(kr.name)
... 
kwallet DBusKeyringKWallet4
file PlaintextKeyring
fail Keyring
file EncryptedKeyring
cryptfile CryptFileKeyring
```
Well, the one that starts with fail is better to be ignored...

In case, you wonder, I'm experimenting with encrypted file backends:
```
>>> for kr in keyring.backend.get_all_keyring():
...   if 'file ' in kr.name:
...     print('%s: %s' % (kr.name, kr.scheme))
...   else:
...     print(kr.name)
... 
kwallet DBusKeyringKWallet4
file PlaintextKeyring: no encyption
fail Keyring
file EncryptedKeyring: PyCrypto [PBKDF2] AES256.CFB
cryptfile CryptFileKeyring: Cryptodome [Argon2] AES OCB
```

**Comment by jaraco** [comment]
Oh, the priority is probably a good indicator:

```
>>> keyring.get_keyring().priority
5
>>> for kr in keyring.backend.get_all_keyring():
...   print(kr.priority, kr.name)
... 
5 OS X Keyring
0 fail Keyring
```

If `keyring.get_keyring().priority` is not truthy (greater than 0), then you have the fail keyring.
