### ISSUE TITLE
KWallet as Backend

### ISSUE THREAD

**Issue by Mebus** [jaraco/keyring#269]
Hallo,

what's the correct way of setting KWallet as backend using keyring.set_keyring ?

I keep getting this error: "TypeError: The keyring must be a subclass of KeyringBackend"

Mebus

**Comment by frispete** [comment]
Hi Mebus,

how about this:
```
>>> keyring.get_keyring()
<keyring.backends.SecretService.Keyring object at 0x7f31bee3d7f0>
>>> 
>>> kwallet5 = keyring.backends.kwallet.DBusKeyring()
>>> kwallet4 = keyring.backends.kwallet.DBusKeyringKWallet4()
>>> 
>>> keyring.set_keyring(kwallet4)
>>> 
>>> keyring.get_keyring()
<keyring.backends.kwallet.DBusKeyringKWallet4 object at 0x7f31c2c15d30>
```

Hth, Pete

**Comment by rulatir** [comment]
**Where** do these incantations **GO**?

**Comment by jaraco** [comment]
@rulatir - you would use these steps in a Python program or interactively in any Python interpreter before you invoke `get_password` or `set_password`. If you're using the CLI interface (`keyring` command), you'll instead need to set the keyring in a config file [per these instructions](https://github.com/jaraco/keyring#config-file-content). Hope that helps.
