### ISSUE TITLE
Key.set_password fails

### ISSUE THREAD

**Issue by omushpapa** [jaraco/keyring#270]
I am using OpenSUSE Leap 42.1. I ran `import keyring` `keyring.set_password('system', 'username', 'password')` in terminal and it fails with
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Giantas/Developer/2theboringstuff/2theboringstuff/lib/python3.4/site-packages/keyring/core.py", line 48, in set_password
    _keyring_backend.set_password(service_name, username, password)
  File "/home/Giantas/Developer/2theboringstuff/2theboringstuff/lib/python3.4/site-packages/keyring/backends/fail.py", line 23, in get_password
    raise RuntimeError(msg)
RuntimeError: No recommended backend was available. Install the keyrings.alt package if you want to use the non-recommended backends. See README.rst for details.
```
OpenSUSE come with KWallet. I do not understand what is the problem then.

**Comment by mitya57** [comment]
Please make sure you are using the latest version of Python-Keyring, and have [dbus-python](https://www.freedesktop.org/wiki/Software/DBusBindings/#dbus-pythonbasedondbus-glib) installed for the same Python version.

**Comment by omushpapa** [comment]
I have installed keyring==10.3.1 and [dbus-1-python3](https://software.opensuse.org/package/dbus-1-python3) is installed but still the same error.

**Comment by mitya57** [comment]
What happens if you try to run this?
```pycon
>>> from keyring.backends.kwallet import DBusKeyring
>>> DBusKeyring.priority
```

**Comment by omushpapa** [comment]
```pytb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/Giantas/Developer/2theboringstuff/2theboringstuff/lib/python3.4/site-packages/keyring/util/properties.py", line 22, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/Giantas/Developer/2theboringstuff/2theboringstuff/lib/python3.4/site-packages/keyring/backends/kwallet.py", line 28, in priority
    raise RuntimeError('python-dbus not installed')
RuntimeError: python-dbus not installed
```

**Comment by mitya57** [comment]
So that’s it. Please make sure that `import dbus` works first, after that Keyring should work too.

**Comment by omushpapa** [comment]
There's no module name `python-dbus`????

**Comment by mitya57** [comment]
Are you running the system Python 3? Your `site-packages` path looks quite strange to me…

**Comment by omushpapa** [comment]
Am running from a virtualenv environment

**Comment by mitya57** [comment]
If you are running it from a virtualenv, then the system package will not help. You need to copy the binaries to your virtualenv, or build dbus-python yourself.

**Comment by jaraco** [comment]
or run keyring from the system python or build the virtualenv with `--system-site-packages`.

**Comment by omushpapa** [comment]
That worked, thanks @jaraco !!
