### ISSUE TITLE
Docker Secrets Backend?

### ISSUE THREAD

**Issue by smallnamespace** [jaraco/keyring#271]
Are there any plans to implement a backend for [Docker Secrets](https://docs.docker.com/engine/swarm/secrets/#examples)?

Looks like the secret just gets written somewhere to `/run/secrets/<secret_name>`, so the actual usage is pretty trivial, but it would be nice for code that is already using `keyring` to continue to do so.

**Comment by jaraco** [comment]
Sounds interesting. Seems like it would be a good application of a third-party extension. I recommend creating the package as keyrings.docker, modeled after keyrings.alt. Then, users on docker could install that to the target env. The keyrings might even have a higher priority especially if it can detect when it's in a viable Docker environment.

**Comment by jaraco** [comment]
I've updated the README to give some guidance on how to build third-party backends. I hope that helps you or others get started on a proposal like this. Feel free to comment here if you have questions with the concept.
