### ISSUE TITLE
lastpass backend

### ISSUE THREAD

**Issue by glyph** [jaraco/keyring#272]
Lastpass has an open-source CLI that could be adapted to programmatic secret retrieval and storage: https://github.com/lastpass/lastpass-cli

**Comment by jaraco** [comment]
This sounds useful and likely broadly so, so might be a good candidate for inclusion in the core lib. Still, it is probably worthwhile to first build it as an extension, a separate library. How about first proving the functionality in a third party lib, perhaps keyrings.lastpass, modeled after keyrings.alt?

**Comment by glyph** [comment]
@jaraco - Sure. What are the steps involved in doing that?

**Comment by jaraco** [comment]
Hi Glyph. I just published some guidance in the README of this package in an attempt to help people like you get started. The short of it is to create a new package in the keyrings namespace, modeling after the keyrings.alt package. Probably start with a new github repo and copy the files from keyrings.alt, tweak them to instead implement keyrings.lastpass, and publish that package. Maybe start by creating the repo in github. If you get stuck, don't hesitate to ask for help here.

**Comment by glyph** [comment]
Thanks. My own plate is kind of full, but I'll point others to this and hopefully someone will find it interesting :).

**Comment by jaraco** [comment]
Happy anniversary. I'm going to close this ticket now, but leave it tagged for possible revival.
