### ISSUE TITLE
Security vulnerability due to attempts to load OS X dlls on Windows

### ISSUE THREAD

**Issue by potrebic** [jaraco/keyring#274]
On Windows this code
```
def _load_backends():
    "ensure that native keyring backends are loaded"
    backends = 'kwallet', 'OS_X', 'SecretService', 'Windows'
    list(map(_load_backend, backends))
    _load_plugins()
```
Will load OS_X, which in turns imports _OX_X_API.py, which attempts to open 

`C:\system\library\frameworks\security.framework\versions\a\security.dll`
and
`C:\system\library\frameworks\coreservices.framework\versions\a\coreservices.dll`

That's a security vulnerability (binary planting) as a any local user on that machine can create the above paths, placing a nefarious dll in that location which will then run as the target user.

**Comment by jaraco** [comment]
I'm not sure how practical the vulnerability is, but it sure does come off as sloppy. Can you propose a fix?

**Comment by jmknoble** [comment]
Seems like fixes might involve something like one of the following approaches:

1. Ensure that the OS_X backend only loads (or is only selected for loading) when the current OS is in fact OS X.

2. Set different priorities for backend loading based on OS, for example:
    - Windows:  Windows
    - Cygwin-ish:  kwallet, SecretService, Windows
    - OS X:  OS_X
    - Else:  kwallet, SecretService

**Comment by jaraco** [comment]
The keyring framework already has priorities for the backends and it determines the priorities of these backends in part by detecting the platform. The problem is, you can't know that the OS_X module is not needed until you import it and inquire about its viability... unless you write an external routine to filter these backends, which would supersede the existing mechanism for prioritizing backends, at which point you have code in at least two places and using different techniques to achieve the same thing. I don't think we want to go that route.

**Comment by jaraco** [comment]
Moreover, I'm not sure this exists as a vulnerability at all. The nefarious user would not only need to plant the two DLLs at the appropriate location (requiring write access to the root of the drive), but they would also need to supply the functions supplied by the OS X versions of those libraries (to avoid AttributeErrors in the _OS_X_API module). And even then, they would only be loading those libraries into the process. They wouldn't be calling into that library without invoking the OS_X backend, which would be made unavailable in the `.priority` check of the backend.

Given this apparent impracticality of the proposed vulnerability and the redundancy of the only proposed workarounds, I'm inclined not to fix this issue. If you feel there are circumstances that I've not addressed, please do expand on the issue and make your case for why my analysis is inadequate.
