### ISSUE TITLE
doesn't automagically create ~/.local/share/python_keyring

### ISSUE THREAD

**Issue by yarikoptic** [jaraco/keyring#276]
first I saw  `Root directory does not exist: /root/.local/share/python_keyring [__init__.py:__init__:145]`  in our logs (yeah... was running as root, trust you so much! ;) )  and that was version 10.1 ... then I upgraded to 10.3.1 and now I do not see that error message (only the one  `Gkr-Message: couldn't connect to dbus session bus: Did not receive a reply...`) but keyring simply doesn't fall into default of using that keyring and just fails to provide any backend UNTIL I just mkdir that directory.  It might be intentional I guess but may be then there should be a warning that none backend was enabled because eg. this directory doesn't exist?

**Comment by jaraco** [comment]
Unfortunately, I'm unable to asses what's happening here. I don't see the message "Root directory does not exist" anywhere in the keyring code (even in 10.1), so I don't think it is producing the message. Furthermore, `__init__.py:__init__:145` doesn't seem to reference anything in keyring. There's no __init__.py file in keyring with 145 lines. Furthermore, I don't see anything that [changed](https://github.com/jaraco/keyring/blob/master/CHANGES.rst) between 10.1 and 10.3.1 that might be implicated in the behavior you describe.

> [Should there] be a warning that none backend was enabled because eg. this directory doesn't exist?

Not really. The plugin design of keyring means that the best backend is selected based on the conditions encountered in the environment (OS, libraries available, etc) and then that best backend is initialized. If backends were to log warnings, these warnings would appear on every startup for every user, even those who would never want that backend.

I suspect the `python_keyring` file behavior is happening in the [keyrings.alt](https://pypi.org/project/keyrings.alt) package which means that any errors you encounter are affected not only by the version of `keyring` but also of `keyrings.alt`, so any troubleshooting you do should consider the version of that library as installed.

I welcome you to do more digging and troubleshooting and present another proposal, but as presented, I don't think there's anything to be done here.
