### ISSUE TITLE
DBUS runtime error

### ISSUE THREAD

**Issue by enkore** [jaraco/keyring#279]
The Gnome thing is installed, but was not unlocked.

```
 File "/usr/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 50, in get_preferred_collection
    collection.unlock()
  File "/usr/lib/python3.6/site-packages/secretstorage/collection.py", line 63, in unlock
    return unlock_objects(self.bus, [self.collection_path], callback)
  File "/usr/lib/python3.6/site-packages/secretstorage/util.py", line 168, in unlock_objects
    return exec_prompt_glib(bus, prompt)[0]
  File "/usr/lib/python3.6/site-packages/secretstorage/util.py", line 134, in exec_prompt_glib
    exec_prompt(bus, prompt, callback)
  File "/usr/lib/python3.6/site-packages/secretstorage/util.py", line 122, in exec_prompt
    prompt_iface.connect_to_signal('Completed', new_callback)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 544, in connect_to_signal
    dbus_interface, **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/proxies.py", line 369, in connect_to_signal
    **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/bus.py", line 148, in add_signal_receiver
    path, **keywords)
  File "/usr/lib/python3.6/site-packages/dbus/connection.py", line 400, in add_signal_receiver
    self._require_main_loop()
RuntimeError: To make asynchronous calls, receive signals or export objects, D-Bus connections must be attached to a main loop by passing mainloop=... to the constructor or calling dbus.set_default_main_loop(...)
```

**Comment by mitya57** [comment]
Does your code use D-Bus in other places somehow?
The mainloop *is* registered in `dbus_init` — see https://github.com/mitya57/secretstorage/blob/master/secretstorage/__init__.py#L45.

Also, please tell us what application and OS you are using, and what are the versions of Keyring and SecretStorage.

**Comment by enkore** [comment]
This happens with the command-line utility included in the package:

```
$ keyring set foo username
Password for 'username' in 'foo': 
Traceback (most recent call last):
snip
RuntimeError: To make asynchronous calls, ...
```

Linux 4.10, Arch Linux, Python 3.6, python-dbus 1.2.4 and keyring 10.3.2, secretstorage is at 2.3.1.

Right after it crashes the GNOME Keyring window pops up, asking for a password (though I don't use GNOME, but KDE and KWallet).

**Comment by mitya57** [comment]
If you are using Plasma, then Keyring should prefer the KWallet backend. Can you please run a Python shell and check if the following code fails:
```python
>>> from keyring.backends.kwallet import DBusKeyring
>>> DBusKeyring.priority
```

As to your original issue, I am now able to reproduce it locally and will look deeper now.

**Comment by enkore** [comment]
```
Python 3.6.0 (default, Feb 28 2017, 11:27:27) 
[GCC 6.3.1 20170109] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from keyring.backends.kwallet import DBusKeyring
>>> DBusKeyring.priority()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: 'float' object is not callable
>>> DBusKeyring.priority
4.9
```

**Comment by mitya57** [comment]
Oh, indeed the parentheses were not needed, sorry. You have both backends available, but the Secret Storage one has higher priority. You can still force Keyring to use KWallet using a configuration file as [described in README](https://github.com/jaraco/keyring/blob/master/README.rst#customize-your-keyring-by-config-file).

**Comment by enkore** [comment]
Ah I understand, thanks. I had gnome-keyring installed (but not started), which seems to give it priority over KWallet (although that one is always running). Uninstalled gnome-keyring and python-keyring now correctly uses KWallet.

**Comment by mitya57** [comment]
Your original issue is now fixed in master. The fix is simple enough so I pushed it directly rather than creating a pull request for @jaraco.

**Comment by frispete** [comment]
...but the underlying issue is to prefer Secret Storage over KWallet in the first place, isn't it?

**Comment by enkore** [comment]
That's the users decision to make.
