### ISSUE TITLE
OSX: access item without warning option missing

### ISSUE THREAD

**Issue by hryamzik** [jaraco/keyring#282]
Security app on Mac OS has the following option:

`-A              Allow any application to access this item without warning (insecure, not recommended!)`

Looks like it's on for this library and can't be turned off. Is it possible to make this flag optional?

**Comment by jaraco** [comment]
Can you explain more? How did you determine that such a setting is on for this library? What is the Security app (I don't have an app called Security)?

Oh, I think you mean the `security` command:

```
$ security add-generic-password --help
Usage: add-generic-password [-a account] [-s service] [-w password] [options...] [-A|-T appPath] [keychain]
 ...
    -A  Allow any application to access this item without warning (insecure, not recommended!)
...
        Add a generic password item.
```

Your suspicion runs contrary to my understanding, which is that only the executable that created the credential can read it without a prompt. Even just using a virtualenv or updating Python will cause a new warning prompt for that credential.

Furthermore, the code that adds the password doesn't use the `security` command (though it did in past versions). [Here's the code where passwords are added](https://github.com/jaraco/keyring/blob/master/keyring/backends/_OS_X_API.py#L219-L242). As you can see, there's no option there for selecting a non-default behavior with respect to allowed applications.

Moreover, if I use keyring to create a password:

```
$ keyring set test-system test-user              
Password for 'test-user' in 'test-system': 
```

And I open the Keychain Access app to inspect that credential, it appears to me that the credential is created without "Allow all applications to access this item":

![image](https://user-images.githubusercontent.com/308610/27541878-9660b12a-5a53-11e7-844e-60d7e5cf5f21.png)

If you're seeing a different behavior and you're using the latest version of the library, then you probably have an environmental condition unique to your system that's forcing the Allow all applications option. Please try to demonstrate the issue on a clean build of macOS with the latest keyring, and if you still have the issue, do please report back here.

**Comment by hryamzik** [comment]
> Even just using a virtualenv or updating Python will cause a new warning prompt for that credential

How about running the same python but from different script? That looks like a security issue for me, I'd prefer to have an empty list of no-prompt apps. Not sure if that's possible at all.

**Comment by jaraco** [comment]
> How about running the same python but from different script?

I don't think it's possible, as the security framework sees `Python thisscript.py` and `Python thatscript.py` as the same application.

**Comment by hryamzik** [comment]
So is it possible to implement an option for an empty allow list?

**Comment by jaraco** [comment]
I think the default behavior is to allow the application that created a credential to access that credential. I don't know if the API allows exempting even the creating application from being whitelisted to access the credential. Take a look at keyring.backends.OS_X and keyring.backends._OS_X_API modules for the implementation... which under the hood use [SecKeychainAddGenericPassword](https://developer.apple.com/documentation/security/1398366-seckeychainaddgenericpassword?language=objc). If they provide a mechanism to control access scope, I'd be open to supporting a hook to expose that control.

**Comment by hryamzik** [comment]
That's wired but I don't see anything related in apple documentation while they do have this implemented in `security` tool. :-(
