### ISSUE TITLE
What should 'service' be?

### ISSUE THREAD

**Issue by marmistrz** [jaraco/keyring#285]
For testing, I created a dummy entry in the keyring.

```
import keyring
keyring.set_password('system', 'foo', 'bar')
```
Then the password can be retrieved using `keyring`:
```
keyring.get_password('system', 'foo')
```
but not with `secret-tool`
```
secret-tool lookup system foo
```
which yields nothing.

I thought that the `service` was the name of the new keyring, but no new keyring was created, just an entry was added to the login keyring with the following description: `Password for 'foo' on 'system'`.

What exactly should `service` be? It's treated as obvious in the docs and is absolutely not to me.

**Comment by mitya57** [comment]
It will show up in Seahorse only if the correct backend (Secret Service) is in use.

Can you please run this in Python shell and see what it prints?
```python
>>> from keyring.backends.SecretService import Keyring
>>> Keyring.viable
```

**Comment by mitya57** [comment]
Read your updated description, you say that an entry is created in the login keyring. This is the expected behavior. Where do the docs say that a new keyring should be created?

**Comment by marmistrz** [comment]
@mitya57, nowhere, they don't explain what service is either, so I have to guess.

**Comment by mitya57** [comment]
Service can be anything — website address, mail server address or any other string. The documentation probably needs to say that, but I have no idea how to formulate that.

**Comment by marmistrz** [comment]
So service means: *what is this password for*?

**Comment by mitya57** [comment]
Yes. As you see, it ends up in the same string as username.

**Comment by starekrow** [comment]
Perhaps where the docs state:

    >>> keyring.set_password("system", "username", "password")

...instead of `"system"` which looks like it might have a magical meaning, use `"namespace"` or `"context"`.

**Comment by jaraco** [comment]
Hi @starekrow: Most of the backend services have some concept of a 'system' or 'service' associated with a credential. LastPass has a 'site'. I think there are lots of ways we could name this, but at this point, I wouldn't want to rename it. I do see how it might make sense to add a blurb explaining how there's no formal definition of this field, but it represents an array of concepts such as site or namespace or context. If you'd like to submit that PR to the README, we'd be delighted to review. Thanks.
