### ISSUE TITLE
new test_requires 'collective.checkdocs' doesn't seem developed anymore

### ISSUE THREAD

**Issue by prometheanfire** [jaraco/keyring#293]
The last commit was 2015, the stated supported versions of python are only up to 3.4, the license is also imprecise (GPL doesn't tell me the version, bug made upstream).  Not sure if the code just doesn't need to be updated, but the lack of activity has me worried.

**Comment by jaraco** [comment]
Yes, that is a little concerning. I only a few months ago started using it. I forget who recommended it to me. I'm happy to adopt an alternative. I do find it helpful, though, to avoid publishing releases with RST errors.

**Comment by prometheanfire** [comment]
The actual amount of code seems low at least.

https://github.com/collective/collective.checkdocs/blob/master/collective/checkdocs/__init__.py

**Comment by jaraco** [comment]
In jaraco/skeleton@95af04d3fcf70a48, I adopted a new package [pytest-checkdocs](https://pypi.org/project/pytest-checkdocs) which performs the same check as a pytest plugin. keyring has since adopted that package, solving this issue.
