### ISSUE TITLE
Keyring errors should derive from a base class

### ISSUE THREAD

**Issue by briggySmalls** [jaraco/keyring#299]
Quoting the python [guidance on user-defined exceptions](https://docs.python.org/3.6/tutorial/errors.html#tut-userexceptions):
> When creating a module that can raise several distinct errors, a common practice is to create a base class for exceptions defined by that module, and subclass that to create specific exception classes for different error conditions

This is useful for programs that call a module/package to identify the source of runtime errors.
 
The keyring errors `InitError` `PasswordSetError` and `PasswordDeleteError` should derive from a base class `KeyringError`

**Comment by jaraco** [comment]
~~Sounds good to me - would you be willing to draft the PR?~~

Oh, I see it. now.

**Comment by briggySmalls** [comment]
Done!

**Comment by jaraco** [comment]
Released as 10.6.0

**Comment by jaraco** [comment]
Well, I made a mess of that - released from a branch. I'll be cleaning that up now.

**Comment by jaraco** [comment]
Okay. Now [10.6.0 released](https://travis-ci.org/jaraco/keyring/jobs/326140129).

**Comment by briggySmalls** [comment]
Thank you! 🤸‍♂️
