### ISSUE TITLE
Moving forward with SecretStorage and D-Bus bindings

### ISSUE THREAD

**Issue by mitya57** [jaraco/keyring#301]
Hi @jaraco,

One of the major issues with Keyring on Linux is the [dbus-python](https://pypi.python.org/pypi/dbus-python) dependency, which has the following problems:

- It is difficult to install from PyPI: there are no wheels, it needs the D-Bus headers installed locally and compiles itself during install.
- It is not actively developed, and the author [recommends](https://pypi.python.org/pypi/dbus-python#problems-and-alternatives) switching to another library.

Some time ago I created a port of SecretStorage to [Jeepney](https://gitlab.com/takluyver/jeepney), a modern pure-Python library by @takluyver. Please see mitya57/secretstorage#10 and the [wip/jeepney](https://github.com/mitya57/secretstorage/tree/wip/jeepney) branch. I want it to eventually become the new release of SecretStorage.

But Jeepney only supports Python 3.5+, while Keyring aims to support Python 2. So I wonder how we should resolve this issue. I see the following possibilities:

1. Release the branch as a separate project, like `secretstorage-ng`. Tweak `setup.py` to select `secretstorage-ng` for newer Pythons and `secretstorage` for older Pythons. The module name will not change, so `secretstorage` and `secretstorage-ng` will conflict with each other.
2. Release the branch as `secretstorage 3.0a1`. PyPI will not pull it automatically, but `setup.py` can select `secretstorage>=3.0a1` for newer Pythons.
3. Release the branch as `secretstorage 3.0`. Make `setup.py` select `secretstorage<3` for older Pythons. I think I prefer this option, but I may consider others too.
4. Try to fork Jeepney and add Python 2 / 3.4 support?

What do you think?

**Comment by mitya57** [comment]
Note that the KWallet backend uses `dbus-python` too, so we may need to eventually port it to Jeepney too.

**Comment by takluyver** [comment]
If you do a release of secretstorage that relies on jeepney, specify `python_requires=">=3.5"` in your setup.py ([setuptools docs](https://setuptools.readthedocs.io/en/latest/setuptools.html#new-and-changed-setup-keywords)). When a user runs `pip install` on an older version of Python, it will respect that restriction, skipping over the incompatible release to automatically install an older version of the package.

We have done this for IPython 6.x releases, for instance. When someone does `pip install ipython` on Python 2.7, they still get the latest 5.x version.

Pip 9 was the first release that implemented support for this - that's already over a year old. But it's still worth having a separate check of `sys.version_info` in setup.py, to catch people installing with older versions of pip, or with other tools.

**Comment by mitya57** [comment]
@takluyver Oh, thanks a lot! I was aware of `python_requires` option, but I did not know that `pip` can fall back to older versions (looks like even in O(1) time, without downloading useless tarballs).

Now I guess we should go with option 3 if @jaraco does not mind. I am not sure what to do with Debian packaging yet, it will probably remain on SecretStorage 2.x for some time.

**Comment by takluyver** [comment]
So far I haven't seen Debian deal with any packages that have gone from cross-compatible to requiring Python 3. They seem to have ignored IPython 6 so far, but it's not the first time that releases have gone unpackaged.

**Comment by jaraco** [comment]
Yes, I like Option 3 best.

Or a variant on option 4 where you write a backport of Jeepney such that the new version of secretstorage runs on all Pythons with Jeepney or the backport (as appropriate for the platform).

I'm also happy to drop support for Python 3.4 (and 2.7) in keyring.

**Comment by cassioiks** [comment]
+1 on this, needs to be solved ASAP. I'm not able to make it run on Ubuntu not RedHat because of the `dbus-python`

**Comment by mitya57** [comment]
@cassioiks You can already use the latest SecretStorage from master branch, it is stable enough. I will make a new release as soon as I have some time to do the remaining minor updates (mostly the documentation).

**Comment by cassioiks** [comment]
@mitya57 Thanks for the update and the very quick response. In reality, I'm having trouble not with SecretStorage, but with dbus: I can't get it working in Linux, I get a `Unable to autolaunch a dbus-daemon without a $DISPLAY for X11`  message, and I can't seem to get it working with the GNOME keyring. Any advice?

**Comment by mitya57** [comment]
@cassioiks: Are you using it on an X11 desktop, or on a headless system? If the latter, please read <https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems>.

**Comment by cassioiks** [comment]
@mitya57 I'm on a headless system, but I couldn't make it work using [https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems](url). It still says it can't launch dbus-daemon.

Maybe I'm missing something regarding this specific line? `Remember to run your application in the same D-Bus session as the daemon`

**Comment by mitya57** [comment]
Can you paste a log / screenshot of what you were trying to do?

**Comment by cassioiks** [comment]
@mitya57 In fact, I'm on rhel 7.4 and I don't have `dbus-launch` nor `dbus-run-session` available. Is there something specific I have to install?

**Comment by mitya57** [comment]
@cassioiks I know nothing about RHEL, but you need one of these tools to be able to use D-Bus (`dbus-run-session` is the recommended one).

If you don’t have D-Bus, you can use one of the file-based backends from https://github.com/jaraco/keyrings.alt.

**Comment by takluyver** [comment]
I'm pretty sure that DBus should be available for RHEL 7. On Fedora there's a package just called `dbus` - try installing that.

**Comment by cassioiks** [comment]
@takluyver It's already installed

> Package 1:dbus-1.6.12-17.el7.x86_64 already installed and latest version

And all the commands I have are:

> dbus-binding-tool     dbus-cleanup-sockets  dbus-daemon           dbus-monitor          dbus-send             dbus-uuidgen

**Comment by takluyver** [comment]
AIUI dbus-daemon is the thing that needs to be running, and dbus-launch and dbus-run-session are wrappers which start dbus and set up the correct environment for programs to run. I guess they must have been added in a newer version of DBus than the one you have.

In principle you should be able to start a daemon manually and set `$DBUS_SESSION_BUS_ADDRESS` to tell programs where it is. But I don't know the invocation you'd need to do that, or if there are other pieces involved.

**Comment by mitya57** [comment]
Today I have released SecretStorage 3.0.0, which is the first stable release using Jeepney. Please test it and report your feedback.

And I have just submitted #320 which should specify the correct dependency for those who install with older pip versions.

**Comment by takluyver** [comment]
Cool! I hope I told you this before, but SecretStorage is probably the first project of any size to depend on Jeepney, so there may well be some bugs to work out at first.

**Comment by mitya57** [comment]
> I hope I told you this before, but SecretStorage is probably the first project of any size to depend on Jeepney, so there may well be some bugs to work out at first.

I am using only the blocking integration. The tests are continuously run on Travis, and no bugs found so far. Thanks for Jeepney! :)
