### ISSUE TITLE
choose which .keyring file to write to?

### ISSUE THREAD

**Issue by NateV** [jaraco/keyring#306]
Is it possible to choose which .keyring file keyring will write to?

Thank you.

**Comment by jaraco** [comment]
I'm not sure what `.keyring` is. Perhaps that's from an old version of keyring or maybe it's a convention used by a non-standard keyring backend.

On certain platforms, you can affect the data root and config root. The code that handles that is in the [platform module](https://github.com/jaraco/keyring/blob/master/keyring/util/platform_.py), so refer to that for ways you might be able to customize the paths.

If you provide more information - which backend are you using, what OS are you on, what packages you have installed (`pip freeze` output), input and output of a session, and any other details about your environment that may be helpful, we may be able to provide more insight.

**Comment by NateV** [comment]
Thank you. I'm on Debian Stretch and using a pipenv virtual environment  with Python 3.5.3

The output of `pip freeze` is 

```
asn1crypto==0.24.0
attrs==17.4.0
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
cryptography==2.1.4
idna==2.6
jeepney==0.3.1
keyring==11.0.0
keyring-jeepney==0.2
lxml==4.1.1
numpy==1.14.1
pandas==0.22.0
pluggy==0.6.0
py==1.5.2
pycparser==2.18
pytest==3.4.1
python-dateutil==2.6.1
pytz==2018.3
requests==2.18.4
ruamel.yaml==0.15.35
SecretStorage==2.3.1
six==1.11.0
urllib3==1.22
```

In `~/.local/share/keyrings/`, there are files project.keyring and login.keyring and user.keystore. The project.keyring file was created when, from Seahorse, I created a new "Password Keyring". "Login" is the name of the other keyring folder Seahorse is showing. Login unlocks automatically, and the Project keyring has a password.

I'm having two problems related to my inability to specify which of these [something].keyring files to use.

1. Ideally, I don't want to use the Login keyring, but the Project keyring I set up just to store credentials for this one project. So I'd like to be able to choose to use that keyring instead of the Login keyring.
2. Somehow python-keyring no longer sees the Login keyring either, and recently stopped saving passwords it creates there and cannot read passwords from the Login keyring. So `keyring.set_password('test1','test2','test3')` no longer saves to the Login keyring. I don't know where it is saving - I assume its base64-encoding the password and just writing the text somewhere. 

So I'd like to be able to tell python-keyring, "Use the file xxx.keyring, or if you can't, just throw an error".

I'm currently using `keyring_jeepney.Keyring()` as a backend because I couldn't get dbus working otherwise. Is there something else I can do to set a backend to deal with this?

Thanks for your help!

**Comment by mitya57** [comment]
The files in `~/.local/share/keyrings` are created not by python-keyring, but by the server-side Secret Service implementation (e.g. GNOME Keyring daemon).

> I don't know where it is saving - I assume its base64-encoding the password and just writing the text somewhere.

This should not be the case with the `keyring_jeepney` backend (and with most other backends too). Can you show your Python code? Are you sure that the `keyring_jeepney` backend is really used?

Or maybe it gets saved into another `.keyring` file instead? Do you see the saved items in Seahorse?

**Comment by NateV** [comment]
Woah. Now I am reading from the Login keyring again. The only thing I noticed is that a file called `q` had been created in my project directory. I deleted that, and now the Login keyring is working, at least.

Is there any way to choose to use the other Project keyring I created, from python-keyring? (that way I can isolate the project credentials under their own keyring password). Or if that's a pointless idea, I'd be glad to hear that too.

**Comment by mitya57** [comment]
> Is there any way to choose to use the other Project keyring I created, from python-keyring?

Try passing `collection='/org/freedesktop/secrets/collection/project'` to `keyring_jeepney.Keyring` constructor.

**Comment by NateV** [comment]
Yes! Thank you. It won't prompt me for the password when its locked, so I'll need to have the collection unlock at login if I want scripts to use these things automatically, but that's not so terrible. At least having the credentials in a separate file helps me stay organized.

**Comment by mitya57** [comment]
> It won't prompt me for the password when its locked, so I'll need to have the collection unlock at login if I want scripts to use these things automatically

keyring_jeepney is a very basic code, it doesn't support unlocking.

Try the default SecretStorage backend — if you have problems with python-dbus, you can install SecretStorage from [Git](https://github.com/mitya57/secretstorage), the latest version in master also uses Jeepney. It *does* support unlocking.

Passing a custom keyring path with SecretStorage backend is a bit different: you first need to construct a `keyring.backends.SecretService.Keyring` instance, and then set its `preferred_collection` attribute to a collection path, like `'/org/freedesktop/secrets/collection/project'`.

**Comment by NateV** [comment]
Thanks. I'll give that a shot. This was super helpful.
