### ISSUE TITLE
D-Bus instructions need more detail in README

### ISSUE THREAD

**Issue by mgreiner** [jaraco/keyring#308]
I'm having trouble using keyring on a headless Linux system. The instructions in the _Using Keyring on headless Linux systems_ section aren't detailed enough for me. I consider myself a novice-to-intermediate Linux user and I can get most things running with the help of a search engine and a bit of trial and error, but I'm stuck here and I suspect many others will be too.

Here are the parts that are unclear to me:

> When that command is started, enter your password into stdin and press Ctrl+D (end of data). After that the daemon will fork into background (use --foreground option to prevent that).

OK, so I got this far. But why mention the `--foreground` option? When would I use that?

> Now you can use the SecretService backend of Keyring. Remember to run your application in the same D-Bus session as the daemon.

How do I run another application in the same D-Bus session? Can we add an example here?

The main problem is that I'm not familiar with D-Bus. I think that might be the case for many novice users. I'm not suggesting that a in-depth description of D-Bus be included in the README, but perhaps a link to further information on D-Bus could be provided.

Note: While this is admittedly a request for help disguised as an issue, I will happily submit a PR for the README if someone can point me in the right direction.

**Comment by cassioiks** [comment]
Hi @mgreiner, I have to say I faced the same confusion some days ago. But I managed to solve the riddle on this specific part:

> Now you can use the SecretService backend of Keyring. Remember to run your application in the same D-Bus session as the daemon.

It happens that when you run `dbus-run-session -- sh` you're starting dbus with a shell of its own, and that's where you need to run the application, and not in the usual /bin/bash or whatever shell you use.

**Comment by mitya57** [comment]
> But why mention the `--foreground` option? When would I use that?

This is a command-line option that many daemons have. You can use it if you want to e.g. kill the daemon later using Ctrl+C combination. If you don’t know why when you would use it, then you probably should not use it.

> How do I run another application in the same D-Bus session? Can we add an example here?

This means: do not exit from `dbus-run-session` shell, stay in there. If the current wording is not clear, maybe you can suggest an improvement?

> I'm not suggesting that a in-depth description of D-Bus be included in the README, but perhaps a link to further information on D-Bus could be provided.

I don’t think that Keyring users need to know many things about D-Bus. They just need to know that it is an inter-process communication protocol.

In any case, here are some links for further reading:

- https://dbus.freedesktop.org/doc/dbus-tutorial.html#whatis
- https://www.freedesktop.org/wiki/IntroductionToDBus/

> Note: While this is admittedly a request for help disguised as an issue, I will happily submit a PR for the README if someone can point me in the right direction.

Pull requests are always welcome!

**Comment by jaraco** [comment]
As this is languishing, I'll close it as addressed, but feel free to submit a PR to incorporate any of these clarifications into the documentation in a way that would have made your introduction easier.
