### ISSUE TITLE
Keyring should load all backends through entry points

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#310]
Currently, keyring loads backends through two mechanisms. First, it loads the four built-in backends explicitly. Then, it loads backends declared as entry points. A simpler, more congruent approach would be for keyring to declare its own backends as entry points and load all backends as entry points.

The main downside to this approach is keyring would no longer work on platforms that don't support entry points... so for a narrow population, that would break compatibility. I'm not sure what that population is or if it exists at all.

Perhaps it would be possible to detect that condition and raise a warning (but retain compatibility) to assess the impact.

**Comment by jaraco** [comment]
I'd release this commit above right away, except I have one major reservation:

The commit adds a dependency, and not a lightweight one.

**Comment by dsully** [comment]
Hey Jason - I was about to put together a pull request that relies on: 

https://pypi.python.org/pypi/entrypoints

Instead of pkg_resources, for all the same reasons that we have discussed before.

What do you think of that approach?

**Comment by jaraco** [comment]
I like it. Let's do that.

**Comment by jaraco** [comment]
This behavior was released in v12.
