### ISSUE TITLE
How can we improve the experience on Linux?

### ISSUE THREAD

**Issue by theacodes** [jaraco/keyring#311]
Presently there are a few large user experience issues with Keyring on Linux:

1. The dependency on python-dbus is tricky. It seems like moving to Jeepney is already being considered: https://github.com/jaraco/keyring/issues/301
2. Working with headless installations is [difficult](https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems). Would it be possible for us to consider starting the dbus daemon automatically if needed?

**Comment by trp07** [comment]
I've been using **dbus-python** on Linux and you can pip-install it just fine.  It works without issue with keyring and SecretStorage.  I've been using linux mint, which is a debian/ubuntu based distro.

My recommendation is adding **dbus-python** as a linux-specific install dependency.

**Comment by mitya57** [comment]
D-Bus can be activated automatically. But you will have difficulties entering your master password for gnome-keyring if you are on a headless system. There is nothing we can do here to help you.

With regards to python-dbus, I will do a new SecretStorage release (using Jeepney) as soon as I have time for it.
