### ISSUE TITLE
race condition in delete_password (Windows backend)

### ISSUE THREAD

**Issue by kingsawyer** [jaraco/keyring#323]
I can get an uncaught exception calling delete_password from multiple threads or processes. It looks like this (older version but still present in 12.2)

```
uncaught exception:
  File "..\site-packages\keyring\core.py", line 54, in delete_password
    _keyring_backend.delete_password(service_name, username)
  File "..\site-packages\keyring\backends\Windows.py", line 115, in delete_password
    self._delete_password(target)
  File "..\site-packages\keyring\backends\Windows.py", line 122, in _delete_password
    TargetName=target,
  File "..\site-packages\win32ctypes\win32cred.py", line 128, in CredDelete
    _win32cred._CredDelete(TargetName, Type, 0)
  File "..\site-packages\win32ctypes\_util.py", line 52, in check_zero
    raise error(code, func_name, description)
error: (1168, 'CredDelete', 'Element not found.')
```

I'd be fine if delete_password caught the element not found error and returned success. Would also be fine to turn this into a PasswordDeleteError. Another option is to add a lock to make it thread safe, but you'd still get this in multiple processes.

**Comment by jaraco** [comment]
I've pushed a new proposed fix (untested). Assuming it passes the CI tests, would you try it out in your environment? `pip install git+https://github.com/jaraco/keyring@bugfix/issue323`

**Comment by jaraco** [comment]
Well dang, the tests didn't pass. And they failed on deleting passwords (but just once on perhaps the most complex passwords), so maybe this change is revealing another defect.
