### ISSUE TITLE
Kwallet: Give meaningful error if the keyring has not been unlocked

### ISSUE THREAD

**Issue by lovetox** [jaraco/keyring#327]
Hi,

When i start the application, Kwallet prompts for the password, if i dont enter the password, `get_password()` returns after 20 seconds with `None` without any error.

Per docs this means there is no password stored in the keyring, which is wrong in this case. I need to know if the user didnt unlock his keyring, because then i can try again. Trying again makes no sense if there is no password in the keyring.

**Comment by mitya57** [comment]
FWIW, the SecretService backend [raises `InitError`][1] when user dismisses the unlock prompt. Maybe this behavior should be consistent across the backends.

[1]: https://github.com/jaraco/keyring/blob/master/keyring/backends/SecretService.py#L60

**Comment by lovetox** [comment]
i just tested this with the secretservice backend, and yes this raises an error, which we can correctly handle.

also do you know why the Kwallet backend returns after 20 seconds and the secretservice backend returns not, if nothing is entered? or at least not after 40 seconds, didnt wait longer

**Comment by mitya57** [comment]
> also do you know why the Kwallet backend returns after 20 seconds and the secretservice backend returns not, if nothing is entered?

This is probably the difference between gnome-keyring and KWallet, not something in Keyring code.

**Comment by lovetox** [comment]
Im not sure, because Kwallet doesnt end the password prompt, its still there.

It would not make much sense to me if Kwallet returns None to the application but still asking the user to unlock the keyring.

**Comment by lovetox** [comment]
also this code seems not be ideal

kwallet backend
```
def get_password(self, service, username):
        """Get password of the username for the service
        """
        if not self.connected(service):
            # the user pressed "cancel" when prompted to unlock their keyring.
            return None
        if not self.iface.hasEntry(self.handle, service, username, self.appid):
            return None
```

**Comment by lovetox** [comment]
It seems the KDE Backend needs an overhaul

- should this be also ported to Jeepney?
- should the dbus wrapper also be in an own package like with secretstorage?
- Is there anywhere a KDE Waller dbus api documentation, i only found https://api.kde.org/frameworks/kwallet/html/classKWallet_1_1Wallet.html
im not sure if all that is available via dbus

**Comment by mitya57** [comment]
I can help with porting the KWallet backend to Jeepney, but that would mean dropping Python 2 support. Moving it to a separate project can help here, but the code base is small so I am not sure it’s worth it.

I wonder what @jaraco thinks about it.

**Comment by lovetox** [comment]
If we want to keep python2 compat, we could just add a new kwallet backend that is only used if python3 is used and which uses jeepney

**Comment by frispete** [comment]
We could raise InitError:
```
    def get_password(self, service, username):
        """Get password of the username for the service
        """
        if not self.connected(service):
            # the user pressed "cancel" when prompted to unlock their keyring.
            raise InitError("Cancelled by user")
        if not self.iface.hasEntry(self.handle, service, username, self.appid):
            return None
        password = self.iface.readPassword(
            self.handle, service, username, self.appid)
        return str(password)
```
similar to the SecretService backend.

Funnily, I stumbled across a similar issue with this backend today, and this change would solve it...

Unfortunately, I cannot test and prepare a MR before in a couple of hours.
Here's my commit: https://github.com/frispete/keyring/commit/1bc7402af193aeb9d344f96cf1d789add44df9ca

@lovetox It would be nice, if you could give it a try.

**Comment by lovetox** [comment]
yes short term i would solve it in a way like this, still this needs more investigation, as connected returns none on any exception, so printing "Cancelled by user" is probably wrong in many cases and misleading.

i will look into it.

**Comment by jaraco** [comment]
I'm not sure when I'll have time to review this in earnest. I do think keyring will need to retain Python 2 support for some time - at least maintenance releases. But a solution that presents the improved behavior on Python 3 and the degraded behavior on Python 2 could be acceptable.
