### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by kimyen** [jaraco/keyring#342]
Hello, I am working in a strict environment where Python is loaded as dynamic library. No Python executable is installed. When I try to install `keyring` I get this error:
```
Searching for secretstorage

Reading https://pypi.python.org/simple/secretstorage/

Downloading https://files.pythonhosted.org/packages/17/7a/683ce8d41b0b392199f1f6273a5cc81a0583b886e799786b7add5750817f/SecretStorage-3.1.0.tar.gz#sha256=29aa3cbd36dd5e54ac17d69161f9a150548f4ffba21fa8b5fdd5add854fe7d8b

Best match: SecretStorage 3.1.0

Processing SecretStorage-3.1.0.tar.gz

Writing /tmp/easy_install-i7d8j355/SecretStorage-3.1.0/setup.cfg

Running SecretStorage-3.1.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-i7d8j355/SecretStorage-3.1.0/egg-dist-tmp-28h5r1lo

warning: install_lib: 'build/lib' does not exist -- no Python modules to install


zip_safe flag not set; analyzing archive contents...

Moving UNKNOWN-0.0.0-py3.5.egg to /tmp/Rtmp5tZrZ8/R.INSTALL53bc1b370d96/synapser/inst/lib/python3.5/site-packages

Adding UNKNOWN 0.0.0 to easy-install.pth file


Installed /tmp/Rtmp5tZrZ8/R.INSTALL53bc1b370d96/synapser/inst/lib/python3.5/site-packages/UNKNOWN-0.0.0-py3.5.egg

error: The 'secretstorage' distribution was not found and is required by keyring
```
I think the problem is related to running `setup.py`. Would this be why I get the error above? Would it be possible to install `keyring` without running `SecretStorage-3.1.0/setup.py`?

**Comment by mitya57** [comment]
What is your Python version?

**Comment by kimyen** [comment]
I am using Python version 3.5. My current work around is to pin `keyring` to version 12.0.2 so that I can use `SecretStorage 2.x` which doesn't run `setup.py`.

**Comment by mitya57** [comment]
I understand now. In SecretStorage 3.1.0 I switched to declarative setup configuration, which requires setuptools 30.3 or newer. Please upgrade your setuptools and try again.

Also there is a wheel — you can install wheel and then you won't need to care about setup.py or setuptools.

**Comment by jaraco** [comment]
@mitya57 Does SecretStorage provide a pyproject.toml with that build requirement? If not, adding one will go a long way to helping users with pip 10 or later. Then he recommendation can be to upgrade pip and not worry to much about setuptools versions.

**Comment by mitya57** [comment]
I will add it.
