### ISSUE TITLE
request to improve man page with practical examples

### ISSUE THREAD

**Issue by SmartLayer** [jaraco/keyring#343]
I'm a bit confused as what are the SERVICE and USERNAME parameter of keyring(1) utility. I'm using gnome-keyring so there are a few possibilities:

1. service is gnome-keyring

2. typically, there are two keyrings, `login` which is unlocked by login, and `user`. `SERVICE` could mean the name of the keyring.

The first is semantically correct but then there seem to be missing a parameter for keyring name before `USERNAME`.

The second is semantically incorrect but makes more sense if you consider the hierarchy: `USERNAME` to be an object under `SERVICES` and items in gnome-keyring is under keyrings.

In practice, setting username under an imagined service called `test` causes an entry to be created in the 'login' keyring, which is very confusing (because nowhere in the commandline mentions the 'login' keyring):

    $ keyring set test username --keyring-backend=keyring.backends.SecretService.Keyring

Since keyring(1) is a userland utility it should make sense for the users.

After a look at the way keyring works I figured out the right explanation:

       keyring provides a way to store, lookup and delete passwords in various
       backends supported by Python-Keyring.

       Usage example:

       # create an entry in the current keyring
       $ keyring set system joe
       Password for 'joe' in 'system':
       # the newly created item looks like this:
       # {"service": "system", "username": 'joe', "password": "[the new password]"}

**Comment by mitya57** [comment]
If you refer to the manpage shipped by Debian then this is the wrong place to file a bug, that manpage is not provided by upstream.

Anyway I wrote it so I will fix it when I have time.

**Comment by mitya57** [comment]
After reading your description more carefully:

Both service and username are stored/interpreted as “lookup attributes” in Secret Service terms. Python-Keyring does **not** allow you to choose collection (“keyring” in your terms), the default or “login” collection is always used, also it does **not** allow you to choose the label, it is auto-generated.

If you need advanced control on collection or label, I suggest you to use the underlying [SecretStorage](https://secretstorage.readthedocs.io/en/latest/) module directly, which provides you with the ability to do all of this. Obviously it won't be cross-platform anymore.

**Comment by mitya57** [comment]
Updated the manpage in https://salsa.debian.org/python-team/modules/python-keyring/commit/b2ee1c8df3d23dfe5dab9b8e7fe7325a84cb1aed.
