### ISSUE TITLE
pip install failure on windows 10, python 3.7 64 bit

### ISSUE THREAD

**Issue by davidsorkin** [jaraco/keyring#344]
C:\>pip install --no-index C:\temp\keyring-15.1.0-py2.py3-none-any.whl
Processing c:\temp\keyring-15.1.0-py2.py3-none-any.whl
Collecting entrypoints (from keyring==15.1.0)
  Could not find a version that satisfies the requirement entrypoints (from keyring==15.1.0) (from versions: )
No matching distribution found for entrypoints (from keyring==15.1.0)

C:\>pip install --no-index C:\temp\keyring-15.1.0.tar.gz
Processing c:\temp\keyring-15.1.0.tar.gz
  Could not find a version that satisfies the requirement setuptools>=30.3 (from versions: )
No matching distribution found for setuptools>=30.3

C:\>python
Python 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import setuptools
>>> print (setuptools.__version__)
40.4.1
>>>

Any tips? Thanks

**Comment by jaraco** [comment]
You can't `pip install --no-index` a package than needs to pull dependencies from the index. Why are you passing no-index?

**Comment by jaraco** [comment]
Assuming you're behind a firewall, you probably need to download the suite of dependencies you need.

**Comment by jaraco** [comment]
On a machine where you do have a network (and using the same windows/python versions), `pip download keyring`, then copy those wheels to your airgapped/firewalled machine, then `pip install *.whl`.

**Comment by davidsorkin** [comment]
I got it to install, thanks! I was confused because of the dependency error
for setuptools when installing from source because setuptools was indeed
already installed. After I installed 'entrypoints' the whl file install
worked and I did not try the .tar.gz file again.

Thanks and regards,
