### ISSUE TITLE
Add field to set label

### ISSUE THREAD

**Issue by alexandrevicenzi** [jaraco/keyring#347]
Currently, all entries are saved with `Password for '%s' on '%s'` label.

It would be nice to be able to set a custom description.

[Source](https://github.com/jaraco/keyring/blob/master/keyring/backends/SecretService.py#L86)

**Comment by mitya57** [comment]
I think SecretService is the only backend that has a concept of labels. As Keyring supports multiple backends, it does not make much sense to provide API that will be only supported by one of them.

If you want to use SecretService, and to have control over labels, you can use the underlying [SecretStorage](https://secretstorage.readthedocs.io/en/latest/) API directly.
