### ISSUE TITLE
Allow all backends to participate

### ISSUE THREAD

**Issue by zooba** [jaraco/keyring#352]
Currently, only the highest priority backend (for the special definition of "priority") is used for getting and setting credentials.

I propose the default behavior (that is, before `set_keyring` is called) to allow all discovered backends to participate. My proposed semantics:

## init_backend
Instead of using `max` to select the best keyring in the unconfigured case, use a new backend that includes all those found/filtered by the call (`keyrings` local variable).

## get_password and get_credential
When getting a password, forward the call to each backend in order and return the first non-None result.

## set_password and delete_password
When setting a password, forward the call to each backend in order and return after the first that _does not_ raise `NotImplementedError`.

**Comment by zooba** [comment]
Open question: how to deal with exceptions when getting passwords?

I think we should just let the first (unexpected) exception bubble out.

**Comment by zooba** [comment]
Also, what error to raise if there are no suitable backends for setting a password?

**Comment by jaraco** [comment]
@zooba I know we discussed this in person, but I've since forgotten. Can you describe for me again the use-case that drove your desire for this new behavior?

**Comment by zooba** [comment]
@jaraco Providing backends that handle certain systems but delegate others. Specifically 3rd-party backends, rather than those that are included in keyring itself - I would really dislike for my handler to prevent someone's cached credentials from working simply because I had an entry_point.
