### ISSUE TITLE
Mutable return value

### ISSUE THREAD

**Issue by earonesty** [jaraco/keyring#356]
It would be cool if, optionally, the return value of a keyring function was a mutable bytestring, allowing the caller to zero it out after use.

Python is a very bad language for crypto in general because of the pervasive use of immutable types, but this lib could at least *try* to give the user an opportunity to clean up.

**Comment by jaraco** [comment]
Can you give an example of a mutable string in Python that meets the security profile you're imagining?

**Comment by jaraco** [comment]
Also, keyring doesn't present or solicit bytestrings, but instead works in text (Unicode)... so any example would need to honor that interface.

**Comment by jaraco** [comment]
[This answer suggests it's not possible](https://stackoverflow.com/a/728237/70170).

**Comment by jaraco** [comment]
I'm going to close this as wontfix, as I don't believe there's a suitable solution, but I'm open to suggestions and will happily re-open this request if there's a demonstration of a technique that could work.
