### ISSUE TITLE
import keyring.util.escape import error

### ISSUE THREAD

**Issue by bavanz** [jaraco/keyring#363]
Im using Ububtu18.04.01LTS. i have successfully installed Spyder3 in my os. when i run spyder3 import keyring.util.escape module missing is appearing in the terminal. Can i have a solution for this? Thanks in advance.

**Comment by mitya57** [comment]
The `keyring.util.escape` module has been removed in version 15.0.0 as documented in CHANGES.rst:

https://github.com/jaraco/keyring/blob/master/CHANGES.rst#1500

Please update `keyrings.alt` to the latest version if you have it installed, and fix your code if it is using that module.
