### ISSUE TITLE
recommended function in core should only return true for secure keyrings

### ISSUE THREAD

**Issue by atbagga** [jaraco/keyring#365]
I am trying to use keyring in my commandline tool to store auth tokens. I do not want to allow fallback to insecure backends like alt or any third party ones.

I was assuming the recommended function should fix the issue for me. But seems like various backends do not follow the priority paradigm.
`keyring.core.recommended(keyring.get_keyring())`

Google keyring has a priority of 3
https://github.com/jaraco/keyrings.alt/blob/master/keyrings/alt/Google.py 

Gnome Keyring which is in alt has a priority of 1
https://github.com/jaraco/keyrings.alt/blob/master/keyrings/alt/Gnome.py

So they will both turn out to be recommended. 

What is the ideal solution to block the backends other than the ones in keyring module?

**Comment by atbagga** [comment]
I can depend on the name but that didn't seem like a first class solution. Is that the only way?

`if (str(keyring.get_keyring()).startswith("keyring.backends")):`

**Comment by jaraco** [comment]
What's causing keyrings.alt to be installed? My first recommendation would be to prevent it from being installed at all.

**Comment by atbagga** [comment]
@jaraco  What packages are installed on the machine is not in my control. If I remove dependency from alt, It could be installed on the machine due to some other packages the user is consuming. 

The issue is my cli without taking explicit dependency on keyrings.alt end up using it to store the tokens which might end up as being stored on plain text file.

**Comment by jaraco** [comment]
The intention of keyring is to provide a deterministic experience for an environment and allow users/deployers to configure those environments to have suitable characteristics. It shouldn't be the responsibility of the application using keyring to dictate what keyrings to exclude. At least, that's the intention.

If you wanted to prevent other keyrings from being installed, you _could_ raise an exception if any keyring plugins are installed other than those in keyring itself (informing the user not to install that package).

Are there environments you wish to support that have a legitimate reason to have keyrings.alt installed for other purposes but where they should be ignored for your application? The purpose for creating keyrings.alt was to discourage its use.

Another option you have, if you want to get explicit about it, is you could in your application invoke `keyring.core.init_backend()` with a limit function... something like

```
def only_builtin(backend):
    return backend.__module__.startswith('keyring.backends.')

keyring.core.init_backend(only_builtin)
```

This technique would work fine except in light of the new `chainer` backend (keyring 16), which allows all backends to participate... so you would want to exclude it too:

```
def only_builtin(backend):
    return (
        backend.__module__.startswith('keyring.backends.')
        and not 'chain' in backend.__module__
    )

keyring.core.init_backend(only_builtin)
```

Does that work for you?

**Comment by atbagga** [comment]
Thanks! The last part of restricting explicitly should work for me. 

> If you wanted to prevent other keyrings from being installed, you could raise an exception if any keyring plugins are installed other than those in keyring itself (informing the user not to install that package).

This would be nice but intrusive experience, asking users to uninstall alt backends. 

Ideally I expected a simpler way to restrict alternate backends, since they are known to have a security risk. 
e.g. `keyring.core.recommended(keyring.get_keyring())` and recommended function handles the restriction logic. So keyring consumer doesn't have to understand the restriction logic.

Just for my info.. Wasn't that the original goal for adding a recommended api?

**Comment by jaraco** [comment]
`recommended` is intended to be used as a limit on `init_backend`. The technique for using `recommend` is thus:

```
keyring.core.init_backend(keyring.core.recommended)
```

That would have a similar effect to what you're seeking to achieve, except as you noticed, it will still include backends that you consider undesirable... and it also is subject to the chainer bypassing the preference. I think I maybe should open another issue about that behavior.

**Comment by jaraco** [comment]
@atbagga When #367 lands, you won't need to have `and not 'chain' in backend.__module__` in `only_builtin`.
