### ISSUE TITLE
The latest PyPI deploy didn’t work

### ISSUE THREAD

**Issue by mitya57** [jaraco/keyring#368]
https://travis-ci.org/jaraco/keyring/jobs/464563561 has:
```
/opt/python/3.7.1/lib/python3.7/distutils/dist.py:274: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
...
Uploading distributions to https://upload.pypi.org/legacy/
Uploading keyring-0.0.0-py2.py3-none-any.whl
100%|██████████████████████████████████████| 53.0k/53.0k [00:01<00:00, 28.3kB/s]
Uploading keyring-0.0.0.tar.gz
100%|██████████████████████████████████████| 47.1k/47.1k [00:01<00:00, 29.3kB/s]
```

which doesn’t look right to me.

And the latest release on PyPI is 17.0.0, not 17.1.0.

**Comment by mitya57** [comment]
This may be an effect of 2c91e8ec0d99f9ca354b7f913d61720925bb98bc.

**Comment by jaraco** [comment]
Hmm. I encountered this issue in another project. I thought I'd solved it. Thanks for reporting this. I'll investigate and rectify the situation.

**Comment by jaraco** [comment]
You're right, and I rolled back the changes in 216c433.

**Comment by jaraco** [comment]
I've manually cut the release of 17.1.0, but I'm going to cut another release to avoid incompatibility issues installing the sdist on older pips.

**Comment by mitya57** [comment]
Thanks for fixing it!

**Comment by jaraco** [comment]
I've deleted the 0.0.0 release. And the [17.1.1 release seems to have worked properly](https://travis-ci.org/jaraco/keyring/jobs/471680847).
