### ISSUE TITLE
On Mac, is it possible to use any keychain-db other than login/default?

### ISSUE THREAD

**Issue by RichardBronosky** [jaraco/keyring#369]
Because of corporate IT, my login keychain is not secure. (It can be accessed by people (corp IT) other than me.) I have move my "service" entry to a keychain file that is exclusive to me, but I can't figure out how to get keyring to use it. If I tell "Keychain Access" to make it the default, it will use it, but, I'd rather not leave it like that.

Please advise.

**Comment by jaraco** [comment]
I don’t believe it’s readily possible today. I believe there’s even an open request to support other common keychains like Internet passwords and not just Generic credentials.

I’d certainly entertain an enhancement to support this need. Perhaps you would be interested in digging deeper into the implementation to devise and demonstrate what changes would be needed to support this feature?

**Comment by RichardBronosky** [comment]
For what it is worth, https://github.com/99designs/aws-vault manages to use a dedicated keychain on macOS rather than the default. I don't know if there is some magic that being a signed binary an advantage to a golang app over a python app.

**Comment by ev0rtex** [comment]
While it's not exposed or abstracted to a usable cross-platform concept you technically _can_ get it to use a different macOS keychain if you use it via the python API (see the [keyring/backends/OS_X.py](https://github.com/jaraco/keyring/blob/7915afdaae9dc664a2ba1ffd91abe64efecc0d46/keyring/backends/OS_X.py#L17) file)...but it's a total hack that involves modifying the class `keychain` value:
```py
import sys
import keyring
from pathlib import Path

if __name__ == '__main__':
    kr = keyring.get_keyring()
    kr.keychain = str(Path.home() / 'Library' / 'Keychains' / (sys.argv[1] + '.keychain-db'))
    print(kr.get_password('service', 'username'))
```

**Comment by jaraco** [comment]
That approach, although hacky, seems suitable for a one-off approach. I'd be open to supporting an environment variable or some other means of soliciting alternate keychains. The real challenge lies in how the interface is common across platforms, so platform-specific inputs aren't available through the interface. Each keyring backend implementation needs to solicit its configuration from the environment. Regardless, I welcome suggestions and contributions.
