### ISSUE TITLE
Nuclear codes stored using insecure "keyring" by default

### ISSUE THREAD

**Issue by cowlinator** [jaraco/keyring#370]
Keyring stores secrets in a completely non-secure way by default, with no warning nor notification.

Steps to reproduce:
1) Install Alpine Linux.  (It's easiest to do this by installing Docker  https://www.docker.com/products/docker-desktop and then running `docker run -it alpine:3.8`)
2) `apk add --update --no-cache musl-dev=1.1.19-r10 python2-dev=2.7.15-r1 py2-pip=10.0.1-r0 gcc=6.4.0-r9 libffi-dev=3.2.1-r4 openssl-dev=1.0.2q-r0 libxml2-dev=2.9.8-r1 libxslt-dev=1.1.32-r0`
3) `pip install --upgrade pip==18.1`
4) `pip install keyring==17.1.1 keyrings.alt==3.1.1`
5) `keyring set nuke_codes dTrump`
6) `python -c "import keyring; print(keyring.get_keyring())"`

Expected result:
Some kind of secure keyring is used. Or, at the very least, `keyring.backends.fail.Keyring (priority: 0)` is used.

Actual result:
`keyrings.alt.file.PlaintextKeyring (priority: 0.5)`

I never explicitly chose the Plaintext keyring, nor was there any warning nor notification that an insecure keyring was being used.  It was only on a whim that I decided to check which keyring was being used, and boy was I ever glad I did.  

Honestly, the Plaintext keyring should have a negative priority by default.  

You don't want to contribute to the apocalypse, do you?

**Comment by jaraco** [comment]
Thanks for the report and the contribution.

Part of the problem is that `utterly insecure` is subjective and makes assumptions about the user's use-case and intentions. Consider, for example, a trusted platform, where the files on the file system are as secure as any other part of the system. In that case, the plain text keyring might be appropriate and perfectly secure. Or consider another case where the data being saved isn't nuclear codes, but merely a secret on an unattended server that would need to be stored in plain text anyway.

The whole point of creating keyrings.alt was to discourage its casual, incidental use, and I believe by making it an optional and discouraged package, it achieves that goal. In fact, the readme states:

> Keyrings in this package may have security risks or other implications. These backends were extracted from the main keyring project to make them available for those who wish to employ them, but are discouraged for general production use. Include this module and use its backends at your own risk.

I believe in the example, the error exists at `pip install keyrings.alt`. Why would you install `keyrings.alt` at all if you're concerned about security?

**Comment by cowlinator** [comment]
@jaraco , I understand what you are saying.  You are right, to a degree.
But, the other problem is that `discouraged` is also subjective, and `security risks or other implications` is ambiguous.  

I can't think of anything less secure than storing a secret in plain text, can you?  Storing a secret in plain text makes Keyring nothing more than a fancy File-IO wrapper.  That's not exactly the idea I got when I read `discouraged` and `security risks or other implications`.  My takeaway from this is that I should be more pessimistic when imagining the implications of vague documentation.

So, forget everything I said about preferring fail.Keyring or PlainText having negative priority.

However, I think it's important for you to think about how a user, even after reading the readme, can still be unaware that their secret is being stored in plain text, the least secure form possible.  All I'm really asking for is explicit documentation about this, or a warning or notification of some kind to pop up when the user ends up using the PlainText keyring.

**Comment by jaraco** [comment]
> I can't think of anything less secure than storing a secret in plain text, can you?

Without too much contortion, I could imagine using a paste server would be less secure. And it illustrates the inherent security of a file an a (private) file system over more accessible approaches.

> nothing more than a fancy File-IO wrapper

It's also an API on which an application can depend to retrieve credentials. It may be that security isn't the goal, but consistency/compatibility.

>  All I'm really asking for is explicit documentation about this, or a warning or notification of some kind to pop up when the user ends up using the PlainText keyring.

There may be other keyrings that are insecure too. If you'd like to send a pull request to the keyrings.alt project to enhance the documentation, I'd have no problem with that. If you want to raise a warning, that's perhaps more impactful, but probably acceptable.

Appreciate the feedback and concern.
