### ISSUE TITLE
Item.get_secret raises exception on empty password  

### ISSUE THREAD

**Issue by fondamenti-dev** [jaraco/keyring#378]
I'm on Fedora 28, with Anaconda.com python distribution and python 3.7.
When an empty password is stored in the keyring (e.g. for the postgres default installation), the get command raises an exception (see below) because secret[2] contains a list instead than a byte
I have solved by adding the following two lines to the Item.get_secret method in file secretstorage/item.py

`                if type(secret[2]) == list:
                        return bytes(0)  `

> Traceback (most recent call last):
>   File "/opt/anaconda3.7/bin/keyring", line 11, in <module>
>     sys.exit(main())
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/keyring/cli.py", line 130, in main
>     return cli.run(argv)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/keyring/cli.py", line 72, in run
>     password = get_password(service, username)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/keyring/core.py", line 57, in get_password
>     return _keyring_backend.get_password(service_name, username)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/keyring/backends/chainer.py", line 46, in get_password
>     password = keyring.get_password(service, username)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/keyring/backends/SecretService.py", line 72, in get_password
>     return item.get_secret().decode('utf-8')
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/secretstorage/item.py", line 108, in get_secret
>     padded_secret = decryptor.update(encrypted_secret) + decryptor.finalize()
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
>     return self._ctx.update(data)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 124, in update
>     n = self.update_into(data, buf)
>   File "/opt/anaconda3.7/lib/python3.6/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 140, in update_into
>     self._backend._ffi.from_buffer(data), len(data)
> TypeError: a bytes-like object is required, not 'list'
>

**Comment by mitya57** [comment]
This was fixed in SecretStorage 3.1.1 (see mitya57/secretstorage#17). Please upgrade it to the latest version.
