### ISSUE TITLE
keyring.backends.SecretService doesn't neatly close open sockets.

### ISSUE THREAD

**Issue by CharString** [jaraco/keyring#380]
When I run a test_suite using setuptools test command and the nose.collector test_suite I get a couple of

    ResourceWarning: unclosed <socket.socket fd=4, family=AddressFamily.AF_UNIX, type=SocketKind.SOCK_STREAM, proto=0, raddr=/run/user/[...uid...]/bus>

I've tracked it down to the dbus socket being opened, but not closed before garbage collection.

**Comment by mitya57** [comment]
Can you please file this issue in [upstream secretstorage project](https://github.com/mitya57/secretstorage)?

I will try to fix it there, but that may require an API break.

**Comment by CharString** [comment]
I already have a patch
