### ISSUE TITLE
win32cred.CRED_PERSIST_ENTERPRISE and other keychain options

### ISSUE THREAD

**Issue by earonesty** [jaraco/keyring#382]
this option should be selectable by the user :

win32cred.CRED_PERSIST_ENTERPRISE

likewise (roaming or not roaming) should be available for other platforms.

1. i can implement this on windows.   not sure what the equivalent is on mac/linux:

2. I'm not sure what the interface should be even if i knew:

maybe something like this:

returns a dict with all supported options for that backend, or their defaults if the keychain has never been used

`res = keyring.get_chain_options("mykeychain")`

this likely will only work if the specified keychain has never been used before, raises a ValueError/NotSupported error if the platform doesn't support that option

`keyring.set_chain_options("mykeychain", roaming=False)`

**Comment by jaraco** [comment]
To help me understand, why would a person want to change this value?

**Comment by earonesty** [comment]
Suppose you have information that cannot leave the machine, like a machine private key in a multi-factor authentication scheme.   And then that factor magically migrates to another box....because windows.   We monkey patch to turn it off now.

**Comment by jaraco** [comment]
Aah. That clarifies. I'm now leaning toward a solution based on environment variables, which could be set globally in the machine, per-user, per invocation, or set in the program.

**Comment by mrx23dot** [comment]
Hello, 
How to actually use it?

```
keyring.set_chain_options("persist", 'local machine')
keyring.set_password('a', 'a', 'a')
```
didn't work. I couldn't find any documentation
Env.var also didn't work:
`set .persist="session"`

**Comment by jaraco** [comment]
To set it on the backend itself, set the `.persist` attribute:

```
backend = keyring.core.get_keyring()
backend.persist = 'session'
# or
backend.persist = win32cred.CRED_PERSIST_SESSION
```

Because keyring has a [general feature](https://github.com/jaraco/keyring#altering-keyring-behavior) that sets values on the backend, you can use that too. Set the environment variable `KEYRING_PROPERTY_PERSIST='session'`.

Let me know how that works for you. And if some documentation would have helped somewhere, please consider contributing that to help the next person.

**Comment by mrx23dot** [comment]
Works great, thanks!
