### ISSUE TITLE
Mysterious problems since keyring 16.0.1 (somehow caused by traceback kept in global variable)

### ISSUE THREAD

**Issue by Mekk** [jaraco/keyring#386]
Long story:
   https://bz.mercurial-scm.org/show_bug.cgi?id=6043
(mostly read from comment 14)

Short story: change introduced in 
https://github.com/jaraco/keyring/commit/c778a14ecccccb2407edc9347f0cdf40b97b3413
caused problems when keyring is imported inside Mercurial (with it's demandimport machinery). What is more funny, we see and test those problems on Linux and Mac.

I have no idea what's exactly going on and which part of the code is really guilty, but the whole problem narrows down to  traceback object being kept by keyring/backends/Windows.py in global variable (missing_deps) - most likely traceback keeps frames alive, frames keeps some variables alive etc.

Considering missing_deps is used there only as a boolean (to test whether there were any problems), please consider keeping such a flag instead. Fixes like:
```
with ExceptionRaisedContext() as missing_deps:
     #…

if missing_deps:
    missing_deps = True
```
or
```
with ExceptionRaisedContext() as missing_deps:
     #…

if missing_deps:
    missing_deps.traceback = None
```
resolve the issue.

(maybe it would be even better to reconsider keeping .traceback inside keyring.errors.ExceptionInfo, this attribute is not used for anything)

PS As I checked, this is the only place in keyring code where ExceptionInfo object is kept for a long time, other places using ExceptionRaisedContext use returned object temporarily.

**Comment by jaraco** [comment]
Can you confirm 18.0.1 fixes the issue?

**Comment by jaraco** [comment]
...which is [still releasing](https://travis-ci.org/jaraco/keyring/jobs/510604647) at the time of this posting.

**Comment by Mekk** [comment]
Unless I miss sth, you commited only change in CHANGES.rst
So it doesn't help.

**Comment by jaraco** [comment]
No I screwed up.

**Comment by Mekk** [comment]
9ea9bb5 helps and resolves the issue.

**Comment by Mekk** [comment]
… so please fix 18.0.1 tag (if release machinery allows it), or tag 18.0.2 (if not) ;-)

**Comment by jaraco** [comment]
18.0.1 is going out again here - https://travis-ci.org/jaraco/keyring/builds/510607549

**Comment by Mekk** [comment]
PyPi-installed 18.0.1 also fixes the issue.

**Comment by Mekk** [comment]
What about 19.0.1 too? From my point of view this is not crucial (mercurial is not yet officially py3-migrated) but this can be faced by people devel-testing py3 version. And of course some non-hg code can also face some similar problem (which, after all, narrowed to spoiling lifecycles and maybe even creating circular refs)

**Comment by jaraco** [comment]
Sure. I just pushed a 19.0.1 tag.

**Comment by Mekk** [comment]
Thank you for (very) quick fix.
