### ISSUE TITLE
Miss `kind` field when add new password

### ISSUE THREAD

**Issue by VictorMonte-zz** [jaraco/keyring#387]
Hi,

I'm trying to add a new password for an user with `internet application` kind, using keyring.
However, i did not find this field or parameter to pass it.
How can I achieve it ?

best regards.

**Comment by jaraco** [comment]
Sorry for the delay in response. Not sure how I missed it until now.

You must be inquiring about macOS, which stores "internet application" passwords in a separate store.

See #369, #260, #10. The current implementation doesn't support it, though I'm open to the project supporting it. I seem to recall I've taken a stab at the implementation a couple of times and been unsuccessful, but I welcome any help on it.
