### ISSUE TITLE
Why decode the password in get_password ?

### ISSUE THREAD

**Issue by alfred-sa** [jaraco/keyring#388]
Hello folks,

I would like to store crypto keys in a SecretStorage keyring.
Those are binary. I wonder why it is needed to decode() in get_password ? As we don't encode in set_password().

I would rather handle the decode myself, if needed, don't you ?

It there any backend that required an utf encoded string to store ?

Thanks

**Comment by mitya57** [comment]
Please see the discussion in #275.

**Comment by alfred-sa** [comment]
Thank you.
I base64 the binary key for now.

But I think that encode/decode should be symmetric (if we decode in get_password, we should encode in set_password). Or have an argument to specify to get_password to not decode maybe.

I can do a pull request if you like.

**Comment by jaraco** [comment]
> encode/decode should be symmetric

I agree.

It does appear that the underlying 'secretstorage' package expects bytes for `create_item`, but [this code](https://github.com/mitya57/secretstorage/blob/20d3244a4d85e3900d7bfacd7692e9ea15834234/secretstorage/util.py#L100-L101) allows it to accept text encodeable as UTF-8.

As a result, there's an implicit contract between keyring and secretstorage about the types of passwords accepted. That's undesirable. I suggest keyring should explicitly encode with 'utf-8' in `set_password` so it owns that encoding.

With or without that change, however, the recommendation in #275 still holds - the recommended (if not required) type for passwords passed to `set_password` is text (Unicode). If you have a binary field, you should decode your bytes using the `latin-1` encoding... and decode them using the same encoding when calling `get_password`. I should think that's more efficient than using a base64 encoding.

> I can do a pull request if you like.

Here are things I'd like possibly to see in the rough order I'd recommend implementing them:

1. Make the encoding/decoding symmetric in the secretstorage keyring be unconditionally encoding in `set_password`.
2. ~~Add a `get_password_bytes` and `set_password_bytes` (and `delete_password_bytes`?) to the Keyring base class to add support for bytes passwords in all keyrings.~~
3. Add type annotations or enhanced docstrings such that the "str/unicode" expectation for passwords is explicitly documented in the code.
4. Add concrete functionality to the Keyring base class that validates passwords for types such that the "str/unicode" expectation is enforced.

**Comment by jaraco** [comment]
I'm no longer in favor of #2. I dislike the idea of multiplying methods. I'd rather like to see something that layers functionality such that each backend doesn't have to support 2x methods. I'm going to close this issue, but welcome proposals, especially those that use some abstraction such as an adapter pattern to keep the backend abstraction simple.
