### ISSUE TITLE
Keyring works in Python Interactive shell but not in script (windows 10). AttributeError: module 'keyring' has no attribute 'set_password'

### ISSUE THREAD

**Issue by gstyle** [jaraco/keyring#389]
Hi,
I've run into a snag trying to use the keyring module in python. This is my first time using keyring so I may just have something misconfigured, however I found this situation a bit unexpected so I figured I'd ask for help.... I'm running Python v3.7.3 and Keyring v19.0.2 in Windows 10. I use Atom however the results are the same when I try to execute the code via a DOS or PS command line. The twist here is it works completely fine via the keyring shell command or IDLE. Here is my simple code.

`import keyring`
`keyring.set_password("system", "username", "password")`
returns
`Traceback (most recent call last):`
  `File "C:\Users\username\Documents\Python\test_keyring.py", line 4, in <module> `
`keyring.set_password("system", "username", "password")`
`AttributeError: module 'keyring' has no attribute 'set_password'
[Finished in 0.168s]`

Interesting thing is when I set the password via the command line and then display it like this, it works fine:
`PS C:\> keyring set system username`
`PS C:\> keyring get system username`
`password`

In the same script I can pass it to the OS and it will return my password.
`import os`
`os.system("keyring get system username")`
It will return 
`password`

I feel like it's not loading the module correctly but If I just run `import keyring` that runs successfully.

What am I doing wrong? Thanks in advance for the help!

**Comment by gstyle** [comment]
Figured this out. Nothing to do with the keyring module. Don't name your script filename the same as the module your importing. IE: keyring.py.  Lesson learned. XD

(in my defense I've only been using python for a week)

**Comment by pawamoy** [comment]
I'm having this issue as well, though my script is not named `keyring.py`. It might be because I'm trying to import keyring, and if it fails, I run a subprocess to install via pip and try again to import it. By that time, `sys.modules["keyring"]` might be populated with an empty module, not sure. The solution would be to `del sys.modules["keyring"]` before re-importing. I'll report back when I have more details.

**Comment by yashwardhan-gautam** [comment]
> `AttributeError: module 'keyring' has no attribute 'set_password' [Finished in 0.168s]`

Thanks a lot, I was struggling through the same error.
