### ISSUE TITLE
Keyring cache token has failed

### ISSUE THREAD

**Issue by juhi-09** [jaraco/keyring#390]
Keyring cache token has failed: While reading from '/home/ec2-user/.local/share/python_keyring/keyring_pass.cfg' [line 56]: option 'https_3a_2f_2flogin_2emicrosoftonline...' in section 'AzureAAD' already exists

Why is this happening?

**Comment by jaraco** [comment]
It sounds to me like in that file, you have two lines in a section `AzureAAD` with the same key. I'd inspect the file with a text editor and remove an invalid option. Normally I wouldn't expect that to happen unless somehow two keys are getting mapped to the same characters and colliding. Maybe share what the key is that shows up twice (but not the value as that would be your password).

**Comment by juhi-09** [comment]
How will it be possible to have 2 keys? and how is it related to cache?

**Comment by juhi-09** [comment]
Yes, a key is the same for 2 entries. How can I avoid it?

**Comment by jaraco** [comment]
I'm not sure. Can you show me how your keyrings are configured with the output from `keyring --list-backends`?

I suspect you have some file system-based backend from [keyrings.alt](/jaraco/keyrings.alt), which are unsupported. Here is [the code that sets a value in an ini file](https://github.com/jaraco/keyrings.alt/blob/f7bee88e5c369b19014b4ecf758eefc44f6c5d12/keyrings/alt/file_base.py#L161), and as you can see, it relies on the configparser to set a value, so I would not expect that to create duplicate values.

Perhaps you have some other program that's manipulating the keyring data and it created a duplicate key?

My suggestion is (a) don't use keyrings.alt if you can help it, and (b) for this particular issue, delete the duplicate entry manually, and if the issue occurs again, see if you can ascertain when/how that happens. If you're able to replicate the issue, I suggest reporting it to the keyrings.alt project.

**Comment by juhi-09** [comment]
I am now trying to suppress the warning using:
import warnings
warnings.filterwarnings(action='ignore', message=".*cache token has failed*")
but this is also not working. unable to suppress the warnings.
