### ISSUE TITLE
on macOS, is this library able to retrieve System Certificates?

### ISSUE THREAD

**Issue by hu13** [jaraco/keyring#392]

**Comment by jaraco** [comment]
Currently, this library only works with one facet of the keychain - the login keychain if I recall correctly. There are hacks to access other keychains, but not other categories of assets like certificates, as far as I know.

It's conceivable the backend could be reconfigured to support retrieving certificates, but I don't believe anyone has explored this possibility. Feel free to do so and share your findings or put together a pull request if you have a good design/implementation to share. Also, if you have more details about what your use-case is that you're trying to solve, that would be useful to know as well.

I'm closing this ticket for now, but feel free to continue to comment. We can re-open it later if appropriate.

**Comment by hu13** [comment]
Thank for the quick response.

I have a python daemon client which utilizes the `request` library to make https request to a server.
Sometimes, a request needs to go through a proxy that does SSL bump and we need to fetch the root certificate from the operating system to verify this proxy.

The native python SSL library only does not fetch any system certificates from macOS's keychain.
So I am looking for an alternative solution.

I will play around with your library and see if I can make it work.

**Comment by grvhi** [comment]
@hu13 - did you ever have any success with this?

**Comment by hu13** [comment]
> @hu13 - did you ever have any success with this?

@grvhi since we need to read all root and system certificates from keychain and merge it with those of certifi, we end up using `/usr/bin/security find-certificate -ap`. You can see an example of how we do in python here: https://github.com/PreVeil/pvHelpers/blob/master/pvHelpers/certificate_bundle.py#L39; a bit naive but it works.

**Comment by grvhi** [comment]
Much appreciated, thank you @hu13
