### ISSUE TITLE
piping password via stdin to set_password doesn't work

### ISSUE THREAD

**Issue by henrymei** [jaraco/keyring#393]
I saw that support for this was introduced by https://github.com/jaraco/keyring/pull/332; however, I'm unable to get it to work be it in my specific use case (piping user-inputted credentials as part of a shell script) or using the example in the original PR:
```
 $ openssl rand -base64 64 | tr -d "\n/+=" | keyring set application api-key
```

I'm curious if anybody else can reproduce or if I'm missing something obvious because late night.

**Comment by jaraco** [comment]
It's working for me.

```
keyring master $ echo foo | keyring set foo bar
keyring master $ keyring get foo bar
foo
```

Sorry to hear you couldn't get it to work. It would be helpful if you reported what _did_ happen (error, password set to wrong value, password not set). I'm assuming you're reporting that the password was not set. In that case, you want to demonstrate that setting a password through the interactive prompt is working as expected but setting through a pipe is not. Feel free to comment/reopen if you're still having issues and can provide more detail.
