### ISSUE TITLE
Allow fetching a username/password pair without specifying the user

### ISSUE THREAD

**Issue by exhuma** [jaraco/keyring#398]
**Use Case:** For historical reasons, our company is currently using two AD instances (work is ongoing to merge) and users have different user-names on both. Some services use one, some the other. So the user-name is not known in advance. I can only use the local user-name for one of those ADs.

The credential manager already contains credentials with the appropriate username/password pairs but I am unable to fetch them using `keyring` as I don't know the username in advance.

* In a `.netrc` file, it is possible to retrieve a username/password pair with only knowing the service name.
* In the Windows Credential Manager a "Generic Credential" also stores only one username per service, so the service-name is sufficient to retrieve the credentials (see https://gist.github.com/exhuma/a310f927d878b3e5646dc67dfa509b42)

I could imagine one of the following interfaces on `keyring`:

    # Make the username optional. If there exist implementations with multiple
    # credentials per service, this may become non-deterministic (depending on back-end).
    def get_credential(service: str, username: str = '') -> Optional[SimpleCredential]: ...

or a new function `get_credentials`:

    # A new function to list credentials. This should be deterministic no matter
    # which back-end is used, and does not change any existing implementation:
    def get_credentials(service: str) -> Set[SimpleCredential]: ...

**Comment by jaraco** [comment]
The latest keyring has this functionality for the Windows keyring. Can you explore the existing interface and see how well it does or doesn’t suit your needs?

**Comment by exhuma** [comment]
I must have missed this. I was looking through the code and docs and did not come across this. I'll look again... 😄

**Comment by exhuma** [comment]
🤔 Looking at https://github.com/jaraco/keyring/blob/master/keyring/backends/Windows.py only shows the two public methods `get_password` and `get_credential` which still require the username.

Are you thinking about using [the private method _get_password](https://github.com/jaraco/keyring/blob/master/keyring/backends/Windows.py#L72)? This does however leak the internal `win32cred.CredRead` result.

**Comment by jaraco** [comment]
It's certainly not well-documented, but it seems [you can pass `None`](https://github.com/jaraco/keyring/blob/979f4dd6078b7ee2db3d5ac71dd3e5bfad62331e/keyring/tests/test_backend.py#L148-L152) for the user to find the "first" matching credential for the given service.

**Comment by ckuethe** [comment]
Can you add the same functionality to linux back ends?

```
>>> import keyring
>>> keyring.set_password('keyring-test', 'myName', 'SecretP@55w0rd!')
>>> keyring.get_password('keyring-test', 'myName')
u'SecretP@55w0rd!'
>>> keyring.get_password('keyring-test', None)
ERROR:dbus.connection:Unable to set arguments ({'username': None, 'service': 'keyring-test'},) according to signature 'a{ss}': <type 'exceptions.TypeError'>: Expected a string or unicode object
>>> print keyring.get_credential('keyring-test', None)
None
```

**Comment by ggirard07** [comment]
@jaraco I saw this being used from the Pyhton interface by passing `None`, but I can't find a way to do the same from the CLI...

I tried the following but none of those seem to work...
```cmd
python -m keyring get netaddress None
python -m keyring get netaddress
Usage: __main__.py [get|set|del] SERVICE USERNAME

__main__.py: error: Wrong number of arguments
python -m keyring get netaddress ''
Usage: __main__.py [get|set|del] SERVICE USERNAME

__main__.py: error: Wrong number of arguments
python -m keyring get netaddress ""
Usage: __main__.py [get|set|del] SERVICE USERNAME

__main__.py: error: Wrong number of arguments
python -m keyring get netaddress 'None'
python -m keyring get netaddress "None"
```

Python 3.8.2
Keyring 21.2.0
Pip 20.0.2
Windows 10

**Comment by jaraco** [comment]
> I can't find a way to [fetch a username/password pair without specifying the user] from the CLI.

I don't think that use-case has been implemented... and adding support for that to the CLI puts pressure on the other backends to implement this sort of usage, which may be fine or may cause others consternation. I think there are several actions needed to formalize this support. I've filed #429 to track.

> Can you add the same functionality to linux back ends?

See #431.
