### ISSUE TITLE
keyring logging at info level as side effect of being imported

### ISSUE THREAD

**Issue by gar1t** [jaraco/keyring#405]
This line:

https://github.com/jaraco/keyring/blob/master/keyring/backend.py#L187

generates INFO logs on import. I believe this type of information, given that it's generated as a side effect of import, should be DEBUG to avoid generating output on something as innocuous as import.

If the information must be logged as INFO, I believe this behavior should be deferred until needed, rather.

Imports are hard to order and in any complex environment as effectively non-deterministic. This makes the INFO log output nondeterministic, which makes testing very difficult. Given the core role of keyring in the Python ecosystem, logged output at the INFO level can pop up in surprising ways.

**Comment by jaraco** [comment]
Seems reasonable to log at the debug level there.
