### ISSUE TITLE
Allow for specifying "Ask for keychain password"

### ISSUE THREAD

**Issue by jdamata** [jaraco/keyring#406]
I would like to be prompted for my keychain password when attempting to get a password. I came this issue https://github.com/jaraco/keyring/issues/282. Instead of setting an empty list of allowed applications, is it possible to enable the  "Ask for keychain password" on password creation?

**Comment by jdamata** [comment]
SecAccessCreate could be called on an existing keychain item to remove the default trusted app.
https://developer.apple.com/documentation/security/1393522-secaccesscreate?language=objc

For enabling asking for keychain password, we can use SecAccessControlCreateWithFlags
https://developer.apple.com/documentation/security/1394452-secaccesscontrolcreatewithflags?language=objc

**Comment by jaraco** [comment]
keyring aims to make the process of credential retrieval as non-interactive as possible. If you wish to change that expectation, it will need to be an opt-in feature. I suggest creating a third-party keyring backend that has this behavior to demonstrate (and supply) the behavior you desire, and then this project can evaluate the behavior and consider integrating it as a native feature.

This project would eagerly expand the private macOS APIs to facilitate such a feature. Just send PRs explaining that you're adding functionality for a third-party package.

How does that sound?
