### ISSUE TITLE
importlib question

### ISSUE THREAD

**Issue by micahculpepper** [jaraco/keyring#412]
Hi @jaraco, no issues to report here, just a question. What motivated the switch to importlib in a9fe22750359c2ca337c83d838e3654ef1fa38ea? I had not heard of this library before, and it seems like it might be important for packaging.

**Comment by jaraco** [comment]
Hi Micah. `importlib.metadata` and [the backport](https://pypi.org/project/importlib_metadata) were created to supplant the use-cases of `pkg_resources`, including entry points... and to provide an implementation available in the standard library. So the main advantage is that keyring is no longer dependent on any third-party library (for Python 3.8 and later). The other advantage is that `importlib.metadata` provides a clean and relatively performant tool for getting metadata generally about a package. I've spent the last 1.5 years making it a reality, so I'm eager to see it adopted in packages that rely on the behaviors it provides.

**Comment by micahculpepper** [comment]
Cool, thanks for the heads up! I've got a few projects that have dependencies on `setuptools` just so that they can use `pkg_resources` to find their data files. I'm glad there's something in the standard library for this now. Thanks for working on this!
