### ISSUE TITLE
Unable to use keyring with ubuntu 16.04

### ISSUE THREAD

**Issue by ahqardah** [jaraco/keyring#413]
**Describe the bug**
I am trying to use Keyring to store a user's access token locally. It works just fine with xOS, Windows, and Ubuntu 18.04. On the other hand, it fails with Ubuntu 16.04. I followed the instructions offered here
```
$ sudo apt install python3-venv libdbus-glib-1-dev
$ cd /tmp
$ pyvenv py3
$ source py3/bin/activate
$ pip install -U pip
$ pip install secretstorage dbus-python
$ pip install keyring
$ python
>>> import keyring
>>> keyring.get_keyring()
<keyring.backends.SecretService.Keyring object at 0x7f9b9c971ba8>
>>> keyring.set_password("system", "username", "password")
>>> keyring.get_password("system", "username")
'password'
```
with no luck, I get the following backend: when checking
```
 keyring.get_backend()
<keyring.backends.fail.Keyring object at 0x7fc4b7e63940>
```

**To Reproduce**
use ubuntu 16.04
follow the steps highlighted above.

**Expected behavior**
It's supposed to use SecretService as the backend, not chainer, sometimes I get fail.Keyring.

**Environment**

- OS: Ubuntu 16.04

```
$ pip list | grep keyring

```
keyring            19.3.0 

```
$ keyring --list-backends
```

```
keyring.backends.chainer.ChainerBackend (priority: 0)
keyring.backends.fail.Keyring (priority: 0)
```

**Comment by ahqardah** [comment]
@jaraco your help is much appreciated. Thanks!

**Comment by jaraco** [comment]
It seems that somehow `keyring.backends.SecretService.Keyring.viable` is raising an exception. Can you try executing that statement and see what it emits?

**Comment by jaraco** [comment]
Or maybe `keyring.backends.SecretService.Keyring.priority`.

**Comment by ahqardah** [comment]
`keyring.backends.SecretService.Keyring.viable` gives `False`
`keyring.backends.SecretService.Keyring.priority` gives:
```
Traceback (most recent call last):
  File "/tmp/py3/lib/python3.5/site-packages/secretstorage/__init__.py", line 37, in dbus_init
    connection = connect_and_authenticate()
  File "/tmp/py3/lib/python3.5/site-packages/jeepney/integrate/blocking.py", line 90, in connect_and_authenticate
    bus_addr = get_bus(bus)
  File "/tmp/py3/lib/python3.5/site-packages/jeepney/bus.py", line 53, in get_bus
    return find_session_bus()
  File "/tmp/py3/lib/python3.5/site-packages/jeepney/bus.py", line 42, in find_session_bus
    addr = os.environ['DBUS_SESSION_BUS_ADDRESS']
  File "/usr/lib/python3.5/os.py", line 725, in __getitem__
    raise KeyError(key) from None
KeyError: 'DBUS_SESSION_BUS_ADDRESS'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 40, in priority
    bus = secretstorage.dbus_init()
  File "/tmp/py3/lib/python3.5/site-packages/secretstorage/__init__.py", line 43, in dbus_init
    raise SecretServiceNotAvailableException(reason) from ex
secretstorage.exceptions.SecretServiceNotAvailableException: Environment variable DBUS_SESSION_BUS_ADDRESS is unset

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/py3/lib/python3.5/site-packages/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 43, in priority
    raise RuntimeError("Unable to initialize SecretService: %s" % e)
RuntimeError: Unable to initialize SecretService: Environment variable DBUS_SESSION_BUS_ADDRESS is unset
```

**Comment by jaraco** [comment]
Great. So now we know the cause. There's no DBUS_SESSION_BUS_ADDRESS defined. I believe that value needs to be defined for dbus (and thus SecretService) to work. Are you in a headless session? Do [these docs](https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems) help?

**Comment by ahqardah** [comment]
Yes, this is on a build agent, which is headless. The docs don't really help :/ as they require the user to interactively enter a password for the keychain. Is there any other workaround?

**Comment by ahqardah** [comment]
```
(py3) agentadmin@host:/tmp$ dbus-run-session -- sh
(py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ gnome-keyring-daemon --unlock
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
(py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ gnome-keyring-daemon -- unlock
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
(py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ python
Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import keyring
>>> keyring.get_password('system', 'user')
Activating service name='org.gnome.keyring.SystemPrompter'
Activated service 'org.gnome.keyring.SystemPrompter' failed: Process org.gnome.keyring.SystemPrompter exited with status 1
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/py3/lib/python3.5/site-packages/keyring/core.py", line 56, in get_password
    return _keyring_backend.get_password(service_name, username)
  File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 74, in get_password
    collection = self.get_preferred_collection()
  File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 62, in get_preferred_collection
    raise KeyringLocked("Failed to unlock the collection!")
keyring.errors.KeyringLocked: Failed to unlock the collection!
```

**Comment by jaraco** [comment]
> The docs ... require the user to interactively enter a password for the keychain

Well, that's sort-of the problem with Linux - it doesn't provide a platform for unlocking a credential store during login the way macOS and Windows do. Instead, it requires you to separately enter a credential to unlock the credential store. So you're left with having to fall back to first principles to decide what it is you're trying to do and how can you accomplish that securely. I don't think there's anything keyring could do to remedy that situation.

@mitya57 might have some advice on how to unlock the dbus session, at least interactively.

**Comment by ahqardah** [comment]
Thanks a bunch @jaraco! really appreciate your help

**Comment by mitya57** [comment]
The problem is that the `--unlock` option was [added in gnome-keyring 3.11.92][1], and Ubuntu 16.04 has 3.10.1. So unlocking the keyring non-interactively is not possible.

I would suggest you to use the `keyrings.alt.file.EncryptedKeyring` backend from [keyrings.alt][2], which is generally discouraged, but for your use case it fits better.

[1]: https://gitlab.gnome.org/GNOME/gnome-keyring/blob/3.34.0/NEWS#L122
[2]: https://github.com/jaraco/keyrings.alt

**Comment by ahqardah** [comment]
```
keyrings.cryptfile.file.PlaintextKeyring (priority: 0.5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.OS_X.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyrings.cryptfile.cryptfile.CryptFileKeyring (priority: 2.5)
keyrings.cryptfile.file.EncryptedKeyring (priority: 0.6)
```
another question @jaraco why does it not select the right keyring for the OS, right now I'm on Mac, it automatically selects Chainer, when it's supposed to be on OS_X. Is there something I am missing here?

**Comment by jaraco** [comment]
@ahqardah Since your question doesn't pertain to the issue, can you open a new issue with a title that will help others find your question? I have an answer prepared.

**Comment by Dinu8** [comment]
> ```
> (py3) agentadmin@host:/tmp$ dbus-run-session -- sh
> (py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ gnome-keyring-daemon --unlock
> SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> (py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ gnome-keyring-daemon -- unlock
> SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
> (py3) \[\e]0;\u@\h: \w\a\]\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]$ python
> Python 3.5.2 (default, Oct  8 2019, 13:06:37) 
> [GCC 5.4.0 20160609] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import keyring
> >>> keyring.get_password('system', 'user')
> Activating service name='org.gnome.keyring.SystemPrompter'
> Activated service 'org.gnome.keyring.SystemPrompter' failed: Process org.gnome.keyring.SystemPrompter exited with status 1
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/tmp/py3/lib/python3.5/site-packages/keyring/core.py", line 56, in get_password
>     return _keyring_backend.get_password(service_name, username)
>   File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 74, in get_password
>     collection = self.get_preferred_collection()
>   File "/tmp/py3/lib/python3.5/site-packages/keyring/backends/SecretService.py", line 62, in get_preferred_collection
>     raise KeyringLocked("Failed to unlock the collection!")
> keyring.errors.KeyringLocked: Failed to unlock the collection!
> ```

SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
This means you are trying to unlock keyring as user. You have to be root be able to unlock.

So run the dbus session like this and it will work:
sudo dbus-run-session -- sh
