### ISSUE TITLE
impossible to use keyring.core.init_backend(limit=keyring.core.recommended)

### ISSUE THREAD

**Issue by ddstreet** [jaraco/keyring#423]
**Describe the bug**
This documentation is in the CHANGES.rst file, but it's impossible to use because it results in endless recursion between chainer.py's priority property and backends function.

**To Reproduce**

 import keyring
 keyring.core.init_backend(keyring.core.recommended)
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "/build/repos/python-keyring/python-keyring/keyring/core.py", line 94, in init_backend
>     or max(
>   File "/build/repos/python-keyring/python-keyring/keyring/core.py", line 78, in recommended
>     return backend.priority >= 1
>   File "/build/repos/python-keyring/python-keyring/keyring/util/properties.py", line 26, in __get__
>     return self.fget.__get__(None, owner)()
>   File "/build/repos/python-keyring/python-keyring/keyring/backends/chainer.py", line 26, in priority
>     return 10 * (len(cls.backends) > 1)
>   File "/build/repos/python-keyring/python-keyring/keyring/util/properties.py", line 26, in __get__
>     return self.fget.__get__(None, owner)()
>   File "/build/repos/python-keyring/python-keyring/keyring/backends/chainer.py", line 39, in backends
>     return sorted(allowed, key=backend.by_priority, reverse=True)
>   File "/build/repos/python-keyring/python-keyring/keyring/backends/chainer.py", line 34, in <genexpr>
>     allowed = (
>   File "/build/repos/python-keyring/python-keyring/keyring/core.py", line 78, in recommended
>     return backend.priority >= 1
> 
etc...

**Expected behavior**
restrict backends to only those 'recommended' (priority > 1)

**Comment by jaraco** [comment]
After creating a test, I'm able to replicate the failure in the test suite. Here's the output:

```
>       keyring.core.init_backend(keyring.core.recommended)

tests/test_core.py:9: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
keyring/core.py:94: in init_backend
    or max(
keyring/core.py:78: in recommended
    return backend.priority >= 1
keyring/util/properties.py:26: in __get__
    return self.fget.__get__(None, owner)()
keyring/backends/chainer.py:29: in priority
    return 10 if len(cls.backends) > 1 else (fail.Keyring.priority - 1)
keyring/util/properties.py:26: in __get__
    return self.fget.__get__(None, owner)()
keyring/backends/chainer.py:42: in backends
    return sorted(allowed, key=backend.by_priority, reverse=True)
keyring/backends/chainer.py:37: in <genexpr>
    allowed = (
keyring/core.py:78: in recommended
    return backend.priority >= 1
E   RecursionError: maximum recursion depth exceeded while calling a Python object
```
