### ISSUE TITLE
Module cannot be installed under Macos Catalina?

### ISSUE THREAD

**Issue by coleblackman** [jaraco/keyring#435]
Hi. I have attempted to install keyring with `pip3 install keyring` but any python program which attempts to import it cannot find the module and the command `keyring` is not found in command line. I also attempted to install with `pip install keyring`. Other modules installed with pip work fine. Thanks

**Comment by jaraco** [comment]
It works for me:

```
draft $ python -m venv env
draft $ env/bin/pip install keyring
Collecting keyring
  Using cached https://files.pythonhosted.org/packages/04/21/42d92822959a37ccc390742c2706c8b06cc6a29c10a5ef2e8d22cf0e2e33/keyring-21.2.0-py3-none-any.whl
Installing collected packages: keyring
Successfully installed keyring-21.2.0
WARNING: You are using pip version 19.2.3, however version 20.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
draft $ env/bin/python -c "import keyring" && echo "no problem"
no problem
```

You'll need to provide more detail. Maybe try running `pip install -v keyring` and paste the output (use triple-backticks before and after pasting).

**Comment by coleblackman** [comment]
Thanks for trying to help. `pip install -v keyring` returns: 
```Defaulting to user installation because normal site-packages is not writeable
Created temporary directory: /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-ephem-wheel-cache-BHXoQ3
Created temporary directory: /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-req-tracker-ccz8Rr
Initialized build tracking at /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-req-tracker-ccz8Rr
Created build tracker: /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-req-tracker-ccz8Rr
Entered build tracker: /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-req-tracker-ccz8Rr
Created temporary directory: /private/var/folders/tv/x5w6z5yd7591qhs9jpq8gsk80000gn/T/pip-install-6S_NhW
Requirement already satisfied: keyring in ./Library/Python/2.7/lib/python/site-packages (18.0.1)
Requirement already satisfied: entrypoints in ./Library/Python/2.7/lib/python/site-packages (from keyring) (0.3)
Requirement already satisfied: configparser>=3.5; python_version == "2.7" in ./Library/Python/2.7/lib/python/site-packages (from entrypoints->keyring) (4.0.2)
```

I suspect my python install directory is incorrect? In any case, I don't think it's an issue with keyring, though it is odd that other modules install okay. Thanks.

**Comment by jaraco** [comment]
That's helpful. It tells me a few things:

- You have `pip` associated with `python2.7`.
- `pip` is installing to ~/Library (user-local installs).
- Any binary would be installed at ~/Library/Python/2.7/bin.

You may have noticed that Python 2.7 is deprecated on macOS Catalina.

```
~ $ python2.7

WARNING: Python 2.7 is not recommended. 
This version is included in macOS for compatibility with legacy software. 
Future versions of macOS will not include Python 2.7. 
Instead, it is recommended that you transition to using 'python3' from within Terminal.

Python 2.7.16 (default, Feb 29 2020, 01:55:37) 
...
```

You should probably try to get away from using Python 2.7, make sure you understand which pip you're using `which pip`. The most straightforward way to ensure you're using the right pip from from the python environment you're targeting is to invoke pip from that python (e.g. `python3.8 -m pip install ...`).

Additionally, if you want console scripts installed, you're going to want to ensure that the `bin` directory for that environment is on your path. For example, I put these lines in my ~/.bash_profile to ensure that binaries of Python 3.8 (and scripts for other packages installed at the system site-packages) are available as commands:

```
PATH="/Library/Frameworks/Python.framework/Versions/3.8/bin:${PATH}"
export PATH
```

Beware, macOS Catalina prefers zsh for a shell; I'm not sure how to customize paths for zsh.

When you run `pip3 install keyring`, you'll be getting a different install to a different location. You'll want to run that with `-v` to see where it's installing to.

Regardless, there's nothing wrong with keyring here. If you need more help installing packages with Python, please research on the [Python Packaging User's Guide](https://packaging.python.org) or with your best user's support group.

**Comment by coleblackman** [comment]
Thanks, you've been really helpful.
