### ISSUE TITLE
Add type annotations

### ISSUE THREAD

**Issue by bhrutledge** [jaraco/keyring#437]
I've been working on adding type annotations to Twine (https://github.com/pypa/twine/issues/231), and keyring is one of our imports that's missing type hints/stubs. Is there any interest in adding those, either in the source or to https://github.com/python/typeshed?

See also: https://mypy.readthedocs.io/en/stable/existing_code.html

**Comment by jaraco** [comment]
I'm happy for someone to contribute type annotations. This codebase has mypy support, so anyone who would like to add annotations, especially ones that add meaningful value, I'm all for it.

**Comment by jaraco** [comment]
The project has one typing annotation and welcomes more. mypy tests pass and the project now includes a `py.typed` file.
