### ISSUE TITLE
[mercurial-keyring] cannot import name 'backend' from 'cryptography.hazmat.backends.openssl.backend'

### ISSUE THREAD

**Issue by php4fan** [jaraco/keyring#450]
**Describe the bug**

I have been using `mercurial_keyring` for years, a mercurial extension that in turn uses `keyring`.

Since I've upgraded to Ubuntu 20.04, mercurial_keyring is broken. I upgraded a bunch of stuff, and now the error I get seems to be due to keyring itself.

**To Reproduce**
1. cd to a mercurial repository
2. run
```
hg pull
```
(or any other hg command that requires a password, for that matter)

**Expected behavior**
Should work

**Observed behavior**
(Why does the report template have "expected behavior" but not "observed behavior", btw?)

```
$ hg pull
pulling from ******************
keyring: keyring backend doesn't seem to work, password can not be restored. Falling back to prompts. Error details: cannot import name 'backend' from 'cryptography.hazmat.backends.openssl.backend' (/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/backend.py)

```

**Environment**

- OS: ubuntu 20.04

```
$ pip list | grep keyring
keyring                   21.2.1
mercurial-keyring         1.3.1

...
$ keyring --list-backends
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.kwallet.DBusKeyring (priority: 4.9)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyring.backends.fail.Keyring (priority: 0)

...
```

**Additional context**

**Comment by jaraco** [comment]
Thanks for the report.

Unfortunately, what you've described is an issue with `mercurial` or `mercurial_keyring`. The error details:

```
cannot import name 'backend' from 'cryptography.hazmat.backends.openssl.backend' (/usr/local/lib/python3.8/dist-packages/cryptography/hazmat/backends/openssl/backend.py)
```

Seem unrelated to anything I know about keyring.

I've been unable to replicate your findings in a clean environment. I tried creating a docker environment with a Mercurial repository:

```
FROM ubuntu:focal
RUN apt update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt install -y mercurial mercurial-keyring python3-pip
RUN hg clone https://foss.heptapod.net/pypy/pypy
```

And then try to push a change to that repo, but it prompts for a password.

```
root@df54affcd47f:/# cd pypy
root@df54affcd47f:/pypy# touch foo
root@df54affcd47f:/pypy# hg add foo
root@df54affcd47f:/pypy# hg commit -m "added foo" --user jaraco    
root@df54affcd47f:/pypy# hg push
pushing to https://foss.heptapod.net/pypy/pypy
searching for changes
http authorization required for https://foss.heptapod.net/pypy/pypy
realm: GitLab
user: interrupted!
```

Moreover, I don't see the same backends or versions as you do:

```
root@df54affcd47f:/pypy# pip3 list
Package                   Version
------------------------- -------
cryptography              2.8    
dbus-python               1.2.16 
entrypoints               0.3    
keyring                   18.0.1 
mercurial-extension-utils 1.5.0  
mercurial-keyring         1.3.0  
pip                       20.0.2 
PyGObject                 3.36.0 
SecretStorage             2.3.1  
setuptools                45.2.0 
six                       1.14.0 
wheel                     0.34.2 
root@df54affcd47f:/pypy# keyring --list-backends
keyring.backends.chainer.ChainerBackend (priority: -10)
keyring.backends.fail.Keyring (priority: 0)
```

Can you do some more investigation and determine how to create a repeatable environment that exhibits the errors you experience?

Thanks.

**Comment by mitya57** [comment]
`cryptography` has a pure Python part and a C extension part. Maybe the Python part installed correctly but something is wrong with the C part?

**Comment by jaraco** [comment]
Closing as the issue has languished, but happy to revisit if there's more information.
