### ISSUE TITLE
SecretService get_credential doesn't return None for missing entry

### ISSUE THREAD

**Issue by EpicWink** [jaraco/keyring#452]
When calling `keyring.get_credential` using [the SecretService backend](https://github.com/jaraco/keyring/blob/fb74a37d54657b279c76360cf82b850ba33d1654/keyring/backends/SecretService.py#L105-L124), if a username is provided but the corresponding entry doesn't exist in the keyring, a Credential object with the provided username (and no password) is returned, instead of None. This is in contrast to what happens in [the default implementation](https://github.com/jaraco/keyring/blob/fb74a37d54657b279c76360cf82b850ba33d1654/keyring/backend.py#L125-L138), where None is returns if  the entry is not found.

This causes pypa/pip#8634

### Reproduction
```python
>>> import keyring
>>> c = keyring.get_credential("spam", "eggs")
```

#### Expected
```python
>>> print(c)
None
```

#### Actual
```python
>>> print(c)
<keyring.credentials.SimpleCredential object at 0x...>
>>> print(c.username, c.password)
eggs None
```

#### Environment
* OS: Ubuntu 20.04.1
* keyring: 21.2.1 (first seen in 19.2)
  * keyring.backends.chainer.ChainerBackend (priority: -1)
  * keyring.backends.SecretService.Keyring (priority: 5)
  * keyring.backends.fail.Keyring (priority: 0)

**Comment by mitya57** [comment]
Can you please test my PR #453?

**Comment by EpicWink** [comment]
#453 fixes the issue for me
