### ISSUE TITLE
why does not keyring  install "secretstorage" on mac?

### ISSUE THREAD

**Issue by gepolv** [jaraco/keyring#455]
**Describe the bug**
I did a fresh install of `keyring` with version `21.3.0` and found `secretstorage` was not installed (not in `Pipfile.lock`). Then I took a look at : https://github.com/jaraco/keyring/blob/master/setup.cfg#L24-L28
```
install_requires =
	pywin32-ctypes!=0.1.0,!=0.1.1; sys_platform=="win32"
	SecretStorage>=3; sys_platform=="linux"
	jeepney>=0.4.2; sys_platform=="linux"
	importlib_metadata; python_version < "3.8"
```
which clearly states it will install `SecretStorage` on linux. My question is why it does not need to install on mac? 

**To Reproduce**
1: install keyring
>pip install keyring

2: check `Pipfile.lock`

**Expected behavior**
`secretstorage` should be installed on mac as well (appear in `Pipfile.lock`)

**Environment**
macos
- OS: [e.g. macOS]

**Additional context**

**Comment by gepolv** [comment]
it is not linux platform.

**Comment by mitya57** [comment]
SecretStorage does not make sense on macOS, as there is no D-Bus or Secret Service daemon there.

On macOS the native OS_X / Keychain backend should be used.
