### ISSUE TITLE
Latest version of black invalidates code

### ISSUE THREAD

**Issue by hoffmang9** [jaraco/keyring#461]
**Describe the bug**
When we bumped keyring to 21.3.1 our Windows installers started to hang opening our wallet on Windows. At this point I'm looking for some assistance with the black errors that tox is throwing in our fork so that we can attempt to better debug the issue. It almost has to be the argv change but first I'd like to get our fork's tests passing.

I replicated your azure action in GitHub actions and you can see the black errors here:
https://github.com/Chia-Network/keyring/runs/1043172888?check_suite_focus=true#step:7:57

Our travis runs have the same issues:
https://travis-ci.com/github/Chia-Network/keyring/jobs/378964137#L291

**To Reproduce**
1. Go to our fork's ci
2. Click on the links above and they will autoscroll to the start of the error section.

**Expected behavior**
Black shouldn't be throwing errors on a fork from jaraco/keyring master.

Also, python 3.7 windows shouldn't fail but we'll come back to that.

**Environment**

- OS: Windows, Travis, GitHub Actions

```
$ pip list | grep keyring
...
$ keyring --list-backends
...
```

**Additional context**

**Comment by jaraco** [comment]
Errors with black were patched in 87122870b37aca37c8988c9368ca0e7d71d25aaf.

**Comment by jaraco** [comment]
Now that the black issues are solved, please open a separate issue about the Windows failures.

**Comment by hoffmang9** [comment]
FYI that it looks like there was some odd interaction between keyring and another bug we introduced - but fixed - in the interim. Windows seems to now be ok with 21.4.0.

Thanks for the help on black. I didn't catch that the black version had changed so I was scratching my forehead about why your ci's didn't fail too...
