### ISSUE TITLE
Interact with Windows Credential Manager via WSL2?

### ISSUE THREAD

**Issue by alextruong** [jaraco/keyring#472]
Is there anything in place (e.g. by Microsoft) to enable this to function? I get the expected
```
keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.
```
when attempting to access it from within a WSL2 distro, but I haven't found any other questions about this on the internet. Thanks!

**Comment by jaraco** [comment]
There's nothing as far as I know. If you look at the `backends.Windows` implementation, you'll see that it relies on ctypes and the Windows C APIs, so it's no big surprise that from within Linux, those APIs aren't generally available. I'd reach out to a WSL support group and inquire if reaching the Credential Manager from WSL2 is possible and if so, what interfaces are supported, and we can work from there.

**Comment by jaraco** [comment]
I did some quick searches around the Internet and I struggle to see any resources on accessing Windows APIs from WSL2. I imagine it's possible, even supported, but someone with more expertise than me will need to work on it. Until someone volunteers to do that work, I'm going to close this issue, but happy to revisit and provide guidance should that come to pass.
