### ISSUE TITLE
keyring.backends.OS_X.Keyring gone, now py2app-compiled app is lost

### ISSUE THREAD

**Issue by yanone** [jaraco/keyring#489]
Since late, `keyring` doesn't work anymore on my py2app-compiled app on macOS. I always had to set a backend explicitly using 

`keyring.core.set_keyring(keyring.core.load_keyring("keyring.backends.OS_X.Keyring"))`

or otherwise it wouldn’t work, throwing: 

`keyring.errors.NoKeyringError: No recommended backend was available. Install a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.`

But of late, the contents of `keyring.backends.OS_X.Keyring` have disappeared, now throwing an expected 

`AttributeError: module 'keyring.backends.OS_X' has no attribute 'Keyring'`

I've never inquired as to why the explicit backend loading was necessary in a compiled app, but was never bothered either. It worked after all. Now it doesn't work anymore.

I'm also setting the backend explicitly for Windows, but there at least the backend is still there.
It's a cross-platform GUI app currently for Mac and Windows, later also Linux.

I can currently only use an older `keyring` version. Can you maybe help in getting the default behaviour (no explicit backend loading) work in compiled apps or suggest other ways?
Thank you

**Comment by yanone** [comment]
Nevermind. I just went through your commits and saw the change from `OS_X` to `macOS`. It works now.

However, maybe you could still help as to why the explicit loading is necessary for compiled apps in the first place. Cause otherwise my app compilations would have never choked on your changed implementation. Loading them the default way is still something I'd like to achieve.

**Comment by jaraco** [comment]
Sorry for the hassle. I did [advertise the change](https://keyring.readthedocs.io/en/latest/history.html#v22-0-0) in a backward-incompatible release.

> why the explicit loading is necessary for compiled apps

It has to do with metadata discovery. Keyring solicits backends from its core implementation and plugins - through entry points, and depending on the tool employed for compiling apps, the metadata is often lost or not accessible through the metadata discovery (i.e. `importlib.metadata.entry_points()`).

Recent innovations in metadata discovery do provide a [mechanism](https://importlib-metadata.readthedocs.io/en/latest/using.html#extending-the-search-algorithm) for environment providers like these app compilers to expose the installed distribution metadata.

If the app compiler you used employed this technique, the discovery would be automatic. I'm happy to advise these projects on how to implement this integration, so feel free to mention me in a relevant issue if I can help.

**Comment by jaraco** [comment]
Looks like py2app is tracking the issue at ronaldoussoren/py2app#256.
