### ISSUE TITLE
set_properties_from_env is not called on "chained" keyring backends

### ISSUE THREAD

**Issue by p-sherratt** [jaraco/keyring#495]
**Describe the bug**
When the `ChainerBackend` is selected as highest priority via get_keyring(), set_properties_from_env() is called against the chainer.  But then as each viable/subordinate backend is instantiated, its own set_properties_from_env() method is _not_ called, and hence any custom KEYRING_PROPERTY_ environment variables are not picked up by the chained keyring backend.

**To Reproduce**
Please see https://github.com/p-sherratt/sagecipher/issues/1 for details of this bug.

**Expected behavior**
set_properties_from_env() should be called on chained backends.

**Comment by p-sherratt** [comment]
On reflection I wonder if this might be a design choice and should just be noted in the readme/docs?  i.e. if a user is setting `KEYRING_PROPERTY_*` in the environment, they should probably set the appropriate `PYTHON_KEYRING_BACKEND` too rather than rely on the chainer.

**Comment by hans2520** [comment]
@p-sherratt In regards to your last comment, would there not be `KEYRING_PROPERTY_*` that could be potentially used in the same way by different backends? If yes, then it would be a desired behavior to set the environment without relying on a distinct backend. In which case, I would argue that the chainer should set the environment on the invoked backends (or else leave that up to the backends to do).

**Comment by jaraco** [comment]
Well described bug. I hadn't considered this case much, but I do agree with the sentiment and original proposal.

**Comment by jaraco** [comment]
I'm wondering if there may be a better design that would cause any and all keyrings to load properties from the environment when constructed, rather than triggering the property configuration in `set_keyring()`. I'd much prefer that then start to proliferate the number of functions that need to be aware of `set_properties...`. The main problem with that is that adding `__init__` to a KeyringBackend would potentially be missed if subclasses implement one.

**Comment by jaraco** [comment]
Have a peek at the aforementioned commit and let me know if that fixes the issue or doesn't.

**Comment by hans2520** [comment]
`super.__init__()` was precisely what I was thinking should be the preferred design as I was reading your earlier comment @jaraco , as it's an expected norm that any inheriting class should follow unless they have a very strong reason not to.

It works for me via hand edit
