### ISSUE TITLE
Keyring 22.4.0+ fails to be imported in Python 3.8+

### ISSUE THREAD

**Issue by ccordoba12** [jaraco/keyring#499]
**Describe the bug**

Keyring fails to be imported in Python 3.8+ due to this import:

https://github.com/jaraco/keyring/blob/bab15d03d42c9173a6c06de2d4616713a498bf94/keyring/backend.py#L12

Since that functionality is part of the standard library in Python 3.8+, it needs to written as

```python
import importlib.metadata as metadata
```

for those versions (I understand the import is correct for older ones).

**To Reproduce**
1. Install Keyring 22.4.0 or later in Python 3.8+
2. Open a Python interpreter
3. `import keyring`

**Expected behavior**
Keyring shouldn't fail when imported.

**Environment**

- OS: Any operating system. This was discovered in Conda-forge when creating packages for Keyring:

  https://github.com/conda-forge/keyring-feedstock/pull/62

**Comment by Zac-HD** [comment]
Came here with a similar report; the trick is to make the dependency conditional on Python version and then to try importing the stdlib version before falling back to the backport on ImportError.  https://github.com/HypothesisWorks/hypothesis/search?q=importlib_metadata shows how we do that in Hypothesis (which indirectly depends on `keyring` - so thanks :smiling_face_with_three_hearts:)

**Comment by Zac-HD** [comment]
Based on the failing CI for #502, I think we're just asking for 473465ea386f2b32424f11295e472d8b9ffa90e1 to be reverted... it's a nicer interface for the implementation of `keyring`, but as a consumer of the code I'd prefer to avoid the extra dependency 😕

**Comment by jaraco** [comment]
> Based on the failing CI for #502, I think we're just asking for [473465e](https://github.com/jaraco/keyring/commit/473465ea386f2b32424f11295e472d8b9ffa90e1) to be reverted... it's a nicer interface for the implementation of `keyring`, but as a consumer of the code I'd prefer to avoid the extra dependency 😕

That extra dependency will become optional again in Python 3.10 alpha 7.

Keyring is attempting to use the new, cleaner interface for entry points afforded by [importlib_metadata 3.6](https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-6-0) and to avoid the deprecation of the prior interface.

See python/importlib_metadata#284 for motivation for this change.

I'd like for hypothesis to make a similar change. In a future version, I plan to [deprecate the dict-like behavior](https://github.com/python/importlib_metadata/pull/289) and eventually remove it (probably in importlib_metadata 4.x and Python 3.11).

I'd like to recommend that Hypothesis model after what keyring has done here. I think you'll find it's a nicer interface for Hypothesis as well. I'd be happy to help draft the change to enable that behavior, but I'd not presume to do if bumping a dependency (and expanding the number of Python versions on which the backport is necessary) is something your project would wish to avoid. Can you explain why having an added dependency is a problem?

**Comment by jaraco** [comment]
As reported, this issue is invalid. As can be clearly seen in 473465e, Keyring intentionally added the dependency for additional Python versions to adopt [new features in importlib_metadata 3.6](https://importlib-metadata.readthedocs.io/en/latest/history.html#v3-6-0).  The recommendation is to install the package with its declared dependencies and everything should work as designed.

Please let me know if I can advise conda on how to support this change.
