### ISSUE TITLE
Support Keychain Item Name Control

### ISSUE THREAD

**Issue by uurazzle** [jaraco/keyring#500]
Hi:

I was wondering if there was support for naming control for the keyring's implementation for keychain items allowing you more control over what the name for the keychain item?

**Comment by jaraco** [comment]
In general, no. Keyring provides an abstraction over many different implementations of secure storage (backends), and not all backends have a concept of an "item name". If you want control over the item name, you'll need to be more specific about what it is you're trying to achieve.

**Comment by uurazzle** [comment]
For example, if I want to use keyring's implementation to create a keychain item to a web server, I want the name of the item to reflect the script that was used to create it. For example, seems like other apps or scripts either name it like...

[SCRIPT/APP NAME] - [SERVER HOSTNAME]

or 

[SERVER HOSTNAME] [(SCRIPT/APP NAME)]

Like GitHub...

Uses the following naming conventions for Keychain items...

GitHub - https://api.github.com
github.com (email@domain.edu)

For my use, we have a project called [jctl](https://github.com/univ-of-utah-marriott-library-apple/jctl) and would like to use keyring and name Keychain items like...

jctl - myserver.edu

or 

myserver.edu (jctl)

Then it would make it easier for end-users to tell which item belongs to which application, service or script.

**Comment by jaraco** [comment]
Okay, so why not use keyring thus?

```
>>> hostname = 'myserver.edu'
>>> project = 'jctl'
>>> service = f'{hostname} ({project})'
>>>  keyring.set_password(service, username, password)
```

What could keyring do to facilitate what you desire? How would it know what conventions to follow?

**Comment by uurazzle** [comment]
Hi @jaraco:

Ok, thanks for your feedback. That looks like it will meet our needs. I will give it a try and let you know if we have any issues.

**Comment by jaraco** [comment]
Sounds good. I'll close the issue for now, but feel free to re-engage it or file a new one as appropriate.
