### ISSUE TITLE
keep asking for kwallet in gnome

### ISSUE THREAD

**Issue by braindevices** [jaraco/keyring#516]
**Describe the bug**
In gnome desktop, the keyring ask for kwallet if the required service does not exist. `keyring get test-vault user` ask to create new kwallet instead of reporting empty pwd or null.

**To Reproduce**
1. `keyring get test-vault user` or `keyring -b keyring.backends.chainer.ChainerBackend get test-vault user`
It ask to create new kwallet. If the test-valut exists, then it is ok.
2. `keyring -b keyring.backends.SecretService.Keyring get test-vault user` return nothing which is fine.

**Expected behavior**
should use password exists in gnome keyring or report no such service in gnome keyring.

**Environment**

- OS: ubuntu 20.04

```
$ pip list | grep keyring
keyring                 18.0.1               
keyrings.alt            3.4.0 
...
$ keyring --list-backends
keyring.backends.kwallet.DBusKeyring (priority: 4.9)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyrings.alt.file.PlaintextKeyring (priority: 0.5)
keyrings.alt.file.EncryptedKeyring (priority: 0.6)
...
```

**Additional context**
I do have kwalletd in system since I also installed some kde app. But they did not cause any problem before. This only happens in recent months.

**Comment by mitya57** [comment]
I think it's the same issue as #496, which is caused by the introduction of keyring chainer in keyring 16.0.

As a workaround, you can set the SecretService backend in the configuration file.

**Comment by braindevices** [comment]
@mitya57 thanks!

**Comment by braindevices** [comment]
hm... the keyringrc.cfg in homedir or current root does not have any effect. the ~/.local/share/python_keyring does not exists. 
```
python3 -c "import keyring.util.platform_; print(keyring.util.platform_.data_root())"
```
show `~/.local/share/python_keyring`

Any idea?

**Comment by braindevices** [comment]
ok, right now we have to put the file in the `~/.local/share/python_keyring`
