### ISSUE TITLE
`python -m keyring del foo bar` asks for the password but doesn't use it

### ISSUE THREAD

**Issue by mitya57** [jaraco/keyring#523]
I don't understand why this code asks for the password but doesn't verify or use it in any way:

https://github.com/jaraco/keyring/blob/d5bc1599d13495e23c3f7151765c29478d8d065d/keyring/cli.py#L87-L91

@jaraco Can you shed some light on this?

**Comment by jaraco** [comment]
Looks like that code goes back a long way: 1f6d225. Also appears it's never been used. So yeah, happy to delete it.
