### ISSUE TITLE
Unable to access NetworkManager wifi passwords in GNOME Keyring

### ISSUE THREAD

**Issue by signed-log** [jaraco/keyring#536]
**Describe the bug**

Due to the nature of wifi entries in gnome keyring, it is impossible to use those in keyring because of it's using of different keys

**To Reproduce**
1. Use NetworkManager (Linux only) as Wifi daemon
2. Connect to a wifi network
3. Open `nm-connection-editor`
4. Go to `Wi-Fi Security`
5. Click on the symbol at the far right of the password field and select `Store the password only for the user`
6. Check for password presence in `seahorse`

**Expected behavior**`

As with all password entries in GNOME Keyring, it should be able to query it as it report in `seahorse` as a `Saved pasword or login

**Environment**

- OS: openSUSE Tumbleweed 

```
$ pip list | grep keyring
keyring                       23.2.1
...
$ keyring --list-backends
...
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.SecretService.Keyring (priority: 5)
```

**Additional context**
`NetworkManager` wifi password are special entries in the GNOME Keyring with those entries :
![seahorse](https://i.imgur.com/4Ol7kmz.png)
If keyring is unlocked `nmcli` can access it, and it is readable through 
```bash
nmcli -show-secrets connection show <SSID>
```

EDIT:

I tested the backend `secretstorage` module, doing :
```py
with closing(secretstorage.dbus_init()) as c:
    collection = secretstorage.get_default_collection(c)
    items = collection.get_all_items()
    for i in items:
        print(i.get_attributes())
```
 It returns :
```py
{'application': 'Python keyring library', 'service': 'REDACTED', 'username': 'REDACTED', 'xdg:schema': 'org.freedesktop.Secret.Generic'}
{'connection-uuid': 'REDACTED', 'setting-key': 'psk', 'setting-name': '802-11-wireless-security', 'xdg:schema': 'org.freedesktop.NetworkManager.Connection'}
```

It appears that (I might be wrong) `keyring` is only supporting the `Generic` scheme and not the `NetworkManager` scheme. If I have time, I might be able to contribute the schema support

**Comment by mitya57** [comment]
The goal of python-keyring is to let your application access *its own* passwords and provide a cross-platform way to do it.

What you need to do is specific to Secret Service backend so it makes more sense to use a dedicated library for it (secretstorage) and not python-keyring.

With secretstorage it will be quite easy to do what you want. Just replace `get_all_items()` with `search_items({'setting-name': '802-11-wireless-security'})` in your snippet (add more search keys if you want).

See the documentation for details:
https://secretstorage.readthedocs.io/en/latest/collection.html#secretstorage.collection.Collection.search_items

**Comment by signed-log** [comment]
Sure, will be easier, thanks
