### ISSUE TITLE
Please add version string

### ISSUE THREAD

**Issue by raedrizqie** [jaraco/keyring#537]
When trying to compile jupyter_client, the test fails because one of the requirements is not met:

`spyder 5.1.5 has requirement keyring>=17.0.0, but you have keyring 0.0.0.`

Suggestion: Adding a version string in setup.cfg solves the problem.

**Comment by jaraco** [comment]
This project uses [setuptools_scm](/pypa/setuptools_scm) to manage versions (and store them authoritatively in one place, the repo tags). This means the project cannot be built from the github tarball. Is that what you're doing? Instead, you should install from PyPI or from the repo source:

```
pip install keyring
```

```
pip install git+https://github.com/jaraco/keyring
```

Either way will get you a valid install with the proper version in the metadata.

**Comment by raedrizqie** [comment]
> This project uses [setuptools_scm](/pypa/setuptools_scm) to manage versions (and store them authoritatively in one place, the repo tags). This means the project cannot be built from the github tarball. Is that what you're doing? Instead, you should install from PyPI or from the repo source:
> 
> ```
> pip install keyring
> ```
> 
> ```
> pip install git+https://github.com/jaraco/keyring
> ```
> 
> Either way will get you a valid install with the proper version in the metadata.

ok.. thank you
