### ISSUE TITLE
Retrieve password entries from the Keychain that weren't created by Keyring? 

### ISSUE THREAD

**Issue by adam10414** [jaraco/keyring#546]
**Describe the bug**
I'm not sure if this is by design, or if I'm just not using it correctly. Based on the examples, this library works fine. However, I'm attempting to retrieve information from the keychain that wasn't created by keyring.

If I create the credential with keyring, it can retrieve it just fine. However, if it was not created by keyring, then I'm unable to retrieve it from the keychain. Is this normal?

I've searched everywhere, and I can't find any references to this elsewhere, so I'm raising this question in hopes someone knows the answer. 

**To Reproduce**
1. Open keychain to find details of the credential you want to retrieve with keychain. 
2. Use either the terminal utility or the function in a python file, and attempt to retrieve it.
3. In both cases, this returns None and does not raise any errors.

**Expected behavior**
Either a raised error stating why the credential was not able to be retrieved, or the actual credential is returned.

**Environment**

- OS: macOS Big Sur 11.6.1

```
$ pip list | grep keyring
> keyring            23.0.1  
(I'm using this version of keyring because later versions do not install correctly on my machine. I've looked this up, and I am not running into the missing 'six' package. This is the latest version I'm able to get working.) 
...
$ keyring --list-backends
...
keyring.backends.macOS.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)

**Additional context**
Add any other context about the problem here.

**Comment by matthewsht** [comment]
adam10414 - I'm not one of the developers but a fellow user. When I asked nearly the same question the answer was in general, No. The reason is that most of the backends are quite rich in their "native" API's and so many of those credentials were created in ways unknown to keyring - which in general uses the simplest calls it can get away with (to remain compatible across backends). Open to being corrected.

**Comment by jaraco** [comment]
Keyring definitely supports loading some passwords created by other applications. There have been cases where I've seen passwords created (for example) by git and then loaded those with keyring.

Here's another example:

```
~ $ security add-generic-password -a jaraco -s 'Top Dog Service' -p password
~ $ keyring get 'Top Dog Service' jaraco
password
```

In that case, the generic password is added by the 'security' command-line and retrieved using keyring.

Currently, the macOS backend only supports loading "generic password" or "application password", so if the password you're attempting to retrieve is of a different type, that's currently unsupported, although that would be a nice feature to support.

Does that answer the question?

**Comment by adam10414** [comment]
Yes, thank you!
