### ISSUE TITLE
Reading browser keys in Gnome Keyring / KWallet

### ISSUE THREAD

**Issue by mbway** [jaraco/keyring#556]
I am having trouble using the keyring module to read the keys of chromium based browsers from the gnome keyring.
(which I'm looking into because of this issue https://github.com/yt-dlp/yt-dlp/issues/1073#issuecomment-996820081)

In KDE Plasma these browsers use KWallet where `keyring.get_password('Chromium Keys', 'Chromium Safe Storage')` will obtain the password.

using `dbus-monitor "interface='org.kde.KWallet'" "type=method_return"` while starting chromium it is
clear to see how the `keyring` call corresponds to what chromium itself is doing.
```
method call time=123 sender=: -> destination=org.kde.kwalletd5 serial=7 path=/modules/kwalletd5; interface=org.kde.KWallet; member=readPassword
   string "Chromium Keys"
   string "Chromium Safe Storage"
   string "Chromium"
```

But in Cinnamon using `debus-monitor` while starting chromium it appears that instead of querying using the service / username like with kwallet it instead just lists all the keys (then presumably iterating through to find the one corresponding to the browser)
```
method call time=123 sender=: -> destination=: serial=21 path=/org/freedesktop/secrets/collection/Default_5fkeyring/2; interface=org.freedesktop.DBus.Properties; member=GetAll
```
In Cinnamon, I have not found a way to obtain the keys using the `keyring` module. If I add my own key to the keyring I am able to retreive it with `keyring.get_password('my_service', 'my_user')` but the chromium key seems to be a different type of key with no associated service
![Screenshot from 2021-12-17 22-57-50](https://user-images.githubusercontent.com/4923501/146617587-7a110eb0-ca8d-4974-9ba0-1dd66800056e.png)

As a workaround, the following seems to work when the keyring backend is identified as being 'SecretService Keyring':
```python
import secretstorage
from contextlib import closing

with closing(secretstorage.dbus_init()) as con:
    col = secretstorage.get_default_collection(con)
    for item in col.get_all_items():
        if item.get_label() == '{} Safe Storage'.format(browser_keyring_name):
            password = item.get_secret()
```

Is there a way to use the keyring library to obtain the same results regardless of which keyring is being used rather than to handle the different backends separately?

**Comment by mitya57** [comment]
Keyring is not intended to be able to read passwords of other applications.

Using SecretService module sounds like a good idea here. Instead of iterating all passwords, you may try something like `col.search_items({'application': 'chromium'})`.

**Comment by mbway** [comment]
Ok, I mistook the library's intention. I thought it was an abstraction over multiple keyring services with a consistent API.
