### ISSUE TITLE
Any way to use gnome-keyring from the command line?

### ISSUE THREAD

**Issue by auwsom** [jaraco/keyring#562]
..without this utility? 

Hi, I'm hoping your expertise can help me with this error "secret-tool: Cannot create an item in a locked collection".

I got it to work once, but cant seem to get it to work on further calling of gnome-keyring-daemon --unlock.

I have a question posted here with more detail.
https://unix.stackexchange.com/questions/690295/error-secret-tool-cannot-create-an-item-in-a-locked-collection

Thank you for any help in advance.

**Comment by mitya57** [comment]
secret-tool is not part of this project.

python-keyring has a command-line interface (`python -m keyring`), but if you want to use it with gnome-keyring, you need to have your keyring unlocked.

If you are in a graphical environment, you will be prompted with an unlock dialog.

If you are in a headless environment, please follow this section of our README: <https://github.com/jaraco/keyring/blob/main/README.rst#using-keyring-on-headless-linux-systems>.
