### ISSUE TITLE
No recommended keyring backend (Linux headless)

### ISSUE THREAD

**Issue by deepthi-shetty** [jaraco/keyring#569]
**No recomended backend found on Linux**
When i run on Linux, I get this error:
```
RuntimeError: No recommended backend was available. Iinstall a recommended 3rd party backend package; or, install the keyrings.alt package if you want to use the non-recommended backends. See https://pypi.org/project/keyring for details.

```

The keyring that is set is:
```
keyring.backends.chainer.ChainerBackend (priority: 0)
```

This works on Windows though.

**Comment by jaraco** [comment]
Sorry to hear. The way keyring works is that it attempts to detect which backends are suitable. Is there a backend you expect to work? Did you follow the instructions in the readme?

**Comment by AlexanderLanin** [comment]
I'll just reuse this ticket since I have the same problem :-)

I've hacked backend.viable to show what is going on (maybe a good idea anyway?!):
```
    @properties.classproperty
    def viable(cls):
        try:
            cls.priority
        except RuntimeError as exc:
            print(f"{cls.__module__}.{cls.__name__} (not viable: {exc})")
            return False
        return True
```

Which now tells me:
```
keyring --list-backends
keyring.backends.kwallet.DBusKeyring (not viable: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11)
keyring.backends.macOS.Keyring (not viable: macOS required)
keyring.backends.kwallet.DBusKeyringKWallet4 (not viable: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11)
keyring.backends.libsecret.Keyring (not viable: libsecret required)
keyring.backends.SecretService.Keyring (not viable: Unable to initialize SecretService: Environment variable DBUS_SESSION_BUS_ADDRESS is unset)
keyring.backends.Windows.WinVaultKeyring (not viable: Requires Windows and pywin32)
keyring.backends.chainer.ChainerBackend (priority: -1)
keyring.backends.fail.Keyring (priority: 0)
```

**Comment by takluyver** [comment]
> Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
> Unable to initialize SecretService: Environment variable DBUS_SESSION_BUS_ADDRESS is unset

Those error messages suggest that you're in a headless environment (no desktop or window manager), since it's not finding D-Bus. If you're running a container or a VM, it's also isolated by default from any D-Bus that might be running outside.

There are some hints in the readme about how to use keyring in such situations: https://github.com/jaraco/keyring#using-keyring-on-headless-linux-systems
