### ISSUE TITLE
Make importlib_metadata optional on Python 3.10.

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#575]
> That extra dependency will become optional again in Python 3.10 alpha 7.

Could it be marked as required only for Python < 3.10 in `setup.cfg`?

_Originally posted by @dotlambda in https://github.com/jaraco/keyring/issues/503#issuecomment-1134170726_

**Comment by Mogost** [comment]
I noticed that in my project, only keyring depends on importlib_metadata.
What I don't understand is that all libraries put the dependency optional for python less than 3.8. Some examples are below

https://github.com/pytest-dev/pytest/blob/611b579d21f7e62b4c8ed54ab70fbfee7c6f5f64/setup.cfg#L51
https://github.com/PyCQA/flake8/blob/1c85f3d07c3aadf597db205dff597da2987745f7/setup.cfg#L45
https://github.com/sqlalchemy/sqlalchemy/blob/3d00de4cca7a80650316754f338317824f921940/setup.cfg#L38

**Comment by jaraco** [comment]
> What I don't understand is that all libraries put the dependency optional for python less than 3.8.

As observed in the PR, there have been [changes in importlib_metadata](https://importlib-metadata.readthedocs.io/en/latest/history.html) and [only some of those are available in importlib.metadata for Python 3.9 and earlier](https://github.com/python/importlib_metadata#compatibility). Since this project relies on `importlib_metadata` 3.6, it also needs `importlib.metadata` from Python 3.10 or later.

**Comment by jaraco** [comment]
> What I don't understand is that all libraries put the dependency optional for python less than 3.8.

As observed in the PR, there have been [changes in importlib_metadata](https://importlib-metadata.readthedocs.io/en/latest/history.html) and [only some of those are available in importlib.metadata for Python 3.9 and earlier](https://github.com/python/importlib_metadata#compatibility). Since this project relies on `importlib_metadata` 3.6, it also needs `importlib.metadata` from Python 3.10 or later.
