### ISSUE TITLE
Allow keychain to be specified in macOS

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#579]
Targeting a specific keychain at call time allows for much more flexibility in environments where developers have to use multiple keychains in the same script. for instance, environments that use identity tokens in the login chain, but use a separate keychain for API keys for SaaS services. With Stock keyring, one would have to use the hacky method mentioned in [this comment](https://github.com/jaraco/keyring/issues/369#issuecomment-456304754), or do some env var magic.

_Originally posted by @a350h in https://github.com/jaraco/keyring/issues/572#issuecomment-1136097453_

**Comment by jaraco** [comment]
@a350h: Please have a look at #580 and let me know if that would satisfy your needs.

**Comment by a350h** [comment]
At first glance, this is perfect! much better than my approach. Thanks a bunch!
