### ISSUE TITLE
issue with condition in py310compat.py

### ISSUE THREAD

**Issue by salahbsmdz** [jaraco/keyring#584]
**Describe the bug**
Based on setup.cfg `importlib_metadata` is required for python < 3.10 so the condition in `py310compat.py` should be `sys.version_info >= (3, 10)`

**Additional context**
1f6d925

**Comment by jaraco** [comment]
Sorry, but it's not a bug. I prefer the simpler syntax. There's no version `== (3, 10)`, so adding equality comparison is pointless.
