### ISSUE TITLE
devpi-client hook broken

### ISSUE THREAD

**Issue by fschulze** [jaraco/keyring#596]
The [``@suppress(KeyringError)``](https://github.com/jaraco/keyring/commit/314c8d36fa06090938f95d2672316471b15a6e65#diff-b0e6ff13ff76becf8aee3446689be4103ae1db3b2ba31748c7cb7b934affc033R17) line breaks the devpi-client hook. It looks like the argument spec is changed by it which causes pluggy to not pass in the arguments correctly. It happens when trying to ``devpi push`` a release to pypi and the password is not set in ``~pypirc`` which causes devpi-client to try the hook.

**Comment by fschulze** [comment]
It can more easily be triggered by ``devpi login username``.

**Comment by jaraco** [comment]
I'm slightly surprised that the argument spec isn't present, because [ContextDecorator uses](https://github.com/python/cpython/blob/7e36abbb7815b14777c207dba0fe6fcd41d6d37a/Lib/contextlib.py#L77-L82) [functools.wraps](https://docs.python.org/3/library/functools.html#functools.wraps).

**Comment by jaraco** [comment]
It looks like `inspect.getfullargspec` shows the raw args, but `inspect.signature` resolves the wrapping.

```
>>> inspect.getfullargspec(cl.devpiclient_get_password)
FullArgSpec(args=[], varargs='args', varkw='kwds', defaults=None, kwonlyargs=[], kwonlydefaults=None, annotations={})
>>> inspect.signature(cl.devpiclient_get_password)
<Signature (url, username)>
```

**Comment by jaraco** [comment]
[Docs say](https://docs.python.org/3/library/inspect.html#inspect.getfullargspec) that `getfullargspec` is discouraged and `signature` should be used:

> Note that [signature()](https://docs.python.org/3/library/inspect.html#inspect.signature) and [Signature Object](https://docs.python.org/3/library/inspect.html#inspect-signature-object) provide the recommended API for callable introspection, and support additional behaviours (like positional-only arguments) that are sometimes encountered in extension module APIs. This function is retained primarily for use in code that needs to maintain compatibility with the Python 2 inspect module API.

**Comment by jaraco** [comment]
Oh, the issue is known (https://github.com/pytest-dev/pluggy/issues/358) and already linked to #582.

**Comment by jaraco** [comment]
v23.9.3 provides a workaround, but the core issue should be fixed upstream in pluggy.
