### ISSUE TITLE
How can I donate to keyring?

### ISSUE THREAD

**Issue by Stevoisiak** [jaraco/keyring#604]
I have used keyring for a few years in my projects and would like to show my support. Is there a way I can donate money to the keyring project?

**Comment by jaraco** [comment]
Thanks Stevoisiak for showing your appreciation. This project is sponsored/supported by [Tidelift](https://tidelift.com/subscription/pkg/pypi-keyring?utm_source=pypi-keyring&utm_medium=referral&utm_campaign=github), so the best way to support the project is to subscribe to Tidelift (mainly for projects profiting from open source).

I've once started to register for Github Sponsors, but never completed it. Your message has inspired me to renew my effort on that, so keep an eye out for that on this and many other projects.

If you wish to make a personal donation, you are welcome to send a token of thanks. My handle is `jaraco` on cashapp, paypal, and venmo.

[![https://cash.app/$jaraco](https://cash.app/qr/$jaraco?size=288&margin=0)](https://cash.app/$jaraco)

<a href="https://paypal.me/jaraco"><img src="https://blog.jaraco.com/images/paypal.png" width=300></a>

[![https://venmo.com/u/jaraco](https://blog.jaraco.com/images/venmo.png)](https://venmo.com/u/jaraco)
