### ISSUE TITLE
Please clarify “Python Software Foundation License” status

### ISSUE THREAD

**Issue by musicinmybrain** [jaraco/keyring#607]
While the text of the [`LICENSE` file](https://github.com/jaraco/keyring/blob/main/LICENSE) is a standard MIT license, `setup.cfg` claims the “Python Software Foundation License” also applies.

https://github.com/jaraco/keyring/blob/2354d68e50633bc879581ce594df436ad8da85a1/setup.cfg#L13-L14

Could you please clarify the following?

- Does this license *actually* apply to `keyring`, either to the whole package or to some part of its sources?
- If the license applies, is it in addition to the MIT license (`AND`), or as an alternative license (dual-licensed, `OR`)?
- If the license applies, is the intended license text [`PSF-2.0`](https://spdx.org/licenses/PSF-2.0.html)?

Ideally, these could be clarified somewhere in the sources rather than only in this issue.

Thanks!

**Comment by jaraco** [comment]
The reason the license is present is there was originally an intention to eventually migrate this library to the Python stdlib, so by dual licensing, it would be trivial to expose the same functionality under Python's license. It's my understanding that the PSF license isn't valid for projects other than Python, so only the MIT license is relevant currently.

When I proposed recently to port this to stdlib, it was dismissed, so I'm no longer anticipating contributing this to Python.

I'm going to just drop the license and keep it simple.

**Comment by musicinmybrain** [comment]
Thanks for the explanation; that’s quite helpful.
