### ISSUE TITLE
[feature] Shell completions

### ISSUE THREAD

**Issue by Freed-Wu** [jaraco/keyring#608]
Like

- <https://github.com/andreafrancia/trash-cli/blob/master/setup.cfg#L31-L33>
- <https://github.com/inducer/pudb/blob/main/setup.py#L28>
- <https://github.com/piccolomo/plotext/blob/master/setup.py#L25>
- <https://github.com/wookayin/gpustat/blob/master/setup.py#L114>

TIA!

**Comment by jaraco** [comment]
Sounds good. Would someone be interested in helping implement these?
