### ISSUE TITLE
Use importlib.metadata on all python versions >3.8

### ISSUE THREAD

**Issue by jakkdl** [jaraco/keyring#628]
[Since `importlib.metadata` is available since python>3.8](https://docs.python.org/3/library/importlib.metadata.html), there's no reason to use `importlib_metadata` in those versions and require users to install an additional dependency. I think it should be as simple as modifying
https://github.com/jaraco/keyring/blob/19374c65876c14ea69dcc4a29fb9858fcbc3c749/keyring/py312compat.py#L7
and
https://github.com/jaraco/keyring/blob/3f29ffb062d391ff26319700140042a066c52fb4/setup.cfg#L25

**Comment by jaraco** [comment]
Thanks for the request.

> there's no reason to use `importlib_metadata`

Unfortunately, that's not correct. If you look at the last commit on py312compat.py, you'll be taken to #526, where you can see that `importlib_metadata` was bumped to solve a particular issue.
