### ISSUE TITLE
Can't store password on keychain with pyinstaller on MacOS Monterey

### ISSUE THREAD

**Issue by c-rei** [jaraco/keyring#629]
It works fine when I use my source, but when I run my app compiled by pyinstalller , I got the error like below.

Error 1:
Can't get password from keychain: (-25293, 'Security Auth Failure: make sure python is signed with codesign util')
Error 2:
Can't store password on keychain: (-67030, 'Security Auth Failure: make sure python is signed with codesign util')

My code just is to saving or get a password, like below.

```
keyring.set_password("my-pa02", "serial_number", key)
keyring.get_password("my-pa02", "serial_number")
```

**Environment**
- OS:  macOS Montorey
- Keyring: 23.13.1
-  Python: 3.8.10
- Pyinstaller: 5.10.1

Thanks any help.

**Comment by Ruben-Kruepper** [comment]
Did you sign your binaries with an Apple Developer key? The error message implies otherwise.

**Comment by jaraco** [comment]
It occurs to me that in a Pyinstaller case, it's not the Python executable that needs to be signed but the wrapper executable. I wonder if the error message should say "make sure _the executable_ is signed with codesign util". Even better would be to emit the exact executable (though I'm not sure if that's possible).

@c-rei Have you tried using [codesign](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html) to sign the executable produced by pyinstaller?

**Comment by c-rei** [comment]
Hi jaraco,

When I updated Pyinstaller, the executable is signed by default of Pyinstaller, so it worked.
Thanks your advices.
