### ISSUE TITLE
v24 breaks keyring_jeepney

### ISSUE THREAD

**Issue by firefart** [jaraco/keyring#646]
Hi,
it looks like the removal of `keyring.util.properties` in v24 broke [keyring_jeepney](https://gitlab.com/takluyver/keyring_jeepney) which seems to be pretty dead since 6 years. You might want to mention this in the Readme under third-party backends as keyring_jeepney is now non functional with the current version.

**Comment by mitya57** [comment]
I don't think someone needs keyring_jeepney, as now we have a built-in SecretStorage-based backend (which also uses jeepney under the hood).

**Comment by firefart** [comment]
https://github.com/genotrance/px Uses it / recommends it for headless systems
