### ISSUE TITLE
Request for documentation regarding the "service" parameter

### ISSUE THREAD

**Issue by wpd** [jaraco/keyring#658]
I apologize for opening this as an issue, but can you please point me at documentation for how the `service` parameter is used in the API.  The examples I see, specify that as `"system"`.  Is that the best/only option available to me?  What does `"system"` specify with regard to the keyring?  What other options might I choose?

Thank you.

--wpd

**Comment by jaraco** [comment]
I think "system" or "service" are used interchangeably. They refer to the system or service that is pertinent to the credential being stored (e.g. hostname or company or URL). You can use the value however you want; it's generally an opaque string.
