### ISSUE TITLE
"Anonymous credential has no username" on keyring get

### ISSUE THREAD

**Issue by koterpillar** [jaraco/keyring#694]
**Describe the bug**
Getting existing credentials using `keyring get` fails with an exception stacktrace showing "Anonymous credential has no username".

**To Reproduce**

```shell
$ keyring set aaaa bbbb
Password for 'bbbb' in 'aaaa': <enter password>
$ keyring get aaaa bbbb
Traceback (most recent call last):
  File "<snip>/keyring", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "<snip>/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 219, in main
    return cli.run(argv)
           ^^^^^^^^^^^^^
  File "<snip>/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 120, in run
    return method()
           ^^^^^^^^
  File "<snip>/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 132, in do_get
    getattr(self, f'_emit_{self.output_format}')(credential)
  File "<snip>/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 140, in _emit_plain
    if credential.username:
       ^^^^^^^^^^^^^^^^^^^
  File "<snip>/venvs/keyring/lib/python3.12/site-packages/keyring/credentials.py", line 39, in username
    raise ValueError("Anonymous credential has no username")
ValueError: Anonymous credential has no username
```

**Expected behavior**

`keyring get` should return the password set by `keyring set`.

**Environment**

- OS: macOS 14.6.1 (23G93)

```shell
$ pipx list | grep keyring <note: pipx>
package keyring 25.4.0, installed using Python 3.12.4
$ keyring --list-backends
keyring.backends.macOS.Keyring (priority: 5)
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.chainer.ChainerBackend (priority: -1)
```

**Additional context**

Works fine with 25.3.0, even with a password set by 25.4.0.

**Comment by valorl** [comment]
Yep, it seems like the introduction of `AnonymousCredentials`, which [throws](https://github.com/jaraco/keyring/blob/main/keyring/credentials.py#L39) on `.username` hasn't been handled properly in the CLI, as both [_emit_json](https://github.com/jaraco/keyring/blob/main/keyring/cli.py#L136) and [_emit_plain](https://github.com/jaraco/keyring/blob/main/keyring/cli.py#L140) will try to access it. (cc @zanieb)

**Comment by ffissore** [comment]
#695 contains a fix. Not sure if this goes against the design decision of introducing `AnonymousCredential`, but I don't have enough context to come up with something better
