### ISSUE TITLE
KWallet keyring should store service name in a folder rather than in username

### ISSUE THREAD

**Issue by jaraco** [jaraco/keyring#83]
In pull request `#21` (no longer available since migration from Bitbucket), Maciej demonstrates how it would be possible to have the KWallet keyring backend store the service name in its own unique field using the 'folder' concept of KWallet.

---
- Bitbucket: https://bitbucket.org/kang/python-keyring-lib/issue/83
- Originally reported by: Jason R. Coombs
- Originally created at: 2013-01-08T23:16:04.699

**Comment by jaraco** [comment]
I agree we should do this, but as I mentioned in the pull request, we should be careful about backward compatibility. In the past, Keyring has automatically migrated a user's data from older versions (usually a few minor releases past) before removing the migration support. I don't have any way to reach out to the users to ask what the impact of a manual migration or no migration would be, so I'm stuck recommending that we build an automatic migration for this feature as well. It's okay if the migration is not reversible, as long as the change is clearly communicated.

Maciej, can you work on a patch that only addresses this aspect and that performs automatic migration? Take a look at [the file location migration](https://bitbucket.org/kang/python-keyring-lib/src/fff4872e0b6be02ee2c7a6802d8f2c7129d210aa/keyring/backend.py?at=0.8#cl-290) for an example of something that worked.

Note that a migration will only be possible if KWallet facilitates enumerating all passwords, something the existing keyring doesn't yet demonstrate.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I'll work on that

---

Original comment by: Maciej Sitarz

**Comment by jaraco** [comment]
I started from writing tests and I'm not sure if it's doable, I mean the migration.

From already existing tests I assume that username, password and service name allow Unicode, whitespace and punctuation characters.

```
#!python

DIFFICULT_CHARS = string.whitespace + string.punctuation
UNICODE_CHARS = escape.u("""κόσμεНа берегу пустынных волнSîne klâwen durh die
wolken sint geslagen, er stîget ûf mit grôzer kraft""")
password = random_string(20, DIFFICULT_CHARS)
username = random_string(20, DIFFICULT_CHARS)
service = random_string(20, DIFFICULT_CHARS)

```

string.punctuation contains "@" which is used as a username/service separator.
I should probably exclude "@" for service name in my test, but knowing this I think the automatic migration won't be successful in 100% cases.

---

Original comment by: Maciej Sitarz

**Comment by jaraco** [comment]
I attached first version of a migration patch.

All tests go well, until I simulated second migration attempt "usernam@gmail.com" would be converted twice and broken.
Do you have some mechanism to run the migration only once on each system?

---

Original comment by: Maciej Sitarz

**Comment by jaraco** [comment]
When playing with bitbucket I deleted the wrong repository, the one from which I requested pull, so pull request `#21` disappeared :(

Happily I had the web page opened so I saved all the comments to disk.
I didn't want you too lose all the comments and thoughts so I shared them on dropbox, links below.

I'm really sorry, for the mess.

Comments from pull request `#21` (in few formats, choose whatever you like best)
- comments.pdf: http://db.tt/yGUODMn2 (Web page saved as PDF)
- comments.html: http://db.tt/hZIUA98m (HTML TXT file)
- comments_html.tgz: http://db.tt/HvmQARqZ (HTML files with graphics)

---

Original comment by: Maciej Sitarz

**Comment by jaraco** [comment]
Maciej,
  I apologize for the delay in getting to your question... and I'm afraid now I don't exactly understand.

  You say that a migration would cause a name to be converted twice, and thus broken. I don't understand how that could happen, if passwords are only migrated from a Python folder to other service-specific folders. I would think the implementation you drafted would be idempotent, thus not corrupting on a second run. Can you elaborate on the failure?

  As for supporting a service name with the `@` symbol, I don't believe there's any value in doing so, as the current implementation would not handle that scenario properly.

---

Original comment by: Jason R. Coombs

**Comment by jaraco** [comment]
I'm closing this as it has grown stale (and unfortunately is now difficult to trace given the migration from Bitbucket). @maciex please let me know if I can help port your patches to a Github pull request, especially if you want to revive this discussion.

**Comment by maciex** [comment]
@jaraco: How do you suggest to migrate already existing entries?
I see two possible approaches:
1. If "Python" folder exists, migrate all entries.
2. If "Python" folder exists, migrate only entries of the service we're currently running

**Comment by mitya57** [comment]
No objections for me (and I'm not much interested in KWallet backend, unlike the SecretService and GNOME ones).
